---
title: "Conclusiones"
---
La finalidad de este informe fue la realización de un análisis de los factores asociados al rendimiento académico, utilizando como medio la evaluación estandarizada “Sistema de Medición de la Calidad de la Educación”(SIMCE) y su relación con el contexto social. A partir de ello surgen tres conclusiones centrales.

En primer lugar, en relación con la hipótesis 2, se constata la profunda estratificación socioeconómica que caracteriza al sistema educativo chileno. El análisis bivariado demostró una asociación estructural (V. de Cramer = 0.73) entre el nivel socioeconómico del estudiante y la dependencia del establecimiento educativo. Este resultado implica que el sistema escolar chileno opera con una lógica de segregación donde los estudiantes de distintos grupos sociales tienden a no compartir espacios educativos. 

En segunda instancia, el modelo de regresión de regresión lineal múltiple explicó un 45.4% de la varianza en los puntajes SIMCE, aportando evidencia robusta a la hipótesis 1, lo cuál constituye un valor considerable dentro del campo de estudios sociales. Los resultados indican que, aún controlando por clima de convivencia escolar, la dependencia administrativa del establecimiento mantiene un efecto sustantivo sobre el desempeño académico: asistir a establecimiento educacional privado remunerado incrementa, en promedio, 56.2 puntos en el puntaje SIMCE en comparación con un establecimiento educacional municipal estatal, manteniendo constantes las demás variables del modelo. 

Por último, se releva el destacado rol del clima de convivencia escolar, validando la hipótesis 3. A pesar del peso de los factores estructurales, esta variable presentó un coeficiente positivo y estadísticamente significativo, evidenciando que la convivencia escolar tiene un retorno directo al rendimiento académico. Este efecto se mantiene independientemente de las características del establecimiento educacional, mostrando que el clima escolar es un recurso pedagógicamente relevante por sí mismo. 

Este informe presenta algunas limitaciones metodológicas que acotan el alcance de las conclusiones. Por una parte, el diseño transversal basado en datos del SIMCE 2024 sólo permite identificar asociaciones y no relaciones causales, además de dejar abierta la posibilidad de sesgos de selección vinculados a la autoselección de estudiantes de cada establecimiento. Por otro lado, la medición del clima de convivencia escolar mediante autorreportes puede vincular sesgos subjetivos o de deseabilidad social, lo que dificulta captar con precisión las condiciones reales del entorno escolar. Para futuras investigaciones, y considerando la relevancia de las políticas públicas mencionadas, previamente en la introducción, se sugiere avanzar hacia modelos multidimensionales que aislen el “efecto escuela” y estudios longitudinales que permitan observar cómo estas variables interactúan a lo largo de la trayectoria escolar.

