% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  a4paper,
  oneside]{scrbook}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=25mm,bottom=25mm,left=30mm,right=20mm]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{5}
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{multirow}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\AtBeginDocument{\hypersetup{linkcolor=black}}
% ---------- Paquetes tipograficos y microajustes ----------
\usepackage{microtype}        % mejor interletrado y justificado
\usepackage{csquotes}         % comillas tipograficas
\usepackage{iftex}
\ifPDFTeX\else
  % Seleccion de fuentes solo cuando XeTeX/LuaTeX esta disponible.
  \IfFontExistsTF{TeX Gyre Termes}{
    \setmainfont{TeX Gyre Termes}
  }{
    \IfFontExistsTF{Latin Modern Roman}{\setmainfont{Latin Modern Roman}}{}
  }
  \IfFontExistsTF{TeX Gyre Heros}{
    \setsansfont{TeX Gyre Heros}
  }{
    \IfFontExistsTF{Latin Modern Sans}{\setsansfont{Latin Modern Sans}}{}
  }
  \IfFontExistsTF{TeX Gyre Cursor}{
    \setmonofont{TeX Gyre Cursor}
  }{
    \IfFontExistsTF{Latin Modern Mono}{\setmonofont{Latin Modern Mono}}{}
  }
\fi
\usepackage{enumitem}         % listas compactas
\setlist{itemsep=.2em, topsep=.2em}

% ---------- KOMA-Script: estilo de titulos y espaciado ----------
\KOMAoptions{
  headings=big,
  parskip=half,
  fontsize=12pt,
  appendixprefix=true
}
\setlength{\parindent}{1.5em}
\setlength{\parskip}{0.6em}
\usepackage{indentfirst}
\usepackage{setspace}         % Control del interlineado del documento
\setstretch{1.5}

% ---------- Encabezados y pies (scrlayer-scrpage) ----------
\usepackage[automark,headsepline]{scrlayer-scrpage}
\clearpairofpagestyles
\automark[chapter]{chapter}
\ihead{\pagemark}
\ohead{\itshape\headmark}
\setheadsepline{0.4pt}
\renewcommand*{\chaptermarkformat}{}
\renewcommand*{\chapterpagestyle}{scrheadings}
\pagestyle{scrheadings}
\makeatletter
\let\ps@plain\ps@scrheadings
\makeatother
\cfoot{}

% ---------- Hipervinculos mas sobrios ----------
\usepackage{hyperref}
\hypersetup{
  colorlinks=true,
  linkcolor=black,
  citecolor=[rgb]{0.05,0.2,0.5},
  urlcolor=[rgb]{0.05,0.2,0.5},
  pdfauthor={\@author},
  pdftitle={\@title}
}

% ---------- Leyendas de figuras/tablas ----------
\usepackage[labelfont=bf,textfont=it]{caption}
\captionsetup{
  skip=8pt
}

% ---------- Tabla de contenidos ----------
\KOMAoptions{toc=graduated}
\RedeclareSectionCommand[tocnumwidth=3em]{chapter}
\RedeclareSectionCommand[tocindent=3.25em,tocnumwidth=2.8em]{section}
\RedeclareSectionCommand[tocindent=6.5em,tocnumwidth=2.5em]{subsection}
\makeatletter
\newcommand*{\tocdotfill}{\leavevmode\leaders\hbox to .6em{\hss.\hss}\hfill}
\makeatother
\RedeclareSectionCommand[toclinefill=\tocdotfill]{chapter}
\RedeclareSectionCommand[toclinefill=\tocdotfill]{section}
\RedeclareSectionCommand[toclinefill=\tocdotfill]{subsection}
\renewcommand*{\contentsname}{Tabla de contenido}
\setkomafont{chapterentry}{\normalfont}
\setkomafont{chapterentrypagenumber}{\normalfont}

% ---------- Viudas/Huerfanas y cortes de pagina ----------
\clubpenalty=10000
\widowpenalty=10000
\displaywidowpenalty=10000

% ---------- Entorno abstract para scrbook ----------
\providecommand{\abstractname}{Resumen}
\makeatletter
\@ifundefined{abstract}{
  \newenvironment{abstract}{
    \cleardoublepage
    \thispagestyle{plain}
    \null\vfill
    \begin{center}
      {\bfseries\Large \abstractname\par}
    \end{center}\vspace{1em}
    \begingroup
  }{
    \par\endgroup
    \vfill\null
    \cleardoublepage
  }
}{}
\makeatother

% ---------- Soporte de subtitulo desde YAML ----------
\makeatletter
\providecommand{\subtitle}[1]{\gdef\@subtitle{#1}}
\providecommand{\@subtitle}{}
\makeatother

\makeatletter
\newcommand{\facso@iflist}[4]{%
  \begingroup
    \def\addvspace##1{}%
    \def\numberline##1{##1}%
    \def\facso@target{#2}%
    \newcount\facso@entrycount
    \facso@entrycount=0\relax
    \long\def\contentsline##1##2##3{%
      \def\facso@this{##1}%
      \ifx\facso@this\facso@target
        \advance\facso@entrycount\@ne
      \fi
    }%
    \InputIfFileExists{\jobname.#1}{}{}%
  \endgroup
  \ifnum\facso@entrycount>0\relax
    #3%
  \else
    #4%
  \fi}
\renewcommand{\listoffigures}{%
  \facso@iflist{lof}{figure}{%
    \cleardoublepage
    \phantomsection
    \addchap*{Listado de Figuras}%
    \thispagestyle{scrheadings}%
    \markboth{Listado de Figuras}{Listado de Figuras}%
    \addcontentsline{toc}{chapter}{Listado de Figuras}%
    \@starttoc{lof}%
    \cleardoublepage
    \automark[chapter]{chapter}%
  }{}}
\renewcommand{\listoftables}{%
  \facso@iflist{lot}{table}{%
    \cleardoublepage
    \phantomsection
    \addchap*{Listado de Tablas}%
    \thispagestyle{scrheadings}%
    \markboth{Listado de Tablas}{Listado de Tablas}%
    \addcontentsline{toc}{chapter}{Listado de Tablas}%
    \@starttoc{lot}%
    \cleardoublepage
    \automark[chapter]{chapter}%
  }{}}
\makeatother

% --- Desactivar portada y abstract automaticos de Pandoc (PDF) ---
\AtBeginDocument{\let\maketitle\relax}
\renewenvironment{abstract}{}{}
\providecommand{\appendixname}{}
\providecommand{\appendixtocname}{}
\providecommand{\appendixpagename}{}
\renewcommand*{\appendixname}{Anexo}
\renewcommand*{\appendixtocname}{Anexos}
\renewcommand*{\appendixpagename}{Anexos}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{fontspec}
\usepackage{multicol}
\usepackage{hhline}
\newlength\Oldarrayrulewidth
\newlength\Oldtabcolsep
\usepackage{hyperref}
\makeatletter
\@ifpackageloaded{bookmark}{}{\usepackage{bookmark}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Tabla de contenidos}
\else
  \newcommand\contentsname{Tabla de contenidos}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{Listado de Figuras}
\else
  \newcommand\listfigurename{Listado de Figuras}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{Listado de Tablas}
\else
  \newcommand\listtablename{Listado de Tablas}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Lista

de

figuras}
\else
  \newcommand\figurename{Lista

de

figuras}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Lista

de

tablas}
\else
  \newcommand\tablename{Lista

de

tablas}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listado}
\newcommand*\listoflistings{\listof{codelisting}{Listado de Listados}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\ifLuaTeX
\usepackage[bidi=basic]{babel}
\else
\usepackage[bidi=default]{babel}
\fi
\babelprovide[main,import]{spanish}
% get rid of language-specific shorthands (see #6817):
\let\LanguageShortHands\languageshorthands
\def\languageshorthands#1{}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Reportes FACSO - Plantilla Quarto},
  pdfauthor={Nombre Apellido},
  pdflang={es},
  colorlinks=true,
  linkcolor={Maroon},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Reportes FACSO - Plantilla Quarto}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Tesis, informes e investigaciones}
\author{Nombre Apellido}
\date{24 de noviembre de 2025}

\begin{document}
\frontmatter
\maketitle

% --- title-pdf.tex personalizado para portada formal ---
\makeatletter
\providecommand{\subtitle}[1]{\gdef\@subtitle{#1}}
\providecommand{\@subtitle}{}
\providecommand{\frontmattercontext}{}
\providecommand{\advisorname}{}
\providecommand{\advisorlabel}{Profesor guia:}
\providecommand{\frontmatterlocation}{}
\InputIfFileExists{includes/cover-config.tex}{}{}

\newcommand{\PrintTitle}{%
  {\sffamily\bfseries\fontsize{24pt}{28pt}\selectfont \@title\par}%
}
\newcommand{\PrintSubtitle}{%
  \begingroup
  \edef\temp{\detokenize{\@subtitle}}%
  \ifx\temp\empty\relax
    % sin subtitulo
  \else
    {\sffamily\bfseries\large \@subtitle\par}%
  \fi
  \endgroup
}
\newcommand{\PrintAuthor}{%
  {\Large\bfseries \@author\par}%
}
\newcommand{\PrintDate}{%
  {\small \@date\par}%
}
\makeatother

\begin{titlepage}
\thispagestyle{empty}
\begin{center}
\vspace*{10mm}

% Logo o imagen institucional
\includegraphics[width=0.35\textwidth]{assets/cover.png}\par
\vspace{12mm}

% Titulo y subtitulo
\PrintTitle
\vspace{6mm}
\PrintSubtitle

\vspace{22mm}
\begingroup
\edef\temp{\detokenize{\frontmattercontext}}%
\ifx\temp\empty\relax
  % sin contexto adicional
\else
  {\normalsize \frontmattercontext\par}
\fi
\endgroup

\vspace{18mm}
\PrintAuthor

\vspace{16mm}
\begingroup
\edef\temp{\detokenize{\advisorname}}%
\ifx\temp\empty\relax
  % sin tutor
\else
  \rule{0.45\textwidth}{0.4pt}\par
  {\small \advisorlabel\ \advisorname\par}
\fi
\endgroup

\vfill
\begingroup
\edef\temp{\detokenize{\frontmatterlocation}}%
\ifx\temp\empty\relax
  % sin ubicacion
\else
  {\small \frontmatterlocation\par}
\fi
\endgroup
\PrintDate

\end{center}
\end{titlepage}

% Preliminares (numeros romanos) y estilo simple
\frontmatter
\pagestyle{scrheadings}

\setcounter{tocdepth}{2} % (o 1/3 segun prefieras)
\tableofcontents
\listoffigures
\listoftables


\mainmatter
\bookmarksetup{startatroot}

\chapter*{Abstract}\label{abstract}
\addcontentsline{toc}{chapter}{Abstract}

\markboth{Abstract}{Abstract}

\small\textbf{Palabras clave:} Sociologia, educacion, Chile \normalsize

Resumen en español (200-300). Expón propósito, método, resultados clave
y conclusiones. Puede incluir citas como Xie
(\citeproc{ref-xie2017bookdown}{2017}) y se actualizarán
automáticamente.

\bookmarksetup{startatroot}

\chapter*{Prefacio}\label{prefacio}
\addcontentsline{toc}{chapter}{Prefacio}

\markboth{Prefacio}{Prefacio}

Agradecimientos opcionales, dedicatorias, notas sobre financiamiento,
etc.

\mainmatter

\bookmarksetup{startatroot}

\chapter{Introducción}\label{introducciuxf3n}

\#Resumen El presente estudio analiza los determinantes de la confianza
en el Estado chileno utilizando datos de la encuesta LAPOP 2023.
Mediante la construcción de un índice sumativo de confianza en los tres
poderes del Estado (Ejecutivo, Legislativo y Judicial), se evalúa su
relación con la edad, la perspectiva de interés de los políticos y la
confianza en las Municipalidades. Los resultados indican que no existe
una correlación significativa entre la edad y la confianza en el Estado,
pero sí se evidencian correlaciones positivas moderadas y grandes con la
perspectiva de interés de los políticos y la confianza en las
municipalidades, respectivamente.

En el presente trabajo se analiza el concepto de confianza en el Estado
de acuerdo a un índice promediado que tome en cuenta la confianza de los
tres poderes del Estado (ejecutivo, legislativo y judicial) en orden de
poder capturar las percepciones que la ciudadanía chilena tiene respecto
a sus representantes.

El Estado se comprenderá como una organización social que administra y
centraliza el poder soberanamente (Schaub, 2004) y que se compone de sus
tres poderes. Montesquieu plantea que esta división surge con la función
de evitar la centralización del poder y con ello la posibilidad de
tiranía, lo que implica transgresión del derecho en su forma
constitucional y civil (Fuentes, 2011). Así, es que la división de
poderes surge con la función de garantizar ciertos marcos que limiten la
acción política, lo que otorga confianza en el Estado.\textbar{}

En particular el Estado se compone del poder ejecutivo, en el cual se
destaca la figura del presidente quien administra el Estado y tiene por
objeto garantizar el orden y la seguridad pública. En segundo lugar el
poder legislativo quien tramita los proyectos de ley y en tercer lugar
el poder judicial quien tiene la facultad de aplicar los ordenamientos
jurídicos del Estado. (Biblioteca del Congreso Nacional de Chile, s.
f.).

Según la OECD (2024) las democracias a nivel global presentan problemas
sistemáticos que se traducen en polarización y tensiones, en Chile,
particularmente, esto se traduce en una baja a la confianza en
instituciones públicas; La baja en confianza institucional, si bien
responde a una crisis generalizada globalmente, en Chile tiene las
características de coincidir con grandes eventos sociopolíticos, de esta
forma, se dan cosas como que el pico de confianza en 2015 coincide con
la aprobación de una reforma electoral, mientras que los bajos niveles
de confianza en 2020 siguieron a las protestas sociales de 2019 (OECD,
2024).

La confianza en las instituciones como el gobierno, congreso y
tribunales es generalmente baja, siendo el congreso la que posee menor
confianza entre las 3 con un 8\%; Esto contrasta con otra instituciones
con mayor legitimidad como la PDI o carabineros, que se encuentran en el
primero y el tercer puesto respectivamente de mayor confianza (CEP,
2025). Con esto se puede decir que la confianza en las instituciones
gubernamentales está mayormente debilitada en cuanto estas refieren a
los poderes del Estado. La baja en la confianza es un fenómeno altamente
perjudicial, pues debilita el aparato público en tanto éste no tiene una
real capacidad de representación de las personas. Esto, pues las
personas tienen un menor incentivo en la participación
institucionalizada, vuelve al aparato estatal más lento (Keefer y
Scartascini, 2022), lo que en Chile se puede ver particularmente con las
bajas electorales en elecciones no obligatorias. De la misma forma, la
desconfianza afecta a la calidad de las políticas públicas en la manera
que los ciudadanos no creen que estas serán eficientes o que ellos
mismos se verán beneficiados, de la misma forma, así mismo, pierden la
confianza en que sus necesidades son escuchadas y tomadas en cuenta a la
hora de implementar las políticas (Keefer y Scartascini, 2022). En base
a esto, definimos la confianza de acuerdo a la definición conceptual de
Irarrázaval y Cruz (2023), que la caracteriza como la expectativa que el
otro actuará acorde a las normas sociales, de manera honesta o al menos
no perjudicial hacia el prójimo; de la misma forma, la confianza puede
tener expectativas en la capacidad o en la integridad, ambas
fundamentales para el entendimiento de la confianza.

Se ha decidido entonces construir un índice sumativo para conocer la
confianza en el Estado a partir de la confianza en cada poder,
permitiendo mayor precisión en la medición, reconociendo las
particularidades de cada poder. Se hace relevante ya que para el
correcto funcionamiento de cada uno, se necesita exista confianza
pertinente que permita su quehacer y ejercicio de soberanía. Los
municipios y sus propias instituciones por otra parte, serán analizados
como forma de gobierno local de vinculación territorial directa separada
del gobierno central. Esto por su fenómeno político a nivel nacional en
tanto podría establecerse una incidencia en la valoración de este tipo
de organismos y sus capacidades en la confianza general del Estado en
términos generalizados (Fuentes, 2018).

El presente trabajo tiene como objetivo medir la relación que existe
entre la confianza según poderes del Estado, con esto se esperan 4
grandes hipótesis:

Existe una relación entre confianza en el Estado y creencia en el
interés del gobierno por la opinión pública (H0= no existe relación
entre la confianza en el Estado y creencia en el interés del gobierno
por la opinión pública)

La confianza en el Estado es menor en población joven que en
generaciones mayores. (H0 = confianza en el Estado es igual o mayor en
población joven que en generaciones mayores)

Existe una relación proporcional entre la confianza en el Estado y la
confianza en los organismos municipales y locales. (H0= No existe una
relación proporcional entre la confianza en el Estado y la confianza en
los organismos municipales y locales).

Existe una relación positiva entre la percepción en el interés del
gobierno por la opinión pública (interés de los políticos) y la
confianza en las municipalidades.\\
(H0= Existe una relación positiva entre la percepción en el interés del
gobierno por la opinión pública (interés de los políticos) y la
confianza en las municipalidades).

\bookmarksetup{startatroot}

\chapter{Antecedentes conceptuales y
empíricos}\label{antecedentes-conceptuales-y-empuxedricos}

\bookmarksetup{startatroot}

\chapter{Metodología}\label{metodologuxeda}

\section{Datos}\label{datos}

Para la realización del trabajo, se utilizó la base de datos del
\textbf{Laboratorio de Opinión Pública LAPOP 2023}. La encuesta fue
aplicada entre junio y agosto de 2023 como forma de agregar a Chile al
proyecto de ``AmericasBarometer'' el cual se actualiza de forma
periódica. La muestra constó de 1653 personas adultas con habilidad para
votar y se aplicó en diferentes regiones del país procurando tener datos
desde el norte hasta el sur de Chile con grupos de 6 áreas urbanas y
rurales (Vanderbilt University, 2023).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{options}\NormalTok{(}\AttributeTok{scipen =} \DecValTok{999}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{"pacman"}\NormalTok{)}
\NormalTok{pacman}\SpecialCharTok{::}\FunctionTok{p\_load}\NormalTok{(tidyverse,    }
\NormalTok{               summarytools, }
\NormalTok{               sjmisc,       }
\NormalTok{               sjPlot,       }
\NormalTok{               haven,}
\NormalTok{               readxl,}
\NormalTok{               psych, }
\NormalTok{               stargazer,}
\NormalTok{               ktnir,}
\NormalTok{               kableExtra,}
\NormalTok{               table1,}
\NormalTok{               janitor, }
\NormalTok{               crosstable) }

\NormalTok{dataLAPOP }\OtherTok{\textless{}{-}} \FunctionTok{read\_dta}\NormalTok{(}\StringTok{"input/CHL\_2023\_LAPOP\_AmericasBarometer\_v1.0\_w.dta"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\section{Variables}\label{variables}

A partir de la base de datos, se seleccionaron las variables de
confianza en el congreso (B13), confianza en la corte suprema (B31) y
confianza en el presidente (B21a) para generar un indice promediado que
reflejase la confianza en el Estado.

Para comparar esta indice también se seleccionaron las variables de edad
(q2), ``A los politicos les importa mi opinion/intereses'' (eff1) y
confianza en la municipalidad (b32). La variable de edad es de tipo
razón, mientras que las otras dos son de tipo ordinal y asumen valores
de (1-7) según el nivel de confianza (Poca confianza - Mucha confianza).
Se renombraron las variables para facilitar la comprensión.

Finalmente, se utilizo una eliminación \emph{listwise} de casos
perdidos. En la toma de esta decision se considero la simpleza de la
función, junto con la reducción de casos despreciable que tuvo como
resultado.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}}\NormalTok{ dataLAPOP }\SpecialCharTok{\%\textgreater{}\%}                       \CommentTok{\#Selección de Variables}
  \FunctionTok{select}\NormalTok{(b13, b21a, b31, b32, eff1, q2) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{na.omit}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}
    \AttributeTok{cCongreso =}\NormalTok{ b13,            }\CommentTok{\#Confianza en el Congreso}
    \AttributeTok{cPresid =}\NormalTok{ b21a,             }\CommentTok{\#Confianza en el Presidente}
    \AttributeTok{cCSup =}\NormalTok{ b31,                }\CommentTok{\#Confianza en la Corte Suprema}
    \AttributeTok{cMuni =}\NormalTok{ b32,                }\CommentTok{\#Confianza en la Municipalidad}
    \AttributeTok{intPol =}\NormalTok{ eff1,              }\CommentTok{\#Creencia en los intereses de los políticos}
    \AttributeTok{edad =}\NormalTok{ q2)                   }\CommentTok{\#Edad}
\end{Highlighting}
\end{Shaded}

Para la construcción del índice se utilizó la sección de confianza en
las instituciones del cuestionario LAPOP, específicamente las preguntas
¿hasta qué punto tiene usted confianza en el congreso?, ¿hasta qué punto
tiene usted confianza en el presidente?, ¿hasta qué punto tiene usted
confianza en la Corte Suprema de Justicia? Las tres variables son de
tipo likert y abarcan un rango del 1 al 7, en donde 1 es nada de
confianza y 7 es mucha confianza.~

Con la creación del índice se logra medir el concepto de
\textbf{confianza en el Estado} de forma más completa que si se hubiera
elegido solo una pregunta, pues de esta forma se abarcan 3 dimensiones
del concepto de confianza.

Se comparó el índice no ponderado, como variable dependiente, de tres
variables independientes para ver su relación con distintos aspectos y
opiniones.

\#\#\#Cohesión del indice: En base a los criterios de cohesión interna
de los indices que señala Cronbach L.J. (1951), el índice muestra una
alta consistencia interna, como lo demuestra un \textbf{alfa de
Cronbach} de

\textbf{𝛼 = {[}0.73{]} (𝑘 = {[}3{]})}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#| echo: true}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{confEstAlpha }\OtherTok{\textless{}{-}}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{select}\NormalTok{(cCSup, cPresid, cCongreso) }\CommentTok{\#Crear indice Confianza en el Estado}

\NormalTok{data}\SpecialCharTok{$}\NormalTok{confEst }\OtherTok{\textless{}{-}}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(cCSup, cPresid, cCongreso) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\#Creamos variable del indice}
  \FunctionTok{rowMeans}\NormalTok{(}\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{alpha}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{confEstAlpha) }\CommentTok{\#Revisar cohesión interna indice}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Reliability analysis   
Call: alpha(x = data$confEstAlpha)

  raw_alpha std.alpha G6(smc) average_r S/N   ase mean  sd median_r
      0.73      0.74    0.67      0.48 2.8 0.012  3.1 1.4     0.52

    95% confidence boundaries 
         lower alpha upper
Feldt      0.7  0.73  0.75
Duhachek   0.7  0.73  0.75

 Reliability if an item is dropped:
          raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
cCSup          0.50      0.51    0.34      0.34 1.0    0.025    NA  0.34
cPresid        0.74      0.74    0.59      0.59 2.8    0.013    NA  0.59
cCongreso      0.68      0.68    0.52      0.52 2.2    0.016    NA  0.52

 Item statistics 
             n raw.r std.r r.cor r.drop mean  sd
cCSup     1574  0.86  0.87  0.78   0.67  3.2 1.6
cPresid   1574  0.80  0.77  0.57   0.48  3.2 2.0
cCongreso 1574  0.77  0.79  0.64   0.52  3.0 1.6

Non missing response frequency for each item
             1    2    3    4    5    6    7 miss
cCSup     0.22 0.13 0.20 0.21 0.15 0.06 0.02    0
cPresid   0.32 0.09 0.14 0.16 0.14 0.09 0.06    0
cCongreso 0.28 0.14 0.20 0.21 0.13 0.04 0.02    0
\end{verbatim}

\#\#Estadísticos descriptivos de las variables dependiente e
independientes.

\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X>{\raggedleft}X}
\toprule
 & vars & n & mean & sd & median & trimmed & mad & min & max & range & skew & kurtosis & se\\
\midrule
confEst & 1 & 1574 & 3.132995 & 1.400951 & 3 & 3.095238 & 1.4826 & 1 & 7 & 6 & 0.1958902 & -0.7679978 & 0.0353119\\
edad & 2 & 1574 & 42.320203 & 16.321403 & 40 & 41.243651 & 16.3086 & 18 & 90 & 72 & 0.5300557 & -0.5266385 & 0.4113913\\
intPol & 3 & 1574 & 3.180432 & 1.849513 & 3 & 3.034127 & 2.9652 & 1 & 7 & 6 & 0.3352215 & -0.9866029 & 0.0466181\\
cMuni & 4 & 1574 & 3.954892 & 1.685697 & 4 & 3.996032 & 1.4826 & 1 & 7 & 6 & -0.2299862 & -0.7206085 & 0.0424891\\
\bottomrule
\end{longtabu}

\section{Métodos}\label{muxe9todos}

Se seleccionaron para el análisis descriptivo tablas, gráficos y
estadísticos descriptivos. En específico se utilizó un histograma y una
nube de puntos para destacar informaciones relevan, los cuales fueron
interpretados. Para el analisis bivariado se utilizó el coeficiente de
correlación de \textbf{Pearson} (\(r\)), para la relación entre la
variable dependiente y las 3 variables independientes, esto ya que la
dependiente tiene caracter numerico y las independientes categorico, por
lo cual corresponde ese tipo de correlacion. Se evaluó la significancia
estadística (p-valor \textless{} 0.05) y el tamaño y dirección del
efecto siguiendo los criterios de Cohen (1988). Se utilizó Chi2 para
asociacion de las variables categoricas percepción de interes de los
politicos sobre la opinión publica con la confianza en las
municipalidades.

\bookmarksetup{startatroot}

\chapter{Análisis}\label{anuxe1lisis}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#| echo: false}

\FunctionTok{options}\NormalTok{(}\AttributeTok{scipen =} \DecValTok{999}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{"pacman"}\NormalTok{)}
\NormalTok{pacman}\SpecialCharTok{::}\FunctionTok{p\_load}\NormalTok{(tidyverse,    }
\NormalTok{               summarytools, }
\NormalTok{               sjmisc,       }
\NormalTok{               sjPlot,       }
\NormalTok{               haven,}
\NormalTok{               readxl,}
\NormalTok{               psych, }
\NormalTok{               stargazer,}
\NormalTok{               ktnir,}
\NormalTok{               kableExtra,}
\NormalTok{               table1,}
\NormalTok{               janitor, }
\NormalTok{               crosstable,}
\NormalTok{               broom,}
\NormalTok{               gginference,}
\NormalTok{               sjstats,}
\NormalTok{               rempsyc,}
\NormalTok{               dplyr) }
\CommentTok{\#Cargar base de datos {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\NormalTok{dataLAPOP }\OtherTok{\textless{}{-}} \FunctionTok{read\_dta}\NormalTok{(}\StringTok{"input/CHL\_2023\_LAPOP\_AmericasBarometer\_v1.0\_w.dta"}\NormalTok{)}

\CommentTok{\#Selección de variables {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{data }\OtherTok{\textless{}{-}}\NormalTok{ dataLAPOP }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(b13, b21a, b31, b32, eff1, q2) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{na.omit}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}
    \AttributeTok{cCongreso =}\NormalTok{ b13,}
    \AttributeTok{cPresid =}\NormalTok{ b21a,}
    \AttributeTok{cCSup =}\NormalTok{ b31,}
    \AttributeTok{cMuni =}\NormalTok{ b32,}
    \AttributeTok{intPol =}\NormalTok{ eff1, }
    \AttributeTok{edad =}\NormalTok{ q2}
\NormalTok{  )}

\CommentTok{\#Variable Dependiente {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{confEstAlpha }\OtherTok{\textless{}{-}}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{select}\NormalTok{(cCSup, cPresid, cCongreso) }\CommentTok{\#Crear indice Confianza en el Estado}

\NormalTok{data}\SpecialCharTok{$}\NormalTok{confEst }\OtherTok{\textless{}{-}}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(cCSup, cPresid, cCongreso) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\#Creamos variable del indice}
  \FunctionTok{rowMeans}\NormalTok{(}\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{df\_confEst }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{confEst =} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{na.omit}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{confEst)))}
\end{Highlighting}
\end{Shaded}

\section{Análisis descriptivo}\label{anuxe1lisis-descriptivo}

Frente a la observación de los estadísticos del indice de confianza en
el Estado, se pueden plantear ciertas conjeturas. Para empezar, es
importante recordar que el indice promediado va de 1 a 7 en niveles de
confianza (1: Muy poca confianza, 7: Mucha confianza).

Tomando esto en consideración, que la media asuma un valor de
\textbf{3.13} implica que la confianza en el Estado es más baja que
alta, lo que se refuerza con el resultado de la mediana (\textbf{3}).

Además de esto los cuartiles (\textbf{Q1= 2, Q3= 4.25}) confirman que el
nivel de confianza en el Estado se encuentra acumulado en el nivel bajo.

Finalmente el valor de \textbf{1.4} de desviación estándar refleja una
gran variabilidad en los valores asumidos por el indice, sin que se
llegue a una polarización completa.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{stargazer}\NormalTok{(}
  \FunctionTok{as.data.frame}\NormalTok{(df\_confEst),}
  \AttributeTok{type =} \StringTok{"text"}\NormalTok{,}
  \AttributeTok{title =} \StringTok{"Estadísticos Básicos de confianza Estado"}\NormalTok{,}
  \AttributeTok{summary.stat =} \FunctionTok{c}\NormalTok{(}\StringTok{"n"}\NormalTok{,}\StringTok{"mean"}\NormalTok{,}\StringTok{"sd"}\NormalTok{,}\StringTok{"min"}\NormalTok{,}\StringTok{"p25"}\NormalTok{,}\StringTok{"median"}\NormalTok{,}\StringTok{"p75"}\NormalTok{,}\StringTok{"max"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Estadísticos Básicos de confianza Estado
===================================================================
Statistic   N   Mean  St. Dev.  Min  Pctl(25) Median Pctl(75)  Max 
-------------------------------------------------------------------
confEst   1,574 3.133  1.401   1.000  2.000   3.000   4.250   7.000
-------------------------------------------------------------------
\end{verbatim}

En el histograma contiguo se percibe algo similar. Se observa que la
distribución es asimétrica y sesgada a la izquierda (negativa), lo que
sugiere que la mayoría de las personas tienden a tener menos confianza
en el Estado. Respecto a la tendencia central, la mayoría de las
observaciones se ubican en los puntos 0, 3 y 4, siendo cercanas al
promedio (\textbf{3.13}) y mediana (\textbf{3}) lo que sugiere que
existe una poca a mediana confianza en el Estado. Se observan gran
cantidad de observaciones en el punto 0 y muy pocas en los puntos 6 y 7.

En general, se puede decir del histograma que existe una poca a mediana
confianza en el Estado dentro de las observaciones.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#| echo: true}

\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ confEst)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ ..density..), }\AttributeTok{fill =} \StringTok{"lightgreen"}\NormalTok{, }\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Grafico 1:Distribución de la confianza en el Estado"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Confianza en el Estado"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Densidad"}\NormalTok{,}
       \AttributeTok{caption =} \StringTok{"Fuente: Elaboración propia en base a LAPOP 2023"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{04-resultados_files/figure-pdf/unnamed-chunk-3-1.pdf}

Para finalizar el análisis descriptivo de la confianza en el Estado en
Chile, se elaboró una comparación de promedios de confianza en el Estado
según los distintos grupos etarios.

El gráfico nos muestra la relación entre la confianza en el Estado
(confEst) y las edades en promedio presentadas en distintos grupos. A
partir de esto y la línea de tendencia (línea azul), se observa que no
existe una relación significativa entre la edad y la confianza en el
Estado. Es decir, al aumentar la edad, la confianza (en promedio) se
mantiene estadísticamente estable (posee una pendiente casi horizontal).

Al analizar los tramos de edad representados por los puntos, existe un
comportamiento no lineal;

Edad (18-28): La confianza en promedio es más alta en comparación con
los tramos intermedios, ubicándose el punto visiblemente por encima de
la línea de tendencia.

Edad (28-68): Posee una disminución en la confianza en promedio, este
rango etario se sutura por debajo de la media estimada, mostrando mayor
desconfianza.

Edad (68-79+): La confianza vuelve a encontrarse sobre el promedio,
superando la línea de tendencia, alcanzando niveles superiores al primer
rango de edad.

Los grupos con mayor variabilidad aparente son los extremos etarios
encuestados, lo que indica que, aunque el promedio es alto, podría haber
diferencias significativas en los patrones de confianza dentro de estos
rangos de edad. Por otro lado, la zona central (28-68) muestra una
dispersión levemente más contenida pero consistentemente baja en
confianza.

Además es inevitable considerar que al estar estudiando variables tipo
escala Likert de tipo ordinal (1 a 7), donde el promedio es 3.25, los
rangos de edad a pesar de estar con mayor valor en los extremos, siguen
estando pegadas una de las otra. Por lo mismo no puede haber mayor
diferencia entre las respuestas segun la edad del encuestado.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#| echo: true}

\DocumentationTok{\#\# Grafico Edad {-} Confianza en el Estado {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{edad\_cortes }\OtherTok{\textless{}{-}} \FunctionTok{cut}\NormalTok{(              }\CommentTok{\#División de la edad de 10 en 10}
\NormalTok{  data}\SpecialCharTok{$}\NormalTok{edad,}
  \AttributeTok{breaks =} \FunctionTok{c}\NormalTok{(}\DecValTok{18}\NormalTok{, }\DecValTok{28}\NormalTok{, }\DecValTok{38}\NormalTok{, }\DecValTok{48}\NormalTok{, }\DecValTok{58}\NormalTok{, }\DecValTok{68}\NormalTok{, }\DecValTok{78}\NormalTok{, }\DecValTok{90}\NormalTok{),}
  \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"18–28"}\NormalTok{, }\StringTok{"29–38"}\NormalTok{, }\StringTok{"39–48"}\NormalTok{, }
             \StringTok{"49{-}58"}\NormalTok{, }\StringTok{"59{-}68"}\NormalTok{, }\StringTok{"69{-}78"}\NormalTok{, }\StringTok{"79+"}\NormalTok{)) }

\NormalTok{grafico1 }\OtherTok{\textless{}{-}}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%}                 \CommentTok{\#Creación objeto para hacer gráfico}
  \FunctionTok{group\_by}\NormalTok{(edad\_cortes) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{mean\_confEst =} \FunctionTok{mean}\NormalTok{(confEst, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{mean\_edad =} \FunctionTok{mean}\NormalTok{(edad, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ungroup}\NormalTok{()}

\FunctionTok{ggplot}\NormalTok{(grafico1, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ mean\_edad, }\AttributeTok{y =}\NormalTok{ mean\_confEst)) }\SpecialCharTok{+} \CommentTok{\#Gráfico edad{-}confEst}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \DecValTok{3}\NormalTok{, }\AttributeTok{color =} \StringTok{"hotpink"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =}\NormalTok{ edad\_cortes), }\AttributeTok{nudge\_y =} \FloatTok{0.08}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Confianza Estado promedio por grupos de edad"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Edad"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Media ConfEst"}\NormalTok{ ,}
    \AttributeTok{caption =} \StringTok{"Fuente: Elaboración propia en base a LAPOP 2023"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{04-resultados_files/figure-pdf/grafico-ejemplo-1.pdf}

Por otro lado, respecto a la relación entre la variable de ``A los
políticos les importa mi opinion/interes'' y la variable ``Confianza en
la Municipalidad'' se observa una alta tasa de centralización en las
opiniones de ambas variables. Sin embargo, se puede notar que se
encuentran más concentrados los datos en la intersección de ``En
desacuerdo'' que en la de ``De acuerdo'' lo que indica que existen más
personas que no estan alineadas con los políticos y que no confian en
las Municipalidades que quienes si lo estan y si confian.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#| echo: true}

\NormalTok{data}\SpecialCharTok{$}\NormalTok{intPol\_3cat }\OtherTok{\textless{}{-}} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{  data}\SpecialCharTok{$}\NormalTok{intPol }\SpecialCharTok{\%in\%} \DecValTok{1}\SpecialCharTok{:}\DecValTok{2} \SpecialCharTok{\textasciitilde{}} \StringTok{"En desacuerdo"}\NormalTok{,}
\NormalTok{  data}\SpecialCharTok{$}\NormalTok{intPol }\SpecialCharTok{\%in\%} \DecValTok{3}\SpecialCharTok{:}\DecValTok{5} \SpecialCharTok{\textasciitilde{}} \StringTok{"Ni acuerdo ni desacuerdo"}\NormalTok{,}
\NormalTok{  data}\SpecialCharTok{$}\NormalTok{intPol }\SpecialCharTok{\%in\%} \DecValTok{6}\SpecialCharTok{:}\DecValTok{7} \SpecialCharTok{\textasciitilde{}} \StringTok{"De acuerdo"}\NormalTok{)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{cMuni\_3cat }\OtherTok{\textless{}{-}} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{  data}\SpecialCharTok{$}\NormalTok{cMuni }\SpecialCharTok{\%in\%} \DecValTok{1}\SpecialCharTok{:}\DecValTok{2} \SpecialCharTok{\textasciitilde{}} \StringTok{"En desacuerdo"}\NormalTok{,}
\NormalTok{  data}\SpecialCharTok{$}\NormalTok{cMuni }\SpecialCharTok{\%in\%} \DecValTok{3}\SpecialCharTok{:}\DecValTok{5} \SpecialCharTok{\textasciitilde{}} \StringTok{"Ni acuerdo ni desacuerdo"}\NormalTok{,}
\NormalTok{  data}\SpecialCharTok{$}\NormalTok{cMuni }\SpecialCharTok{\%in\%} \DecValTok{6}\SpecialCharTok{:}\DecValTok{7} \SpecialCharTok{\textasciitilde{}} \StringTok{"De acuerdo"}\NormalTok{)}


\DocumentationTok{\#\#Gráfico de relación entre intPol y cMuni}
\FunctionTok{label}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{intPol\_3cat) }\OtherTok{=} \StringTok{"A los politicos les importa mi opinion/intereses"}
\FunctionTok{label}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{cMuni\_3cat)  }\OtherTok{=} \StringTok{"Confio en mi Municipalidad"}
\NormalTok{sjPlot}\SpecialCharTok{::}\FunctionTok{sjt.xtab}\NormalTok{(}\AttributeTok{var.row =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{intPol\_3cat, }
                 \AttributeTok{var.col =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{cMuni\_3cat, }
                 \AttributeTok{show.summary =}\NormalTok{ F, }
                 \AttributeTok{emph.total =}\NormalTok{ T, }
                 \AttributeTok{show.row.prc =}\NormalTok{ T, }
                 \AttributeTok{show.col.prc =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2000}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2000}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2000}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2000}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2000}}@{}}
\toprule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\multirow{2}{=}{\begin{minipage}[t]{\linewidth}\centering
A los politicos les\\
importa mi\\
opinion/intereses\strut
\end{minipage}} &
\multicolumn{3}{>{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.6000} + 4\tabcolsep}}{%
\begin{minipage}[t]{\linewidth}\centering
Confio en mi\\
Municipalidad\strut
\end{minipage}} & \multirow{2}{=}{Total} \\
& De acuerdo & En desacuerdo & \begin{minipage}[t]{\linewidth}\centering
Ni acuerdo ni\\
desacuerdo\strut
\end{minipage} \\
De acuerdo & \begin{minipage}[t]{\linewidth}\centering
{66}\\
{37.9~\%}\\
{23.7~\%}\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{24}\\
{13.8~\%}\\
{7.5~\%}\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{84}\\
{48.3~\%}\\
{8.6~\%}\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{174}\\
{100~\%}\\
{11.1~\%}\strut
\end{minipage} \\
En desacuerdo & \begin{minipage}[t]{\linewidth}\centering
{85}\\
{13.3~\%}\\
{30.5~\%}\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{200}\\
{31.3~\%}\\
{62.9~\%}\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{354}\\
{55.4~\%}\\
{36.2~\%}\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{639}\\
{100~\%}\\
{40.6~\%}\strut
\end{minipage} \\
\begin{minipage}[t]{\linewidth}\raggedright
Ni acuerdo ni\\
desacuerdo\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{128}\\
{16.8~\%}\\
{45.9~\%}\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{94}\\
{12.4~\%}\\
{29.6~\%}\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{539}\\
{70.8~\%}\\
{55.2~\%}\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{761}\\
{100~\%}\\
{48.3~\%}\strut
\end{minipage} \\
Total & \begin{minipage}[t]{\linewidth}\centering
{279}\\
{17.7~\%}\\
{100~\%}\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{318}\\
{20.2~\%}\\
{100~\%}\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{977}\\
{62.1~\%}\\
{100~\%}\strut
\end{minipage} & \begin{minipage}[t]{\linewidth}\centering
{1574}\\
{100~\%}\\
{100~\%}\strut
\end{minipage} \\
\end{longtable}

\section{Análisis Estadístico
Bivariado}\label{anuxe1lisis-estaduxedstico-bivariado}

En relación a las hipótesis planteadas en la introducción, se elaboraron
distintas pruebas estadísticas de correlación para poder rechazar sus
hipotesis nulas, y con eso, obtener indicios que apoyen las hipotesis
alternativas.

Para la hipotesis nula 1: No e\emph{xiste una relación entre la edad y
la confianza en el Estado}. Se implemento una prueba de correlación de
tipo \textbf{Pearson} debido a que las dos variables son de tipo
continuas. Frente a los resultados ( Coeficiente (\(r\)): -0.003, Valor
p = 0.8831) no se pudo rechazar la hipotesis nula, es decir, \textbf{no
se puede confirmar de que exista una correlación entre la edad y la
confianza en el Estado en Chile}. Según los criterios de Cohen(1988)
seria una correlación muy pequeña y negativa.

\begin{verbatim}

    Pearson's product-moment correlation

data:  data$edad and data$confEst
t = -0.14701, df = 1572, p-value = 0.8831
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.05310716  0.04570952
sample estimates:
         cor 
-0.003707872 
\end{verbatim}

Para la hipotesis nula 2: No \emph{Existe una relación entre la
percepción de los intereses de los políticos por la opinion pública y la
confianza en el Estado}. Se empleó el coeficiente de correlación de
Pearson debido a la naturaleza de las variables, en tanto la percepción
de interés político es ordinal y el nivel de confianza es numérico. El
coeficiente da cuenta de una relación positiva y grande, siguiendo los
criterios de \textbf{Cohen (1988)} (r = 0.512). \textbf{Es decir, es
probable que a medida que aumentan la confianza en las municipalidades,
las personas también aumentan sus niveles de confianza}. La relación es
estadísticamente significativa (p \textless{} 0.001), por ende es
posible rechazar H0 sobre no asociación entre variables, entregando
evidencia a favor de una relación entre ambas variables con un 99.9\% de
confianza.

\begin{verbatim}

    Pearson's product-moment correlation

data:  data$intPol and data$confEst
t = 21.491, df = 1572, p-value < 0.00000000000000022
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.4374214 0.5138420
sample estimates:
      cor 
0.4765314 
\end{verbatim}

Para la hipotesis nula 3: \emph{No existe una relación entre la
confianza en el Estado y la confianza en los organismos municipales}. Se
implemento una prueba de correlación de tipo \textbf{Pearson} debido a
que una de las variables es de tipo continua y la otra ordinal. Frente a
los resultados ( Coeficiente (\(r\)): 0,512, Valor p \textless{}
0.00005) se pudo rechazar la hipotesis nula, es decir, \textbf{existen
indicios de que exista una correlación entre la confianza en las
Municipalidades y la confianza en el Estado en Chile}. Según los
criterios de Cohen(1988) seria una correlación grande y positiva.

\begin{verbatim}

    Pearson's product-moment correlation

data:  data$cMuni and data$confEst
t = 23.658, df = 1572, p-value < 0.00000000000000022
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.4750163 0.5479361
sample estimates:
      cor 
0.5123993 
\end{verbatim}

Por ultimo, la hipotesis nula 4: \emph{No existe una relación entre la
percepción de los intereses de los políticos por la opinion pública y la
confianza en las municipalidades} . Se implemento una prueba de
correlación de tipo chi2, debido a que ambas variables son de tipo
ordinal. De acuerdo a un Chi crítico de 50,998 para un α=0.05, de
acuerdo a 36 grados de libertad y con un p \textless{} 0.00000000022, se
obtiene un Chi estimado de 245.79, \textbf{por lo que se puede rechazada
la hipótesis nula, lo que significa que existe una correlación
estadísticamente probable entre la percepción en el interés del gobierno
por la opinión pública y la confianza de los ciudadanos en las
municipalidades}. Según los criterios de \textbf{Cohen(1988)}, con una
\textbf{V de Cramer} de 0.16, se trata de una correlación pequeña.

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{cccc}



\ascline{0.5pt}{000000}{1-4}

\multicolumn{1}{>{}c}{\textcolor[HTML]{000000}{\fontsize{12}{24}\selectfont{\global\setmainfont{Times New Roman}{statistic}}}} & \multicolumn{1}{>{}c}{\textcolor[HTML]{000000}{\fontsize{12}{24}\selectfont{\global\setmainfont{Times New Roman}{\textit{p}}}}} & \multicolumn{1}{>{}c}{\textcolor[HTML]{000000}{\fontsize{12}{24}\selectfont{\global\setmainfont{Times New Roman}{parameter}}}} & \multicolumn{1}{>{}c}{\textcolor[HTML]{000000}{\fontsize{12}{24}\selectfont{\global\setmainfont{Times New Roman}{Method}}}} \\

\ascline{0.5pt}{000000}{1-4}\endfirsthead 

\ascline{0.5pt}{000000}{1-4}

\multicolumn{1}{>{}c}{\textcolor[HTML]{000000}{\fontsize{12}{24}\selectfont{\global\setmainfont{Times New Roman}{statistic}}}} & \multicolumn{1}{>{}c}{\textcolor[HTML]{000000}{\fontsize{12}{24}\selectfont{\global\setmainfont{Times New Roman}{\textit{p}}}}} & \multicolumn{1}{>{}c}{\textcolor[HTML]{000000}{\fontsize{12}{24}\selectfont{\global\setmainfont{Times New Roman}{parameter}}}} & \multicolumn{1}{>{}c}{\textcolor[HTML]{000000}{\fontsize{12}{24}\selectfont{\global\setmainfont{Times New Roman}{Method}}}} \\

\ascline{0.5pt}{000000}{1-4}\endhead



\multicolumn{1}{>{}l}{\textcolor[HTML]{000000}{\fontsize{12}{24}\selectfont{\global\setmainfont{Times New Roman}{245.79}}}} & \multicolumn{1}{>{}c}{\textcolor[HTML]{000000}{\fontsize{12}{24}\selectfont{\global\setmainfont{Times New Roman}{<\ .001***}}}} & \multicolumn{1}{>{}c}{\textcolor[HTML]{000000}{\fontsize{12}{24}\selectfont{\global\setmainfont{Times New Roman}{36}}}} & \multicolumn{1}{>{}c}{\textcolor[HTML]{000000}{\fontsize{12}{24}\selectfont{\global\setmainfont{Times New Roman}{Pearson's\ Chi-squared\ test}}}} \\

\ascline{0.5pt}{000000}{1-4}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\begin{verbatim}
X-squared 
0.1613272 
\end{verbatim}

\includegraphics{04-resultados_files/figure-pdf/unnamed-chunk-10-1.pdf}

\bookmarksetup{startatroot}

\chapter{Conclusiones}\label{conclusiones}

El análisis realizado a partir de los datos LAPOP 2023 permite concluir
que la confianza en el Estado chileno es, en promedio, baja (3.13 sobre
7). Contrario a lo que se suele estipular en el debate público sobre la
``brecha generacional'', este estudio \textbf{no encontró evidencia} de
que la edad sea un determinante de la confianza en el Estado
(\(p > 0.05\)); la desafección institucional afecta tanto a jóvenes como
a mayores por igual; En cuanto a la prueba de Chi2, se puede observar
una correlación estadísticamente significativa entre la percepción del
interés del gobierno por la opinión pública y la confianza de los
ciudadanos en las municipalidades.

Por el contrario, las variables actitudinales mostraron un fuerte poder
explicativo. Tanto el interés político como la confianza en las
municipalidades mostraron correlaciones significativas y positivas. El
hallazgo más relevante es la fuerte conexión entre la confianza local y
nacional (\(r = 0.51\)), lo que sugiere que fortalecer la gestión y
transparencia a nivel municipal podría ser una estrategia efectiva para
recomponer la confianza en la estructura estatal general. También que
mientras mayor interés hay por parte de los políticos mayor es el nivel
de confianza en el estado, lo que puede ser evidencia útil para la
promoción de políticas públicas orientadas a la participación y
vinculación del estado y la sociedad.

Como limitación, se señala que el diseño correlacional no permite
establecer causalidad. Futuras investigaciones deberían abordar modelos
de regresión múltiple para aislar el efecto de estas variables
controlando por nivel socioeconómico o victimización delictiva.

\bookmarksetup{startatroot}

\chapter{Conclusiones}\label{conclusiones-1}

El análisis realizado a partir de los datos LAPOP 2023 permite concluir
que la confianza en el Estado chileno es, en promedio, baja (3.13 sobre
7). Contrario a lo que se suele estipular en el debate público sobre la
``brecha generacional'', este estudio \textbf{no encontró evidencia} de
que la edad sea un determinante de la confianza en el Estado
(\(p > 0.05\)); la desafección institucional afecta tanto a jóvenes como
a mayores por igual; En cuanto a la prueba de Chi2, se puede observar
una correlación estadísticamente significativa entre la percepción del
interés del gobierno por la opinión pública y la confianza de los
ciudadanos en las municipalidades.

Por el contrario, las variables actitudinales mostraron un fuerte poder
explicativo. Tanto el interés político como la confianza en las
municipalidades mostraron correlaciones significativas y positivas. El
hallazgo más relevante es la fuerte conexión entre la confianza local y
nacional (\(r = 0.51\)), lo que sugiere que fortalecer la gestión y
transparencia a nivel municipal podría ser una estrategia efectiva para
recomponer la confianza en la estructura estatal general. También que
mientras mayor interés hay por parte de los políticos mayor es el nivel
de confianza en el estado, lo que puede ser evidencia útil para la
promoción de políticas públicas orientadas a la participación y
vinculación del estado y la sociedad.

Como limitación, se señala que el diseño correlacional no permite
establecer causalidad. Futuras investigaciones deberían abordar modelos
de regresión múltiple para aislar el efecto de estas variables
controlando por nivel socioeconómico o victimización delictiva.

\bookmarksetup{startatroot}

\chapter{Referencias}\label{referencias}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-xie2017bookdown}
Xie, Y. (2017). \emph{bookdown: Authoring Books and Technical Documents
with R Markdown}. Chapman; Hall/CRC.

\end{CSLReferences}

Biblioteca del Congreso Nacional de Chile. (s. f.). Portal de la
Biblioteca del Congreso Nacional de Chile. Portal de la Biblioteca del
Congreso Nacional de Chile. https://www.bcn.cl/portal/

CEP 2025. Estudio Nacional de opinión pública: Encuesta CEP 94. Centro
de Estudios Públicos. Disponible en:
https://www.cepchile.cl/encuesta/encuesta-cep-n-94-mayo-junio-2025-issp-orientaciones-laborales/
Cohen, J. (1988). Statistical Power Analysis for the Behavioral Sciences
(2nd ed.). Hillsdale, NJ: Erlbaum.

Cronbach, L. J. (1951). Coefficient alpha and the internal structure of
tests. Psychometrika, 16(3), 297-334.

Fuentes, C. (2011). MONTESQUIEU: TEORÍA DE LA DISTRIBUCIÓN SOCIAL DEL
PODER. Revista de Ciencia Política, 31(1), 47-61.
https://doi.org/10.4067/s0718-090x2011000100003

Fuentes, C. (2018). CONFIANZA EN EL GOBIERNO LOCAL Y CAPACIDADES
INSTITUCIONALES DE LOS MUNICIPIOS CHILENOS: UN ANÁLISIS MULTINIVEL.
Revista Iberoamericana de Estudios Municipales, (18), 91--120.
https://doi.org/10.32457/riem.vi18.32

Irarrázaval, I., Cruz, F. (2023). Confianza institucional en Chile: un
desafío para el desarrollo. Puntos de referencia, (682).
https://static.cepchile.cl/uploads/cepchile/2023/12/pder682\_-irarrazaval.pdf

Keefer, P., Scartascini, C. (2022). Confianza: la clave de la cohesión
social y el crecimiento en América Latina y el Caribe. Banco
Interamericano de Desarrollo.

LAPOP. (2023). AmericasBarometer 2023: Chile Technical Information.
Vanderbilt University.

OECD (2024). Los determinantes de la confianza en las instituciones
públicas de Chile. OECD Publishing.

Schaub, J. (2004). Sobre el concepto de Estado. Historia Contemporánea,
28. https://doi.org/10.1387/hc.5007

\cleardoublepage
\phantomsection
\addcontentsline{toc}{part}{Apéndices}
\appendix

\chapter{Instrumentos de
levantamiento}\label{instrumentos-de-levantamiento}

Incluye cuestionarios, guias de entrevista, etc.

\chapter{Tablas adicionales}\label{tablas-adicionales}

Tablas extendidas, tests de robustez, etc.


\backmatter

% --- Cuerpo del libro (capítulos) en arábigos ---
\mainmatter
\pagestyle{scrheadings}

% --- (Opcional) Estilo del índice general ---
% \addtocontents{toc}{\protect\thispagestyle{plain}}


\end{document}
