<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ángela Aguilar, Mariana Cuervo, Nayomi López, Cassidy Mansilla e Ingrid Pita">

<title>Diferencia en el tiempo libre</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="informe_correlacional_files/libs/clipboard/clipboard.min.js"></script>
<script src="informe_correlacional_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="informe_correlacional_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="informe_correlacional_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="informe_correlacional_files/libs/quarto-html/popper.min.js"></script>
<script src="informe_correlacional_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="informe_correlacional_files/libs/quarto-html/anchor.min.js"></script>
<link href="informe_correlacional_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="informe_correlacional_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="informe_correlacional_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="informe_correlacional_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="informe_correlacional_files/libs/bootstrap/bootstrap-81ff0694e0c8f6005801e8c2a6653441.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="informe_correlacional_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="informe_correlacional_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

<link href="informe_correlacional_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">

<script src="informe_correlacional_files/libs/tabwid-1.1.3/tabwid.js"></script>



</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Diferencia en el tiempo libre</h1>
<p class="subtitle lead">Estadística Correlacional 2025</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Ángela Aguilar, Mariana Cuervo, Nayomi López, Cassidy Mansilla e Ingrid Pita </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">23 de noviembre de 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introducción" class="level1">
<h1>Introducción</h1>
<p>El estudio que se realiza del uso del tiempo se ha convertido en un elemento importante para comprender sucesos que ocurren en la sociedad, como la desigualdad económica y de género presente en la vida cotidiana. En Chile, el análisis del tiempo libre constituye una herramienta clave para evaluar el bienestar, la calidad de vida y la distribución de las descargas que se realizan en distintos grupos sociales.</p>
<p>Según la Comisión Económica para América Latina y el Caribe (CEPAL), el tiempo es una dimensión estructural de desigualdad que revela brechas no notorias en los ingresos, pero sí son visibles cuando la persona organiza sus actividades diarias (CEPAL, 2004). Por eso, el estudio del tiempo libre, entendido como el conjunto de actividades no obligatorias que las personas realizan para descansar o desarrollar intereses personales (Gershuny y Fisher, 2014), se vuelve esencial para poder evaluar la calidad y estilo de vida.</p>
<p>La disponibilidad y el uso del tiempo no solo se relaciona con el bienestar, sino también con la inserción laboral, el nivel económico, las responsabilidades de cuidado y las desigualdades de género. Distintas investigaciones han demostrado que las mujeres suelen disponer de menos tiempo libre debido a la ocupación que tienen en la casa como tareas domésticas o de trabajos no remunerados que asumen dentro del hogar (Aguirre, 2005; Miranda, 2011). Esta desigualdad se puede reflejar en patrones estructurales presentes en toda América Latina. En esta línea, Arriagada (2011) plantea que la organización social del cuidado reproduce desigualdades que limitan la autonomía de ciertos grupos, como mujeres o personas de menores ingresos. De manera complementaria, estudios contemporáneos han demostrado que la distribución del tiempo libre está asociado tanto a factores estructurales como a condiciones laborales, trayendo educativas y características del entorno residencial (Mora, 2019).</p>
<p>Desde esta perspectiva, el presente trabajo busca analizar las desigualdades en el uso del tiempo libre en Chile, considerando variables sociodemográficas y laborales que pueden incidir en su distribución del tiempo. Se decidió construir un índice de tiempo libre a partir de variables relacionadas al uso del tiempo en base a ENUT, 2023 de esta manera el tiempo libre se aborda como la variable dependiente del estudio. El objetivo es indagar en si hay correlación entre el sexo, la discapacidad y la edad en el tiempo libre que las personas poseen. El informe se dividirá en la metodología usada, donde se explicará la base con la que se trabajó y las variables usadas para construir el índice para, posteriormente, entrar en la sección del análisis de los resultados, donde se analizarán gráficos y tablas de correlación para terminar concluyendo.</p>
<p>Se espera que la investigación pueda aportar en indicar si las variables sexo, discapacidad y edad están correlacionadas al tiempo libre que puedan poseer las personas. En este contexto, se formularon tres hipótesis:</p>
<p>-H1) Las mujeres no tienen tiempo libre a comparación a hombres.</p>
<p>-H2) Las personas mayores (65 años o más) y los menores (0 a 18 años) tienen tiempo libre, mientras que las personas adultas (19 años a 64 años) no lo tienen.</p>
<p>-H3) Las personas discapacitadas tienen tiempo libre, mientras que las personas que no poseen discapacidad no tienen tiempo libre.</p>
</section>
<section id="metodología" class="level1">
<h1>Metodología</h1>
<section id="datos" class="level2">
<h2 class="anchored" data-anchor-id="datos">Datos</h2>
<p>La metodología que conforma todo este informe se basa en los datos de la ENUT 2023, la cual es la Encuesta Nacional sobre el Uso del Tiempo. Este es un estudio estadístico que se encarga de registrar el cómo las personas emplean las horas del día en ciertas actividades, como lo son el trabajo remunerado, el trabajo no remunerado y el tiempo personal, entre otras situaciones. Esta encuesta es realizada por el Instituto Nacional de Estadística (INE), de modo que logra una visibilidad sobre las diversas formas de trabajo diario que las personas desempeñan, aún si dicho trabajo no es remunerado, y, a su vez, comprender cómo se distribuye el tiempo en la sociedad (INE, 2023). Teniendo en cuenta la ENUT como base de datos es que se determina que el tema central para el presente informe es “La diferencia en de tiempo libre de las personas”.</p>
<p>En base a este tema central es que se desglosó la variable dependiente, la cual sería “El tiempo libre”, debido a que así se se espera medir o identificar si existe algún cambio en si las personas tienen o no tiempo libre según las variables independientes que fueron escogidas. Las tres variables independientes escogidas fueron las siguientes: “Sexo”, “Edad” y “Discapacidad”. Esto debido a que son las que se espera que influyan en los resultados que se obtendrán en la variable dependiente, debido a que estas variables, las independientes, tienen a marcar una diferencia en múltiples fenónemos, por lo que se busca comprobar si las personas tienen tiempo libre o no se correlaciona a su sexo, edad o si tiene discapacidad.</p>
<p>Para poder medir si las personas tienen tiempo libre o no se creó un índice a partir de ciertas variables de la encuesta ENUT 2023, el cual será ocupado para realizar correlaciones y crear gráficos comparativos que sustenten o anulen las 3 hipótesis planteadas con anterioridad.</p>
</section>
<section id="variables" class="level2">
<h2 class="anchored" data-anchor-id="variables">Variables</h2>
<p>Para medición de si las personas tienen tiempo libre o no se creó un índice de tiempo libre, que se midió en cuatro dimensiones divididad de la siguiente forma:</p>
<ol type="1">
<li>Dimensión 1: Tiempo de trabajo (trabajo). Variable nominal Esta dimensión presenta sus resultados de forma dicotómica, de modo que se operacionaliza tal que: “Si los individuos poseen tiempo libre o no, según su tiempo de traslado más sus actividades laborales”.</li>
</ol>
<p>Esta dimensión contempla las variables:</p>
<p>-“tiempo de traslado” (t_tto_dt). De razón: Tiempo en día tipo en traslados por trabajo en la ocupación.</p>
<p>-“tiempo que trabaja” (t_to_dt). De razón: Tiempo en día tipo en actividades de trabajo en la ocupación</p>
<ol start="2" type="1">
<li>Dimensión 2: Tiempo de estudio (estudio). Variable nominal Esta dimensión presenta sus resultados de forma dicotómica, de modo que se operacionaliza tal que: “Si los individuos poseen tiempo libre o no, según su tiempo de traslado más sus actividades educativas”.</li>
</ol>
<p>Esta dimensión contempla las variables:</p>
<p>-“tiempo de traslado” (t_ted_dt). De razón: Tiempo de traslados en educación en día tipo.</p>
<p>-“tiempo en actividades de educación” (t_ed_dt). De razón: Tiempo en día tipo en actividades de educación.</p>
<ol start="3" type="1">
<li>Dimensión 3: Responsabilidades personales (resp_personal) Variable nominal. Esta dimensión presenta sus resultados de forma dicotómica, de modo que se operacionaliza tal que: “Si los individuos poseen tiempo libre o no, según sus actividades de cuidado a otras personas, de trabajo doméstico y de cuidado personal en un día tipo”.</li>
</ol>
<p>Esta dimensión contempla las variables:</p>
<p>-“tiempo de actividades de cuidado” (t_tcnr_ce_dt). De razón: Tiempo en día tipo en actividades de Cuidados esenciales a integrantes del hogar, tales como mudar o llevar al baño, bañar o asear, vestir o arreglar, dar de comer, ayudar a camina, desplazarse o cambiar de posición, ayudar a comunicarse con otras personas, contar juegos o jugar o la acostó o le hizo dormir.</p>
<p>-“tiempo de trabajo doméstico” (t_tdnr_dt). De razón: Tiempo en día tipo en Trabajo Doméstico No Remunerado para el Propio Hogar. Está a nivel de gran división de CAUTAL.</p>
<p>-“tiempo de cuidado personal” (t_cpaf_cp_dt). De razón: Tiempo en día tipo en actividades de Cuidado personal, tales como bañarse, vestirse o arreglarse o ir a una consulta o centro médico.</p>
<ol start="4" type="1">
<li>Dimensión 4: Tiempo de ocio (ocio). Variable ordinal. Esta dimensión presenta sus resultados de forma dicotómica, de modo que se operacionaliza tal que: “Si los individuos poseen tiempo libre o no para realizar actividades de uso de Medios de Comunicación Masiva y si poseen tiempo libre o no para realizar actividades de vida social y ocio en un día tipo”.</li>
</ol>
<p>Esta dimensión contempla las variables:</p>
<p>-“tiempo de uso de MCM” (t_mcm_dt). De razón: Tiempo en día tipo en uso de Medios de Comunicación Masiva en un día tipo.</p>
<p>-“tiempo de uso en vida social y ocio” (t_vsyo_dt). De razón: Tiempo en día tipo en actividades de Vida social y ocio. No contempla actividades deportivas y uso de medios de comunicación masiva.</p>
<p>Se utilizaron ciertas variables para la construcción de gráficos y correlaciones, las cuales son:</p>
<ol type="1">
<li><p>Sexo (Sexo). Variable nominal.</p></li>
<li><p>Edad (edad). Variable de razón: Edad en años cumplidos.</p></li>
<li><p>Edad recodificada (edad_recod). Variable ordinal: Edad separada en tramos etarios.</p></li>
<li><p>Discapacidad (pesd). Variable nominal: Identifica si una persona está en situación de discapacidad.</p></li>
</ol>
<p>Para cerrar, la variable del índice fue recodificada como “itl_recod” para volverla una variable dicotómica para indicar si se posee tiempo libre o no.</p>
<p>Respecto al trato de los NA, se optó por aplicar listwise a las variables que fueron creadas para las dimensiones, ya que esto permitía calcularlas por medio de una suma ponderada para la creación del índice.</p>
<div class="cell" data-tbl-cap="Estadísticas descriptivas por variable" data-tbl-label="tbl-estadisticas-variables">
<div class="cell-output-display">
<div id="pykmifqwzs" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>@import url("https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#pykmifqwzs table {
  font-family: 'Source Sans Pro', system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#pykmifqwzs thead, #pykmifqwzs tbody, #pykmifqwzs tfoot, #pykmifqwzs tr, #pykmifqwzs td, #pykmifqwzs th {
  border-style: none;
}

#pykmifqwzs p {
  margin: 0;
  padding: 0;
}

#pykmifqwzs .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 13px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: 85%;
  border-top-style: solid;
  border-top-width: 1.5px;
  border-top-color: #000000;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 1.5px;
  border-bottom-color: #000000;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#pykmifqwzs .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#pykmifqwzs .gt_title {
  color: #333333;
  font-size: 16px;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#pykmifqwzs .gt_subtitle {
  color: #333333;
  font-size: 11px;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#pykmifqwzs .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pykmifqwzs .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pykmifqwzs .gt_col_headings {
  border-top-style: solid;
  border-top-width: 1.2px;
  border-top-color: #000000;
  border-bottom-style: solid;
  border-bottom-width: 1.2px;
  border-bottom-color: #000000;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pykmifqwzs .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#pykmifqwzs .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#pykmifqwzs .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#pykmifqwzs .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#pykmifqwzs .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 1.2px;
  border-bottom-color: #000000;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#pykmifqwzs .gt_spanner_row {
  border-bottom-style: hidden;
}

#pykmifqwzs .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#pykmifqwzs .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#pykmifqwzs .gt_from_md > :first-child {
  margin-top: 0;
}

#pykmifqwzs .gt_from_md > :last-child {
  margin-bottom: 0;
}

#pykmifqwzs .gt_row {
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#pykmifqwzs .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#pykmifqwzs .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#pykmifqwzs .gt_row_group_first td {
  border-top-width: 2px;
}

#pykmifqwzs .gt_row_group_first th {
  border-top-width: 2px;
}

#pykmifqwzs .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pykmifqwzs .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#pykmifqwzs .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#pykmifqwzs .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pykmifqwzs .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pykmifqwzs .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#pykmifqwzs .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#pykmifqwzs .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#pykmifqwzs .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pykmifqwzs .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pykmifqwzs .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pykmifqwzs .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pykmifqwzs .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pykmifqwzs .gt_left {
  text-align: left;
}

#pykmifqwzs .gt_center {
  text-align: center;
}

#pykmifqwzs .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#pykmifqwzs .gt_font_normal {
  font-weight: normal;
}

#pykmifqwzs .gt_font_bold {
  font-weight: bold;
}

#pykmifqwzs .gt_font_italic {
  font-style: italic;
}

#pykmifqwzs .gt_super {
  font-size: 65%;
}

#pykmifqwzs .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#pykmifqwzs .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#pykmifqwzs .gt_indent_1 {
  text-indent: 5px;
}

#pykmifqwzs .gt_indent_2 {
  text-indent: 10px;
}

#pykmifqwzs .gt_indent_3 {
  text-indent: 15px;
}

#pykmifqwzs .gt_indent_4 {
  text-indent: 20px;
}

#pykmifqwzs .gt_indent_5 {
  text-indent: 25px;
}

#pykmifqwzs .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#pykmifqwzs div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<caption>Estadísticas descriptivas por variable</caption>
<thead>
<tr class="gt_heading header">
<td colspan="6" class="gt_heading gt_title gt_font_normal"><strong>Estadísticas descriptivas de dimensiones del índice de tiempo libre</strong></td>
</tr>
<tr class="gt_heading even">
<td colspan="6" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">Variables de uso del tiempo en base a ENUT, 2023</td>
</tr>
<tr class="gt_col_headings header">
<th id="Variable" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Variable</th>
<th id="N" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">N</th>
<th id="Media" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Media</th>
<th id="Desv_Est" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Desv. Est.</th>
<th id="Min" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Mín.</th>
<th id="Max" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Máx.</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">Tiempo dedicado al trabajo (trabajo)</td>
<td class="gt_row gt_center" headers="N">48020</td>
<td class="gt_row gt_center" headers="Media">0.416</td>
<td class="gt_row gt_center" headers="Desv_Est">0.739</td>
<td class="gt_row gt_center" headers="Min">0.000</td>
<td class="gt_row gt_center" headers="Max">2.000</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">Tiempo dedicado a la educación (estudio)</td>
<td class="gt_row gt_center" headers="N">48020</td>
<td class="gt_row gt_center" headers="Media">0.121</td>
<td class="gt_row gt_center" headers="Desv_Est">0.437</td>
<td class="gt_row gt_center" headers="Min">0.000</td>
<td class="gt_row gt_center" headers="Max">2.000</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">Tiempo dedicado a Responsabilidades personales (resp_personal)</td>
<td class="gt_row gt_center" headers="N">48020</td>
<td class="gt_row gt_center" headers="Media">0.554</td>
<td class="gt_row gt_center" headers="Desv_Est">0.723</td>
<td class="gt_row gt_center" headers="Min">0.000</td>
<td class="gt_row gt_center" headers="Max">3.000</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">Tiempo dedicado al ocio (ocio)</td>
<td class="gt_row gt_center" headers="N">48020</td>
<td class="gt_row gt_center" headers="Media">1.384</td>
<td class="gt_row gt_center" headers="Desv_Est">1.283</td>
<td class="gt_row gt_center" headers="Min">0.000</td>
<td class="gt_row gt_center" headers="Max">3.000</td>
</tr>
</tbody><tfoot>
<tr class="gt_sourcenotes odd">
<td colspan="6" class="gt_sourcenote">Notas: En base a ENUT, 2023</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<p>Cálculo de correlación del índice de tiempo libre (itl) mediante Alpha de Cronbach.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">&nbsp;</th>
<th data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">trabajo</th>
<th data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">estudio</th>
<th data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">resp_personal</th>
<th data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">ocio</th>
</tr>
<tr class="even">
<td style="font-style: italic">trabajo</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">estudio</td>
<td style="text-align: center; padding: 0.2cm;">-0.054<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">resp_personal</td>
<td style="text-align: center; padding: 0.2cm;">0.351<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.241<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">ocio</td>
<td style="text-align: center; padding: 0.2cm;">0.374<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.249<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.546<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td colspan="5" style="text-align: right; border-bottom: double black; border-top: 1px solid black; font-style: italic; font-size: 0.9em;">Computed correlation used pearson-method with listwise-deletion.</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6158207</code></pre>
</div>
</div>
</section>
<section id="métodos" class="level2">
<h2 class="anchored" data-anchor-id="métodos">Métodos</h2>
<p>Los métodos estadísticos para el cálculo de las dimension fue una suma ponderada para estadandarizar sus datos y evitar errores en el cálculo debido a los NA, puesto que por la naturaleza de las variables, no era posible calculas las dimensiones con un promedio ponderado. Tras esto, el cálculo del índice de tiempo libre como tal si fue realizado por medio de un promedio ponderado, ya que se buscaba que las cuatros dimensiones valieran 0.25, de modo que se estandarizaran.</p>
<p>Tras esto, se realiza un Alpha de Cronbach para ver la correlación del índice y sus dimensiones, dando 0.61, por lo que el índice está apto para su uso.</p>
<p>Posteriormente, se realizaron correlaciones entre el índice de tiempo libre (itl) y el sexo, entre itl y la edad y entre itl y discapacidad, utilizando Pearson.</p>
<p>También se realizó una prueba de CHI2 entre el índice de tiempo libre recodificado (itl_recod) y sexo y una tabla de contingencia entre itl_recod y edad_recod.</p>
</section>
</section>
<section id="análisis" class="level1">
<h1>Análisis</h1>
<section id="análisis-descriptivo" class="level2">
<h2 class="anchored" data-anchor-id="análisis-descriptivo">Análisis descriptivo</h2>
<section id="resumen-de-las-estadisticas-descriptivas-clave-de-la-variable-índice-de-tiempo-libre" class="level3">
<h3 class="anchored" data-anchor-id="resumen-de-las-estadisticas-descriptivas-clave-de-la-variable-índice-de-tiempo-libre">Resumen de las estadisticas descriptivas clave de la variable índice de tiempo libre</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Estadístico</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Media</td>
<td style="text-align: right;">0.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mediana</td>
<td style="text-align: right;">0.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Desviación estándar</td>
<td style="text-align: right;">0.58</td>
</tr>
<tr class="even">
<td style="text-align: left;">Varianza</td>
<td style="text-align: right;">0.34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mínimo</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Máximo</td>
<td style="text-align: right;">2.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rango</td>
<td style="text-align: right;">2.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">Coef. Variación</td>
<td style="text-align: right;">0.94</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N válidos</td>
<td style="text-align: right;">48020.00</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La media del ITL es de 0,62 mientras que la mediana alcanza el 0,75, lo que propone que la distribución posee asimetría negativa, pues la mitad de las personas tienen un nivel de tiempo libre igual o mayor a 0,75, pero el promedio baja dado a la existencia de los valores bajos. Mientras tanto su desviación estándar de 0,58 indica una variabilidad moderada con respecto a la disponibilidad de tiempo libre.</p>
</section>
<section id="frecuencia-de-la-variable-itl" class="level3">
<h3 class="anchored" data-anchor-id="frecuencia-de-la-variable-itl">Frecuencia de la variable ITL</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=48020 valid N=48020 mean=0.62 sd=0.58

Value |     N | Raw % | Valid % | Cum. %
----------------------------------------
 0.00 | 19570 | 40.75 |   40.75 |  40.75
 0.25 |   456 |  0.95 |    0.95 |  41.70
 0.50 |  2636 |  5.49 |    5.49 |  47.19
 0.75 |  6586 | 13.72 |   13.72 |  60.91
 1.00 |  7509 | 15.64 |   15.64 |  76.55
 1.25 |  6061 | 12.62 |   12.62 |  89.17
 1.50 |  3608 |  7.51 |    7.51 |  96.68
 1.75 |  1382 |  2.88 |    2.88 |  99.56
 2.00 |   201 |  0.42 |    0.42 |  99.98
 2.25 |    11 |  0.02 |    0.02 | 100.00
 &lt;NA&gt; |     0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>La distribución del ITL es continua y se puede observar una mayor concentración de casos en valores bajos, especialmente entre 0 y 1, lo cual significa que gran parte de la población dispone de niveles reducidos de tiempo libre.</p>
</section>
<section id="histograma-de-la-distribución-del-índice-de-tiempo-libre" class="level3">
<h3 class="anchored" data-anchor-id="histograma-de-la-distribución-del-índice-de-tiempo-libre">Histograma de la distribución del Índice de tiempo libre</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_correlacional_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los resultados muestran que hay una alta concentración en valores muy bajos del índice, específicamente entre el 0.0 y 0.3, demostrando una alta frecuencia logrando superar así los 5000 casos. A partir de esto, la frecuencia disminuye progresivamente, aunque con pequeños progresos entre 0.8 y 1.5, hasta llegar a los valores más alejados de los niveles más altos. Esto presenta que el tiempo libre está distribuido de manera desigual, en donde una proporción significativa de la población dispone de niveles muy limitados, mientras que un grupo específico alcanza niveles mayores.</p>
</section>
<section id="frecuencia-de-la-variable-sexo" class="level3">
<h3 class="anchored" data-anchor-id="frecuencia-de-la-variable-sexo">Frecuencia de la variable sexo</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Sexo (x) &lt;numeric&gt; 
# total N=48020 valid N=48020 mean=1.53 sd=0.50

Value |         Label |     N | Raw % | Valid % | Cum. %
--------------------------------------------------------
    1 |        Hombre | 22609 | 47.08 |   47.08 |  47.08
    2 |         Mujer | 25411 | 52.92 |   52.92 | 100.00
   96 | Valor Perdido |     0 |  0.00 |    0.00 | 100.00
 &lt;NA&gt; |          &lt;NA&gt; |     0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>La distribución por sexo muestra un equilibrio razonable entre hombres (47.08 %) y mujeres (52.92 %), lo que implica que la muestra es relativamente balanceada. Este equilibrio es relevante dado que permite comparar el tiempo libre entre ambos grupos sin que exista un sesgo fuerte en la composición de la muestra. La presencia mínima de valores perdidos indica buena calidad en los resultados.</p>
</section>
<section id="índice-de-confianza" class="level3">
<h3 class="anchored" data-anchor-id="índice-de-confianza">Índice de confianza</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Estadístico</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Media ITL</td>
<td style="text-align: right;">0.6187838</td>
</tr>
<tr class="even">
<td style="text-align: left;">Límite inferior IC 95%</td>
<td style="text-align: right;">0.6135895</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Límite superior IC 95%</td>
<td style="text-align: right;">0.6239782</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Con respecto a los intervalos, la proximidad que hay entre esto se explica debido a un tamaño muestral grande, lo cual entrega una alta precisión a la estimación de la media. Dado que el IC no incluye valores altos, en este caso sobre 1,0, se confirma que, en promedio, la población presenta niveles relativamente moderados o bajos de tiempo libre.</p>
</section>
<section id="cálculo-de-alpha-de-crobach-aplicado-al-itl" class="level3">
<h3 class="anchored" data-anchor-id="cálculo-de-alpha-de-crobach-aplicado-al-itl">Cálculo de Alpha de Crobach aplicado al ITL</h3>
<div class="cell">
<pre><code>## [1] 0.6158207</code></pre>
</div>
<p>El coeficiente obtenido indica que el conjunto de indicadores y dimensiones ocupados para poder realizar el índice presenta una consistencia interna alta. Lo cual significa que los elementos que componen este índice está midiendo un mismo concepto de manera coherente, en otras palabras es suficiente sólida para que el índice sea empleado como variable dependiente para los resultados posteriores.</p>
</section>
</section>
<section id="análisis-estadístico-bivariado" class="level2">
<h2 class="anchored" data-anchor-id="análisis-estadístico-bivariado">Análisis estadístico bivariado</h2>
<section id="matríz-de-correlaciones" class="level3">
<h3 class="anchored" data-anchor-id="matríz-de-correlaciones">Matríz de correlaciones</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">&nbsp;</th>
<th data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">trabajo</th>
<th data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">estudio</th>
<th data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">resp_personal</th>
<th data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">ocio</th>
</tr>
<tr class="even">
<td style="font-style: italic">trabajo</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">estudio</td>
<td style="text-align: center; padding: 0.2cm;">-0.054<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">resp_personal</td>
<td style="text-align: center; padding: 0.2cm;">0.351<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.241<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">ocio</td>
<td style="text-align: center; padding: 0.2cm;">0.374<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.249<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.546<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td colspan="5" style="text-align: right; border-bottom: double black; border-top: 1px solid black; font-style: italic; font-size: 0.9em;">Computed correlation used pearson-method with listwise-deletion.</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Las correlaciones presentadas son estadísticamente significativas (p &lt; .001) lo cual indica relaciones consistentes por disponibilidad horaria. Por un lado la relación entre trabajo y estudio es relativamente baja y negativa (-0.054) lo cual indica que dedicar más tiempo al trabajo apenas se asocia con reducir el tiempo destinado al estudio. Por otro lado, las responsabilidades personales muestran una correlación moderada con el trabajo (0.35) y una correlación también moderada con estudio (0.24), lo que indica que quienes estudian o trabajan suelen asumir simultáneamente más tareas personales. Por último el patrón que más resalta está entre responsabilidades personales y ocio (0.55), relación que indica que estas dos dimensiones se mueven de manera conjunta dentro del índice</p>
</section>
<section id="correlación-de-pearson-entre-itl-y-sexo" class="level3">
<h3 class="anchored" data-anchor-id="correlación-de-pearson-entre-itl-y-sexo">Correlación de Pearson entre ITL y sexo</h3>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimación</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Método</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Alternativa</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">95% IC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">7.29</td>
<td style="text-align: left;">&lt; 0.001***</td>
<td style="text-align: right;">48018</td>
<td style="text-align: left;">Pearson's product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
<td style="text-align: left;">[0.02, 0.04]</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>El analisis de Pearson entre ITL y sexo muestra una correlacion menor (0.03) aunque estadisticamente significativa gracias al gran tamaño de la muestra. Dado de que el valor de p es menor a 0.001, la magnitud del efecto es prácticamente nula lo que implica que el sexo explica una fracción ínfima de las diferencias en el tiempo libre.</p>
</section>
<section id="correlación-de-pearson-entre-itl-y-edad" class="level3">
<h3 class="anchored" data-anchor-id="correlación-de-pearson-entre-itl-y-edad">Correlación de Pearson entre ITL y edad:</h3>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimación</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Método</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Alternativa</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">95% IC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">48.26</td>
<td style="text-align: left;">&lt; 0.001***</td>
<td style="text-align: right;">48018</td>
<td style="text-align: left;">Pearson's product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
<td style="text-align: left;">[0.21, 0.22]</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>La correlación entre ITL y edad tiene un valor aproximado de 0.215, lo cual indica una relación positiva pero a su vez débil. Es estadísticamente significativo al tener un p menor a 0,001. Esto significa que la edad de una persona explica en menor medida si posee tiempo libre o no.</p>
</section>
<section id="correlación-de-pearson-entre-itl-y-discapacidad" class="level3">
<h3 class="anchored" data-anchor-id="correlación-de-pearson-entre-itl-y-discapacidad">Correlación de Pearson entre ITL y discapacidad</h3>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimación</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Método</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Alternativa</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">95% IC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">-13.19</td>
<td style="text-align: left;">&lt; 0.001***</td>
<td style="text-align: right;">48018</td>
<td style="text-align: left;">Pearson's product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
<td style="text-align: left;">[-0.07, -0.05]</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>La correlación de Pearson entre ITL y discapacidad es de -0.06, un valor bajo que indica una relación negativa y débil. Este resultado contradice la hipótesis planteada (H3) dado que se esperaba que las personas con discapacidad tengan más tiempo libre, pero obteniendo los resultados se muestra lo contrario, aunque de igual manera su efecto es el mínimo.</p>
</section>
<section id="frecuencia-por-sexo-e-itl" class="level3">
<h3 class="anchored" data-anchor-id="frecuencia-por-sexo-e-itl">Frecuencia por sexo e itl</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<tbody>
<tr class="odd">
<th rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">Sexo</th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">itl_recod</th>
<th rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid; background-color: #f8f8f8;">Total</th>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">0</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Hombre</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">13557</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">9052</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">22609</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Mujer</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">15691</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">9720</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">25411</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">29248</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">18772</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">48020</span></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La tabla muestra que, al recodificar el ITL es una variable dicotómica (0 = bajo tiempo libre; 1 = alto tiempo libre), los porcentajes difieren entre hombres y mujeres. Por un lado el de los hombres con 13557, presentando un bajo ITL y un 9053 representando un alto ITL; por el lado de las mujeres con un 15691 en bajo ITL y un 9720 con un alto ITL. A primera vista ambos sexos tienen mayor presencia en la categoría de poco tiempo libre, pero las mujeres aparecen ligeramente sobre representadas en esta categoría.</p>
</section>
<section id="tabla-de-contingencia-entre-itl-y-sexo" class="level3">
<h3 class="anchored" data-anchor-id="tabla-de-contingencia-entre-itl-y-sexo">Tabla de contingencia entre ITL y sexo</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<th rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">Sexo</th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">itl_recod</th>
<th rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid; background-color: #f8f8f8;">Total</th>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">0</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Hombre</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">13557</span><br>
<span style="color:#333399;">60&nbsp;%</span><br>
<span style="color:#339933;">46.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">9052</span><br>
<span style="color:#333399;">40&nbsp;%</span><br>
<span style="color:#339933;">48.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">22609</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">47.1&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Mujer</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">15691</span><br>
<span style="color:#333399;">61.7&nbsp;%</span><br>
<span style="color:#339933;">53.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">9720</span><br>
<span style="color:#333399;">38.3&nbsp;%</span><br>
<span style="color:#339933;">51.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">25411</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">52.9&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">29248</span><br>
<span style="color:#333399;">60.9&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">18772</span><br>
<span style="color:#333399;">39.1&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">48020</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La tabla permite observar una asociación débil pero visible, las mujeres presentan mayor proporción de tiempo libre reducido respecto a los hombres. Este análisis refuerza la validez de la hipótesis H1 (“Las mujeres tienen menos tiempo libre que los hombres”), dado que incluso con la recodificación del ITL, la tendencia se mantiene</p>
</section>
<section id="prueba-chi2-entre-itl-y-sexo" class="level3">
<h3 class="anchored" data-anchor-id="prueba-chi2-entre-itl-y-sexo">Prueba CHI2 entre ITL y sexo</h3>
<div class="cell">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-a9a56516{table-layout:auto;}.cl-a99f27dc{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a99f27e6{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a9a1baec{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-a9a1baed{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-a9a1d400{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a9a1d401{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a9a1d402{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-a9a56516"><thead><tr style="overflow-wrap:break-word;"><th class="cl-a9a1d400"><p class="cl-a9a1baec"><span class="cl-a99f27dc">statistic</span></p></th><th class="cl-a9a1d400"><p class="cl-a9a1baec"><span class="cl-a99f27e6">p</span></p></th><th class="cl-a9a1d400"><p class="cl-a9a1baec"><span class="cl-a99f27dc">parameter</span></p></th><th class="cl-a9a1d400"><p class="cl-a9a1baec"><span class="cl-a99f27dc">Method</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-a9a1d401"><p class="cl-a9a1baed"><span class="cl-a99f27dc">15.95</span></p></td><td class="cl-a9a1d402"><p class="cl-a9a1baec"><span class="cl-a99f27dc">&lt; .001***</span></p></td><td class="cl-a9a1d402"><p class="cl-a9a1baec"><span class="cl-a99f27dc">1</span></p></td><td class="cl-a9a1d402"><p class="cl-a9a1baec"><span class="cl-a99f27dc">Pearson's Chi-squared test with Yates' continuity correction</span></p></td></tr></tbody></table></div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_correlacional_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La prueba chi-cuadrado calcula un valor de 15.953, con 1 grado de libertad y un p-value &lt; 0.001, el cual indica que existe una asociación estadísticamente significativa entre el sexo y el nivel de tiempo libre recodificado (no tener tiempo libre o si tenerlo). Esto significa que la distribución del tiempo libre no es igual entre hombres y mujeres y que el sexo tiene una relación con si se dispone o no de tiempo libre.</p>
</section>
<section id="cálculo-del-coeficiente-phi" class="level3">
<h3 class="anchored" data-anchor-id="cálculo-del-coeficiente-phi">Cálculo del Coeficiente Phi</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01826965</code></pre>
</div>
</div>
<p>El coeficiente Phi reportado, aprox. 0.02, refleja la magnitud del efecto, y este es muy pequeño. Esto significa que aunque la relación entre sexo e ITL recodificado es estadísticamente significativa, el tamaño del efecto es débil. Este resultado es coherente con investigaciones previas, las desigualdades de género existen, pero no siempre muestran efectos grandes en mediciones agregadas, especialmente cuando el itl resume múltiples actividades diarias.</p>
</section>
<section id="gráfico-entre-itl-y-sexo" class="level3">
<h3 class="anchored" data-anchor-id="gráfico-entre-itl-y-sexo">Gráfico entre ITL y sexo</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_correlacional_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La diferencia más notoria es que las mujeres presentan un número mayor en la categoría “No tiene tiempo libre”, mientras que la diferencia en “Tiene tiempo libre” es menor, aunque igualmente presente. Esta visualización respalda la hipótesis H1 y demuestra que las mujeres están más concentradas en niveles reducidos de tiempo libre. Este gráfico facilita observar la desigualdad de género en la distribución del tiempo libre, reforzando los resultados estadísticos.</p>
</section>
<section id="tabla-de-contingencia-entre-itl-y-tramos-de-edad" class="level3">
<h3 class="anchored" data-anchor-id="tabla-de-contingencia-entre-itl-y-tramos-de-edad">Tabla de contingencia entre ITL y tramos de edad</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<tbody>
<tr class="odd">
<th rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">edad_recod</th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">itl_recod</th>
<th rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid; background-color: #f8f8f8;">Total</th>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">0</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">0-18 años</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">9049</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">2331</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">11380</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">19-29 años</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4072</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">3579</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">7651</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">30-49 años</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">6381</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">6407</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">12788</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">50-64 años</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4874</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4153</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">9027</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">65+ años</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4872</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">2302</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">7174</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">29248</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">18772</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">48020</span></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La tabla muestra cómo se distribuye el tiempo libre (no tiene tiempo libre y tiene tiempo libre) según los distintos tramos de edad. En otros términos más generales, se observa que todos los grupos presentan mayor proporción en la categoría de no tiene tiempo libre, lo que confirma una tendencia a no tener disponibilidad de tiempo libre.</p>
</section>
<section id="tabla-de-contingencia-entre-itl-y-tramos-de-edad-en-porcentajes" class="level3">
<h3 class="anchored" data-anchor-id="tabla-de-contingencia-entre-itl-y-tramos-de-edad-en-porcentajes">Tabla de contingencia entre ITL y tramos de edad en porcentajes</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<th rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">edad_recod</th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">itl_recod</th>
<th rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid; background-color: #f8f8f8;">Total</th>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">0</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">0-18 años</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">9049</span><br>
<span style="color:#333399;">79.5&nbsp;%</span><br>
<span style="color:#339933;">30.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">2331</span><br>
<span style="color:#333399;">20.5&nbsp;%</span><br>
<span style="color:#339933;">12.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">11380</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">23.7&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">19-29 años</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4072</span><br>
<span style="color:#333399;">53.2&nbsp;%</span><br>
<span style="color:#339933;">13.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">3579</span><br>
<span style="color:#333399;">46.8&nbsp;%</span><br>
<span style="color:#339933;">19.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">7651</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">15.9&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">30-49 años</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">6381</span><br>
<span style="color:#333399;">49.9&nbsp;%</span><br>
<span style="color:#339933;">21.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">6407</span><br>
<span style="color:#333399;">50.1&nbsp;%</span><br>
<span style="color:#339933;">34.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">12788</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.6&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">50-64 años</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4874</span><br>
<span style="color:#333399;">54&nbsp;%</span><br>
<span style="color:#339933;">16.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4153</span><br>
<span style="color:#333399;">46&nbsp;%</span><br>
<span style="color:#339933;">22.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">9027</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">18.8&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">65+ años</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">4872</span><br>
<span style="color:#333399;">67.9&nbsp;%</span><br>
<span style="color:#339933;">16.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">2302</span><br>
<span style="color:#333399;">32.1&nbsp;%</span><br>
<span style="color:#339933;">12.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">7174</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">14.9&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">29248</span><br>
<span style="color:#333399;">60.9&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">18772</span><br>
<span style="color:#333399;">39.1&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">48020</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La siguiente tabla permite hacer una mejor interpretación comparativa, por ejemplo en el grupo de 0–18 años hay un 79.5 % que presenta bajo tiempo libre y solo el 20.5 % declara alto ITL. Diferente al grupo 30–49 años que tiene una distribución casi pareja: 49.9 % bajo ITL, 50.1 % alto ITL. Este tramo presenta el mayor acceso relativo al tiempo libre, lo cual puede estar vinculado a estabilidad laboral y mejor organización del tiempo. En conjunto, estos porcentajes no apoyan completamente la hipótesis H2, porque los grupos extremos (menores y mayores) no son los que poseen más tiempo libre. De hecho, quienes reportan mejores niveles de tiempo libre son las personas de 30–49 años.</p>
</section>
<section id="prueba-de-chi2-entre-itl-y-edad" class="level3">
<h3 class="anchored" data-anchor-id="prueba-de-chi2-entre-itl-y-edad">Prueba de CHI2 entre ITL y edad</h3>
<div class="cell">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-aa99874a{table-layout:auto;}.cl-aa938afc{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-aa938b06{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-aa95eb58{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-aa95eb62{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-aa960336{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-aa960340{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-aa960341{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-aa99874a"><thead><tr style="overflow-wrap:break-word;"><th class="cl-aa960336"><p class="cl-aa95eb58"><span class="cl-aa938afc">statistic</span></p></th><th class="cl-aa960336"><p class="cl-aa95eb58"><span class="cl-aa938b06">p</span></p></th><th class="cl-aa960336"><p class="cl-aa95eb58"><span class="cl-aa938afc">parameter</span></p></th><th class="cl-aa960336"><p class="cl-aa95eb58"><span class="cl-aa938afc">Method</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-aa960340"><p class="cl-aa95eb62"><span class="cl-aa938afc">2,824.96</span></p></td><td class="cl-aa960341"><p class="cl-aa95eb58"><span class="cl-aa938afc">&lt; .001***</span></p></td><td class="cl-aa960341"><p class="cl-aa95eb58"><span class="cl-aa938afc">4</span></p></td><td class="cl-aa960341"><p class="cl-aa95eb58"><span class="cl-aa938afc">Pearson's Chi-squared test</span></p></td></tr></tbody></table></div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_correlacional_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico ilustra la comparación entre la distribución teórica del estadístico Chi-cuadrado con 4 grados de libertad y el valor observado en la prueba aplicada a las variables ITL y edad. Siendo el resultado de la prueba Chi2 = 2,824.96, se sitúa muy por encima del valor crítico para α = 0.05 (9.488), demostrando que existe correlación entre la edad y el tiempo libre.</p>
</section>
<section id="gráfico-de-itl-y-edad" class="level3">
<h3 class="anchored" data-anchor-id="gráfico-de-itl-y-edad">Gráfico de ITL y edad</h3>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="informe_correlacional_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>ITL según tramos etarios ENUT 2023</figcaption>
</figure>
</div>
</div>
</div>
<p>El siguiente gráfico solidifica las tendencias presentadas anteriormente. Comenzando por el tramo 0–18 años concentra el valor más alto en “No tiene tiempo libre”, lo que coincide podría coincidir con la carga escolar. Por otro lado los grupos 30–49 y 19–29 años son los que muestran una mayor presencia en la categoría “Tiene tiempo libre”, pero por una diferencia de aproximadamente 100 personas. Mientras tanto el grupo 65+ años vuelve a destacarse por tener mayor frecuencia en no tener tiempo libre, lo cual es contrario a lo esperado teóricamente.</p>
<p>Con el siguiente gráfico se puede confirmar que la distribución del tiempo libre no sigue un patrón lineal respecto a la edad, y los adultos de mediana edad parecen estar en las mejores condiciones para disponer de tiempo libre.</p>
</section>
</section>
<section id="discusión-de-resultados" class="level2">
<h2 class="anchored" data-anchor-id="discusión-de-resultados">Discusión de resultados</h2>
<p>Respecto a los resultados, es posible corroborar la hipótesis 1, ya que los resultados indican que las mujeres poseen menos tiempo libre que los hombres; sin embargo, la correlaciones indican que el factor sexo no es un factor que esté muy correlacionado a si se dispone de tiempo libre o no.</p>
<p>Es posible falsear la hipótesis 2, ya que los resultados indican que las personas entre 0-18 años y 65 años o más tienden a no poseer tiempo libre y gracias a los resultados se puede indicar que hay una correlación débil entre la edad y el tiempo libre.</p>
<p>La hipótesis 3 se falsea, ya que las personas con discapacidad tienden a no tener tiempo libre; sin embargo, la correlación entre dispacidad y tiempo libre no es muy fuerte.</p>
<p>Para cerrar, aun se necesitan más datos e identificar distintas variables que pudiesen estar correlacionadas sobre la disposición de tiempo libre.</p>
</section>
</section>
<section id="conclusión" class="level1">
<h1>Conclusión</h1>
<p>Para concluir podemos decir que se puede apreciar que el tiempo libre se distribuye de manera desigual, debido a que se presentan mayormente una alta concentración en los valores bajos del índice. La primera hipótesis se confirma, mientras que la segunda hipótesis fue desmentida gracias a los datos obtenidos y, por último, la tercera hipótesis referente a la discapacidad es que podemos denotar una correlación débil y negativa que termina por desmentir la hipótesis planteada.</p>
<p>Respecto a las limitaciones que se pueden observar en la investigación, se puede mencionar que, si bien las correlaciones presentadas fueron estadísticamente significativas gracias al gran tamaño muestral, hubieron variables con una magnitud de efecto fue muy pequeño, por lo que esto limitaría el indicar si la variable posee o no un impacto en relación al tiempo libre. Posiblemente el hecho de haber construido un índice a partir de dimensiones con pocos indicadores sea una explicación de por qué los resultados de las correlaciones fueron menores a los esperados.</p>
<p>Como sugerencias para futuros análisis, se propone el tener en cuenta que la creación de un índice de tiempo libre a partir de dimensiones que posean indicadores específicos en días tipo, puesto que sintetiza de buena manera si las personas poseen tiempo libre o no, pero que este sea hecho con la implementación de un mayor número de indicadores correlacionados en cada dimensión para que este sea aún más efectivo. La creación de un índice de tiempo libre puede ayudar a futuros estudios a entender las desigualdades que pueden llegar a darse en la población y comprender la razón detrás de ello, por lo que se propone que la creación de un índice de tiempo libre se tenga presente para futuras investigadores que busquen identificar desigualdades.</p>
</section>
<section id="bibliografía" class="level1">
<h1>Bibliografía</h1>
<p>Arriagada, I. (2011). La organización social del cuidado: desafíos para la autonomía de las mujeres en América Latina. CEPAL.</p>
<p>Aguirre, R. (2005). Los cuidados y las mujeres: indicadores para un análisis de uso del tiempo. CEPAL.</p>
<p>Gershuny, J., y Fisher, K. (2014). Time Use Research: An Introduction. Oxford University Press.</p>
<p>Mora, C. 2019. Interseccionalidad y fronteras sociales: género y clase social en el mercado laboral chileno. Estudios Públicos. 156 (dic. 2019).</p>
<p>Naciones Unidas, Comisión Económica para América Latina y el Caribe (CEPAL). (2004). Panorama social de América Latina 2002-2003. Santiago de Chile: Naciones Unidas.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>