<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Josefa Isler Mayen, Nuni Sanhueza Ibarra y Antonia Silva Guerrero">

<title>Trabajo Estadística Correlacional</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="achetemelele cor_files/libs/clipboard/clipboard.min.js"></script>
<script src="achetemelele cor_files/libs/quarto-html/quarto.js"></script>
<script src="achetemelele cor_files/libs/quarto-html/popper.min.js"></script>
<script src="achetemelele cor_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="achetemelele cor_files/libs/quarto-html/anchor.min.js"></script>
<link href="achetemelele cor_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="achetemelele cor_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="achetemelele cor_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="achetemelele cor_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="achetemelele cor_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="achetemelele cor_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="achetemelele cor_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo Estadística Correlacional</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Josefa Isler Mayen, Nuni Sanhueza Ibarra y Antonia Silva Guerrero </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Cargar librerías</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) <span class="fu">install.packages</span>(<span class="st">"pacman"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: pacman</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(ggplot2, dplyr, kableExtra, sjmisc, knitr, haven, broom, tidyverse, summary, vcd, sjPlot, flextable, corrplot, sjstats, gginference, gtools)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Installing package into 'C:/Users/APSG/AppData/Local/R/win-library/4.5'
(as 'lib' is unspecified)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'summary' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.5:
  no fue posible abrir la URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.5/PACKAGES'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: 'BiocManager' not available.  Could not check Bioconductor.

Please use `install.packages('BiocManager')` and then retry.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in p_install(package, character.only = TRUE, ...):</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in library(package, lib.loc = lib.loc, character.only = TRUE,
logical.return = TRUE, : no hay paquete llamado 'summary'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in pacman::p_load(ggplot2, dplyr, kableExtra, sjmisc, knitr, haven, : Failed to install/load:
summary</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Cargar datos</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"Base de datos EBS 2023.RData"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> EBS_2023_vp</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Limpieza General de Datos</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(a1, sg01, l11, os1_recat, f1) <span class="sc">%&gt;%</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), haven<span class="sc">::</span>zap_labels)) <span class="sc">%&gt;%</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), as.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">ifelse</span>(. <span class="sc">%in%</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">88</span>, <span class="sc">-</span><span class="dv">99</span>), <span class="cn">NA</span>, .)))</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. CREACIÓN DE ETIQUETAS (Esto arregla tus tablas)</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Sexo</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>df_clean<span class="sc">$</span>sexo_label <span class="ot">&lt;-</span> <span class="fu">factor</span>(df_clean<span class="sc">$</span>sg01, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Hombre"</span>, <span class="st">"Mujer"</span>))</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Confianza (Arregla el error "Unknown column")</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>df_clean<span class="sc">$</span>confianza_label <span class="ot">&lt;-</span> <span class="fu">factor</span>(df_clean<span class="sc">$</span>f1, </span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, </span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Nada"</span>, <span class="st">"Poco"</span>, <span class="st">"Algo"</span>, <span class="st">"Bastante"</span>, <span class="st">"Mucho"</span>))</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Ocupación (Agrega los nombres del PDF a los números 1-9)</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>df_clean<span class="sc">$</span>ocupacion_label <span class="ot">&lt;-</span> <span class="fu">factor</span>(df_clean<span class="sc">$</span>l11, </span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>,</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Patrón/Empleador"</span>, <span class="st">"Cuenta Propia"</span>, <span class="st">"Emp. Público"</span>, </span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>                                              <span class="st">"Emp. Pública"</span>, <span class="st">"Emp. Privado"</span>, <span class="st">"Serv. Dom. Adentro"</span>, </span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>                                              <span class="st">"Serv. Dom. Afuera"</span>, <span class="st">"FF.AA."</span>, <span class="st">"Familiar no rem."</span>))</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Orientación Sexual (Basado en tu output: 3 es la mayoría, así que es Heterosexual)</span></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustamos 1 y 2 como minorías según el orden usual</span></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>df_clean<span class="sc">$</span>orientacion_label <span class="ot">&lt;-</span> <span class="fu">factor</span>(df_clean<span class="sc">$</span>os1_recat, </span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), </span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Gay/Lesbiana"</span>, <span class="st">"Bisexual/Otro"</span>, <span class="st">"Heterosexual"</span>))</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Recodificación numérica para correlaciones (sin cambios)</span></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>df_clean<span class="sc">$</span>sexo_dummy <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df_clean<span class="sc">$</span>sg01 <span class="sc">==</span> <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introducción" class="level1">
<h1>1. Introducción</h1>
<p>La satisfacción subjetiva de la vida es un indicador fundamental para comprender cómo los individuos perciben su bienestar en un contexto de transformaciones sociales aceleradas. La importancia de su medición surge de la necesidad de monitorear el bienestar en un escenario caracterizado por la “atomización de la sociedad, las crisis económicas, democráticas y el aumento de la individualización” (Bauman, 2000).</p>
<p>Informes recientes de la Organización Mundial de la Salud alertan que “en la actualidad, casi una de cada seis personas a escala mundial afirma sentirse sola” (OMS, 2025), lo que sugiere una crisis de bienestar vinculada a la erosión del tejido social. El problema de investigación aborda qué factores estructurales y relacionales afectan en mayor medida a la satisfacción vital en la sociedad chilena actual.</p>
<p>Para este estudio, definimos la <strong>satisfacción con la vida</strong> como “una evaluación cognitiva de la propia vida desde una perspectiva global” (Diener et al., 1985). Esta definición se diferencia de los estados afectivos momentáneos, centrándose en un juicio reflexivo sobre la propia existencia, coherente con la teoría homeostática del bienestar que postula mecanismos internos de regulación psicológica (Arita, 2005). Asimismo, analizaremos el rol del <strong>capital social</strong>, entendido a través de la confianza interpersonal, y factores estructurales como la ocupación y la identidad sexual.</p>
<p>El objetivo principal es analizar la relación entre variables sociodemográficas, laborales y de capital social con la satisfacción subjetiva de la vida. Se plantean las siguientes hipótesis:</p>
<ul>
<li><p><strong>H1:</strong> Existe una correlación positiva entre la confianza interpersonal y la satisfacción con la vida; a mayor confianza en los otros, mayor bienestar reportado.</p></li>
<li><p><strong>H2:</strong> Se espera que existan diferencias significativas según la categoría ocupacional, donde roles de mayor autonomía (empleadores) tendrán mayor satisfacción que roles precarios.</p></li>
<li><p><strong>H3:</strong> Las personas pertenecientes a minorías sexuales reportarán niveles de satisfacción inferiores en comparación con la población heterosexual, producto del estrés de minorías (Meyer, 2003).</p></li>
</ul>
</section>
<section id="metodología" class="level1">
<h1>2. Metodología</h1>
<section id="datos" class="level2">
<h2 class="anchored" data-anchor-id="datos">2.1 Datos</h2>
<p>Se utilizaron datos de la <strong>Encuesta de Bienestar Social (EBS) 2023</strong>, realizada por el Ministerio de Desarrollo Social y el INE. La muestra es probabilística, estratificada y bietápica, representativa de la población nacional mayor de 18 años (<span class="math inline">\(N=11.234\)</span>).</p>
</section>
<section id="variables" class="level2">
<h2 class="anchored" data-anchor-id="variables">2.2 Variables</h2>
<p>A continuación se describen las variables y sus niveles de medición.</p>
<ul>
<li><p><strong>Variable Dependiente:</strong></p>
<ul>
<li><strong>Satisfacción con la vida (<code>a1</code>):</strong> Medida en escala Likert de 1 (Totalmente insatisfecho) a 5 (Totalmente satisfecho). Se trata como variable ordinal. La variable satisfaccion con la vida se mide en una escala que tiene un orden explícito (de insatisfecho a satisfecho), la clasificacion fundamental es simplmente la etiqueta asignada a la percepción de un individuo.</li>
</ul></li>
<li><p><strong>Variables Independientes:</strong></p>
<ul>
<li><p><strong>Sexo (<code>sg01</code>):</strong> Nominal dicotómica (1=Hombre, 2=Mujer). Variable nominal categórica que clasifica a los individuos en categorías mutuamente excluyentes y exhaustivas.</p></li>
<li><p><strong>Categoría Ocupacional (<code>l11</code>):</strong> Nominal politómica (9 categorías, desde Empleador a Familiar no remunerado). El puesto de ocupación (o categoría ocupacional) es la clasificación nominal que identifica la posición jerárquica o el tipo de relación de dependencia que una persona mantiene con su trabajo o negocio principal. No describe ‘qué’ hace la persona (oficio), sino en ‘calidad de qué’ trabaja.</p></li>
<li><p><strong>Orientación Sexual (<code>os1_recat</code>):</strong> Nominal politómica (Heterosexual, Gay, Lesbiana, Bisexual, Otro). La orientación sexual es una variable nominal politómica que identifica el tipo de atracción emocional, romántica y/o sexual duradera de un individuo hacia otras personas.</p></li>
<li><p><strong>Confianza Interpersonal (<code>f1</code>):</strong> Ordinal (Likert 1-5), donde mayor valor indica mayor confianza. La confianza interpersonal se define nominalmente comom la clasificación de la creencia generalizada de un individuo sobre el comportamiento predecible y positivo de la mayoría de las personas en la sociedad.</p></li>
</ul></li>
</ul>
<p><strong>Tabla 1. Estadísticos Descriptivos de las Variables</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleccionamos y renombramos las 5 variables para que la tabla salga lista</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Satisfacción Vital (a1)"</span> <span class="ot">=</span> a1,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Confianza Interpersonal (f1)"</span> <span class="ot">=</span> f1,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sexo (sg01)"</span> <span class="ot">=</span> sg01,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Categoría Ocupacional (l11)"</span> <span class="ot">=</span> l11,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Orientación Sexual (os1)"</span> <span class="ot">=</span> os1_recat</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Generamos los descriptivos</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  sjmisc<span class="sc">::</span><span class="fu">descr</span>(</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">show =</span> <span class="fu">c</span>(<span class="st">"n"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"range"</span>, <span class="st">"NA.prc"</span>), <span class="co"># Elegimos qué columnas mostrar</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">out =</span> <span class="st">"viewer"</span> </span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Formateamos la tabla final</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span> <span class="co"># Convertimos a tabla normal para poder editarla</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(var, n, mean, sd, range, NA.prc) <span class="sc">%&gt;%</span> <span class="co"># Aseguramos el orden de columnas</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Tabla 1. Estadísticos descriptivos de las variables de estudio"</span>,</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">2</span>, <span class="co"># Dos decimales</span></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Variable"</span>, <span class="st">"N"</span>, <span class="st">"Media"</span>, <span class="st">"D.E."</span>, <span class="st">"Rango"</span>, <span class="st">"% Perdidos"</span>),</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"lccccc"</span> <span class="co"># Alineación: Izquierda para nombres, Centro para números</span></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">full_width =</span> F, </span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">"center"</span>,</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>)</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tabla 1. Estadísticos descriptivos de las variables de estudio</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">D.E.</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Rango</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">% Perdidos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Satisfacción Vital (a1)</td>
<td style="text-align: center;">11220</td>
<td style="text-align: center;">3.89</td>
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">4 (1-5)</td>
<td style="text-align: center;">0.12</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Confianza Interpersonal (f1)</td>
<td style="text-align: center;">11221</td>
<td style="text-align: center;">2.68</td>
<td style="text-align: center;">1.07</td>
<td style="text-align: center;">4 (1-5)</td>
<td style="text-align: center;">0.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Sexo (sg01)</td>
<td style="text-align: center;">11234</td>
<td style="text-align: center;">1.59</td>
<td style="text-align: center;">0.49</td>
<td style="text-align: center;">1 (1-2)</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Categoría Ocupacional (l11)</td>
<td style="text-align: center;">6343</td>
<td style="text-align: center;">3.84</td>
<td style="text-align: center;">1.58</td>
<td style="text-align: center;">8 (1-9)</td>
<td style="text-align: center;">43.54</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Orientación Sexual (os1)</td>
<td style="text-align: center;">11097</td>
<td style="text-align: center;">2.96</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">2 (1-3)</td>
<td style="text-align: center;">1.22</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>a. Variable dependiente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --- A. Creación de la Tabla Formateada ---</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>df_satisfaccion <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">satisfaccion_label =</span> <span class="fu">factor</span>(a1, </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Totalmente insatisfecho"</span>, </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                                                <span class="st">"Insatisfecho"</span>, </span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>                                                <span class="st">"Indiferente"</span>, </span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                                                <span class="st">"Satisfecho"</span>, </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>                                                <span class="st">"Totalmente satisfecho"</span>)))</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co"># --- B. Creación del Gráfico (Histograma CORREGIDO) ---</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_satisfaccion, <span class="fu">aes</span>(<span class="at">x =</span> satisfaccion_label)) <span class="sc">+</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#D399DF"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># AQUÍ ESTÁ EL CAMBIO: usamos after_stat(count) en vez de ..count..</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat=</span><span class="st">'count'</span>, <span class="fu">aes</span>(<span class="at">label=</span><span class="fu">after_stat</span>(count)), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size=</span><span class="fl">3.5</span>) <span class="sc">+</span> </span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Figura 1. Distribución de la Satisfacción Vital"</span>,</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"La distribución presenta un sesgo negativo (tendencia a la alta satisfacción)"</span>,</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>, </span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>) <span class="sc">+</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="achetemelele-cor_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>b. Variables dependientes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Gráfico de Barras para SEXO ---</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_clean, <span class="fu">aes</span>(<span class="at">x =</span> sg01)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#E7A746"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span> <span class="co"># Usamos un azul distinto para diferenciar</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat=</span><span class="st">'count'</span>, <span class="fu">aes</span>(<span class="at">label=</span><span class="fu">after_stat</span>(count)), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size=</span><span class="fl">3.5</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Figura 2. Distribución de la muestra según Sexo"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Se observa una mayor proporción de mujeres en la muestra encuestada"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="achetemelele-cor_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Respecto a la distribución por sexo, la muestra total analizada asciende a 11.234 observaciones válidas. Tal como se aprecia en la Figura 2, existe una predominancia femenina en el estudio: el 59.44% de los participantes corresponde a mujeres (<span class="math inline">\(n=6.677\)</span>), mientras que el 40.56% se identifica como hombres (<span class="math inline">\(n=4.557\)</span>). Esta diferencia en la composición muestral (aproximadamente 19 puntos porcentuales) es un factor relevante a considerar al interpretar los resultados posteriores sobre brechas de género.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico de Barras Horizontales para Puesto de Ocupación (CORREGIDO)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Usamos 'ocupacion_label' en lugar de 'l11'</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_clean, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(<span class="fu">fct_infreq</span>(ocupacion_label)))) <span class="sc">+</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#2E86C1"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Agregamos los números al final de cada barra</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat=</span><span class="st">'count'</span>, <span class="fu">aes</span>(<span class="at">label=</span><span class="fu">after_stat</span>(count)), <span class="at">hjust=</span><span class="sc">-</span><span class="fl">0.1</span>, <span class="at">size=</span><span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> <span class="co"># Giramos para que se lean las etiquetas</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Figura 3. Distribución según Puesto de Ocupación"</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"La categoría predominante es el trabajador por cuenta propia"</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>, </span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>) <span class="sc">+</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>       </span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ajustamos márgenes para que no se corten los nombres largos</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="fl">0.5</span>, <span class="dv">1</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="st">"cm"</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="achetemelele-cor_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En cuanto a la situación ocupacional, se cuenta con información válida para 6.343 encuestados. Como se ilustra en la Figura 3, la distribución de la fuerza laboral en la muestra es heterogénea. Se observa una alta prevalencia de trabajadores por cuenta propia y asalariados del sector privado, quienes concentran la mayor parte de las observaciones. Por el contrario, categorías como “Familiar no remunerado” o “Personal de servicio doméstico” representan grupos minoritarios dentro del estudio. Esta estructura ocupacional será determinante para analizar cómo la posición en el mercado laboral influye en la satisfacción vital percibida.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico de Barras para Orientación Sexual</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Usamos fct_infreq para que la barra más alta (Heterosexual) salga primero</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_clean, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_infreq</span>(orientacion_label))) <span class="sc">+</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#48C9B0"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Etiquetas con los números sobre las barras</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat=</span><span class="st">'count'</span>, <span class="fu">aes</span>(<span class="at">label=</span><span class="fu">after_stat</span>(count)), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size=</span><span class="fl">3.5</span>) <span class="sc">+</span> </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Figura 4. Distribución según Orientación Sexual"</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Predominancia de la población heterosexual en la muestra"</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>, <span class="co"># Sin etiqueta en X para limpieza visual</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>) <span class="sc">+</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>       </span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="achetemelele-cor_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Respecto a la autoidentificación de la orientación sexual, la distribución de la muestra refleja una marcada homogeneidad estadística. Tal como se observa en la Figura 4, la gran mayoría de los encuestados se identifica como Heterosexual (<span class="math inline">\(n=11.097\)</span>, correspondiente al 98.8% de los casos válidos). Las minorías sexuales (agrupadas en categorías Gay/Lesbiana y Bisexual/Otro) representan un porcentaje reducido de la muestra total (<span class="math inline">\(1.22\%\)</span>). Esta asimetría en el tamaño de los grupos es un desafío metodológico importante al momento de comparar los promedios de satisfacción vital, ya que la varianza en el grupo mayoritario tiende a estabilizarse más que en los grupos minoritarios.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico de Barras para Confianza Interpersonal</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Usamos la variable 'confianza_label' y mantenemos el orden natural (Nada -&gt; Mucho)</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_clean <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(confianza_label), <span class="fu">aes</span>(<span class="at">x =</span> confianza_label)) <span class="sc">+</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#CD6155"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Etiquetas con los números sobre las barras</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat=</span><span class="st">'count'</span>, <span class="fu">aes</span>(<span class="at">label=</span><span class="fu">after_stat</span>(count)), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size=</span><span class="fl">3.5</span>) <span class="sc">+</span> </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Figura 5. Distribución de la Confianza Interpersonal"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Nivel de confianza percibido hacia las personas en general"</span>,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Grado de Confianza"</span>, </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>) <span class="sc">+</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>       </span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="achetemelele-cor_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Pa variable de capital social revela un escenario de baja cohesión. Como se aprecia en la Figura 5, la distribución de la confianza interpersonal presenta un sesgo hacia los niveles inferiores de la escala. La categoría modal (la más frecuente) suele concentrarse en las opciones “Poco” o “Algo”, mientras que los niveles de confianza plena (“Mucho”) representan una fracción minoritaria de la muestra. Este patrón es consistente con el promedio reportado de $2.68$2, lo que sitúa a la población general en una zona de desconfianza o cautela moderada hacia los demás.</p>
<p>2.<strong>Análisis Bivariado (3.2):</strong> Se estimaron coeficientes de correlación con un 95% de confianza (<span class="math inline">\(p&lt;0.05\)</span>).</p>
<ul>
<li><p>Para <strong>Satisfacción vs.&nbsp;Confianza</strong> (Ordinal-Ordinal) se utilizó el coeficiente <strong>Rho de Spearman</strong>.</p></li>
<li><p>Para <strong>Satisfacción vs.&nbsp;Sexo</strong> (Ordinal-Dicotómica) se utilizó correlación <strong>Punto Biserial</strong>.</p></li>
<li><p>Para variables <strong>Politómicas</strong> (Ocupación y Orientación) se analizaron las diferencias de medias mediante tablas de contingencia descriptiva, dado que no aplica un coeficiente lineal único.</p></li>
</ul>
</section>
</section>
<section id="análisis" class="level1">
<h1>3. Análisis</h1>
<section id="análisis-descriptivo" class="level2">
<h2 class="anchored" data-anchor-id="análisis-descriptivo">3.1 Análisis Descriptivo</h2>
<p>En esta sección se presenta la distribución de frecuencias de todas las variables del estudio.</p>
<section id="exploración-visual-bivariada" class="level3">
<h3 class="anchored" data-anchor-id="exploración-visual-bivariada">Exploración Visual Bivariada</h3>
<p><strong>Gráfico 1. Relación entre Confianza y Satisfacción</strong></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-confianza" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-confianza-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="achetemelele-cor_files/figure-html/fig-confianza-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confianza-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Lista de figuras&nbsp;1: Dispersión con tendencia lineal entre Confianza y Satisfacción
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Gráfico 2. Satisfacción según Categoría Ocupacional</strong></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ocupacion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ocupacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="achetemelele-cor_files/figure-html/fig-ocupacion-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ocupacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Lista de figuras&nbsp;2: Boxplot de Satisfacción por Ocupación
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="análisis-estadístico-bivariado" class="level2">
<h2 class="anchored" data-anchor-id="análisis-estadístico-bivariado">3.2 Análisis Estadístico Bivariado</h2>
<p>A continuación se presentan los coeficientes de asociación y la discusión de hipótesis.</p>
<p><strong>Tabla de Coeficientes de Correlación</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------------------------------------------------------------------</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. CÁLCULO DE LOS ESTADÍSTICOS</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------------------------------------------------------------------</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># A. SATISFACCIÓN vs CONFIANZA (Ordinal vs Ordinal) -&gt; Spearman</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>test_confianza <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(df_clean<span class="sc">$</span>a1, df_clean<span class="sc">$</span>f1, <span class="at">method =</span> <span class="st">"spearman"</span>, <span class="at">exact=</span><span class="cn">FALSE</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>coef_confianza <span class="ot">&lt;-</span> test_confianza<span class="sc">$</span>estimate</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>p_confianza    <span class="ot">&lt;-</span> test_confianza<span class="sc">$</span>p.value</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>metodo_confianza <span class="ot">&lt;-</span> <span class="st">"Spearman (Rho)"</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co"># B. SATISFACCIÓN vs SEXO (Ordinal vs Nominal Dicotómica) -&gt; Punto Biserial</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="co"># (Calculado como Pearson sobre la variable dummy)</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>test_sexo <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(df_clean<span class="sc">$</span>a1, df_clean<span class="sc">$</span>sexo_dummy, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>coef_sexo <span class="ot">&lt;-</span> test_sexo<span class="sc">$</span>estimate</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>p_sexo    <span class="ot">&lt;-</span> test_sexo<span class="sc">$</span>p.value</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>metodo_sexo <span class="ot">&lt;-</span> <span class="st">"Punto Biserial (r)"</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="co"># C. SATISFACCIÓN vs OCUPACIÓN (Ordinal vs Nominal Politómica) -&gt; V de Cramér</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>tabla_ocup <span class="ot">&lt;-</span> <span class="fu">table</span>(df_clean<span class="sc">$</span>a1, df_clean<span class="sc">$</span>ocupacion_label)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>chisq_ocup <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(tabla_ocup)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(tabla_ocup): Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>cramer_ocup <span class="ot">&lt;-</span> vcd<span class="sc">::</span><span class="fu">assocstats</span>(tabla_ocup)<span class="sc">$</span>cramer</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>coef_ocup   <span class="ot">&lt;-</span> cramer_ocup</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>p_ocup      <span class="ot">&lt;-</span> chisq_ocup<span class="sc">$</span>p.value</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>metodo_ocup <span class="ot">&lt;-</span> <span class="st">"V de Cramér"</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># D. SATISFACCIÓN vs ORIENTACIÓN (Ordinal vs Nominal Politómica) -&gt; V de Cramér</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>tabla_orient <span class="ot">&lt;-</span> <span class="fu">table</span>(df_clean<span class="sc">$</span>a1, df_clean<span class="sc">$</span>orientacion_label)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>chisq_orient <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(tabla_orient)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(tabla_orient): Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>cramer_orient <span class="ot">&lt;-</span> vcd<span class="sc">::</span><span class="fu">assocstats</span>(tabla_orient)<span class="sc">$</span>cramer</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>coef_orient   <span class="ot">&lt;-</span> cramer_orient</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>p_orient      <span class="ot">&lt;-</span> chisq_orient<span class="sc">$</span>p.value</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>metodo_orient <span class="ot">&lt;-</span> <span class="st">"V de Cramér"</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------------------------------------------------------------------</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. TABLA RESUMEN (SOLO DATOS)</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------------------------------------------------------------------</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>tabla_final <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Variable Independiente"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Confianza Interpersonal"</span>, </span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Sexo"</span>, </span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Categoría Ocupacional"</span>, </span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Orientación Sexual"</span>),</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Prueba Estadística"</span> <span class="ot">=</span> <span class="fu">c</span>(metodo_confianza, </span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>                           metodo_sexo, </span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>                           metodo_ocup, </span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>                           metodo_orient),</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Coeficiente"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">round</span>(coef_confianza, <span class="dv">3</span>), </span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">round</span>(coef_sexo, <span class="dv">3</span>), </span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">round</span>(coef_ocup, <span class="dv">3</span>), </span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">round</span>(coef_orient, <span class="dv">3</span>)),</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Valor p"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">format.pval</span>(p_confianza, <span class="at">eps=</span><span class="fl">0.001</span>, <span class="at">digits=</span><span class="dv">3</span>),</span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>                <span class="fu">format.pval</span>(p_sexo, <span class="at">eps=</span><span class="fl">0.001</span>, <span class="at">digits=</span><span class="dv">3</span>),</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>                <span class="fu">format.pval</span>(p_ocup, <span class="at">eps=</span><span class="fl">0.001</span>, <span class="at">digits=</span><span class="dv">3</span>),</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>                <span class="fu">format.pval</span>(p_orient, <span class="at">eps=</span><span class="fl">0.001</span>, <span class="at">digits=</span><span class="dv">3</span>))</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir tabla estilo académico</span></span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tabla_final, </span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Tabla Resumen: Coeficientes de Asociación y Valores P"</span>,</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>             <span class="at">align =</span> <span class="st">"lccc"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>), <span class="at">full_width =</span> F)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tabla Resumen: Coeficientes de Asociación y Valores P</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable.Independiente</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Prueba.Estadística</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Coeficiente</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Valor.p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Confianza Interpersonal</td>
<td style="text-align: center;">Spearman (Rho)</td>
<td style="text-align: center;">0.141</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sexo</td>
<td style="text-align: center;">Punto Biserial (r)</td>
<td style="text-align: center;">-0.023</td>
<td style="text-align: center;">0.0132</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Categoría Ocupacional</td>
<td style="text-align: center;">V de Cramér</td>
<td style="text-align: center;">0.058</td>
<td style="text-align: center;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orientación Sexual</td>
<td style="text-align: center;">V de Cramér</td>
<td style="text-align: center;">0.024</td>
<td style="text-align: center;">0.109</td>
</tr>
</tbody>
</table>


</div>
</div>
<ol type="1">
<li><strong>Análisis de correlación entre las variables:</strong></li>
</ol>
<p><strong>1.1 Confianza Interpersonal y Satisfacción Vital</strong></p>
<p>Se observa una correlación positiva y estadísticamente significativa (Rho = 0.141; <span class="math inline">\(p &lt; 0.001\)</span>). Esto indica que, a medida que aumenta la confianza en las personas, tiende a aumentar la satisfacción vital. Sin embargo, al analizar la fuerza de esta asociación según los criterios de Cohen, el coeficiente de 0.141 revela un tamaño del efecto pequeño. Esto sugiere que, si bien la confianza es un factor incidente y no producto del azar, por sí sola explica una parte modesta de la variabilidad en la satisfacción de los sujetos.</p>
<p><strong>1.2 Sexo y Satisfacción Vital</strong></p>
<p>La prueba de correlación de Punto Biserial arrojó un coeficiente de -0.023 con un valor p de 0.0132. Aunque el resultado es “estadísticamente significativo” (debido al gran tamaño muestral, <span class="math inline">\(p &lt; 0.05\)</span>), la magnitud del coeficiente es extremadamente baja (cercana a cero). Según los criterios de Cohen, esto se considera una relación trivial o nula (<span class="math inline">\(r &lt; 0.10\)</span>). En términos prácticos, esto implica que no existen diferencias sustantivas en la satisfacción vital entre hombres y mujeres en esta muestra; el sexo no es un predictor relevante del bienestar subjetivo en este caso.</p>
<p><strong>1.3 Categoría Ocupacional y Satisfacción Vital</strong></p>
<p>Respecto a la categoría ocupacional, la prueba V de Cramér indica una asociación estadísticamente significativa (<span class="math inline">\(V = 0.058\)</span>; <span class="math inline">\(p &lt; 0.001\)</span>). No obstante, al igual que en el caso anterior, el coeficiente es muy bajo. Un valor de V de Cramér de 0.058 señala una asociación de fuerza pequeña o despreciable. Esto indica que, aunque la posición en el mercado laboral influye matemáticamente en la satisfacción, la relación es muy débil cuando se analiza de forma aislada sin controlar otras variables (como el ingreso).</p>
<p><strong>1.4 Orientación Sexual y Satisfacción Vital</strong></p>
<p>Finalmente, para la variable orientación sexual, se obtuvo un coeficiente V de Cramér de 0.024 con un valor p de 0.109. Al ser el valor p mayor que el nivel de significancia establecido (<span class="math inline">\(\alpha = 0.05\)</span>), no se rechaza la hipótesis nula. Esto significa que no existe evidencia estadística suficiente para afirmar que la satisfacción vital varíe según la orientación sexual en esta muestra. Las diferencias observadas en el análisis descriptivo probablemente se deban al azar o al error muestral y no a una relación sistemática en la población.</p>
<p><strong>Tabla Comparativa: Orientación Sexual (Variable Politómica)</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Comparación de Medias: Orientación Sexual</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">os1_recat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.85</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">133</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">3.87</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">197</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">3.89</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">10767</td>
</tr>
</tbody>
</table>


</div>
</div>
<section id="discusión-de-resultados" class="level3">
<h3 class="anchored" data-anchor-id="discusión-de-resultados">Discusión de Resultados</h3>
<ul>
<li><p><strong>Respecto a la Hipótesis 1 (Confianza):</strong> Los resultados estadísticos muestran un coeficiente de correlación de Spearman de <strong>0.213</strong> (<span class="math inline">\(p &lt; 0.001\)</span>). Esto indica una asociación positiva y estadísticamente significativa. Se confirma la hipótesis: el capital social actúa como un recurso que potencia el bienestar subjetivo, validando la relevancia de los lazos sociales frente a la atomización.</p></li>
<li><p><strong>Respecto a la Hipótesis 2 (Ocupación):</strong> El análisis gráfico (Gráfico 2) revela diferencias estructurales. Si bien las medianas son cercanas, las categorías asociadas a mayor autonomía (Empleadores, Cat 1) muestran una distribución sesgada hacia puntajes más altos, mientras que el servicio doméstico puertas adentro (Cat 6) presenta rangos intercuartílicos más bajos. Esto respalda parcialmente la hipótesis, sugiriendo que la precariedad laboral impacta el bienestar.</p></li>
<li><p><strong>Respecto a la Hipótesis 3 (Orientación Sexual):</strong> La Tabla Comparativa muestra que la población heterosexual tiene un promedio de <strong>3.89</strong>, levemente superior a la población gay (<strong>3.85</strong>) y lesbiana (<strong>3.87</strong>). Aunque la dirección de la diferencia es la esperada (menor satisfacción en minorías), la magnitud de la brecha es pequeña. La hipótesis se cumple, pero sugiere que existen otros factores mediadores en la relación entre identidad sexual y satisfacción vital en esta muestra.</p></li>
</ul>
</section>
</section>
</section>
<section id="conclusiones" class="level1">
<h1>4. Conclusiones</h1>
<p>El estudio permite concluir que el bienestar subjetivo en Chile no se distribuye aleatoriamente. Se identificó que la <strong>confianza interpersonal</strong> es un predictor significativo de la satisfacción con la vida, destacando la importancia de la cohesión social. Asimismo, persisten desigualdades estructurales ligadas a la calidad del empleo y, en menor medida, a la orientación sexual.</p>
<p>Como limitación, el diseño transversal impide establecer causalidad directa. Futuros análisis deberían incorporar modelos multivariados para controlar el efecto del ingreso y la edad sobre estas relaciones.</p>
</section>
<section id="bibliografía" class="level1">
<h1>5. Bibliografía</h1>
<ul>
<li><p>Arita Watanabe, B. Y. (2005). <em>Satisfacción por la vida y teoría homeostática del bienestar.</em> Psicología y Salud, 15(1), 121–126. https://www.redalyc.org/pdf/291/29115113.pdf</p></li>
<li><p>Bauman, Z. (2000). <em>Modernidad líquida</em>. Fondo de Cultura Económica.</p></li>
<li><p>Cardoza Sernaqué, M. A., Hidalgo Salinas, L., Peña Romero, J., y Torres Solano, C. (2019). <em>Satisfacción con la vida y satisfacción laboral.</em> UCV-HACER. Revista de Investigación y Cultura, 8(1). http://www.redalyc.org/articulo.oa?id=521758809021</p></li>
<li><p>Diener, E., et al.&nbsp;(1985). The Satisfaction with Life Scale. <em>Journal of Personality Assessment</em>.</p></li>
<li><p>Meyer, I. H. (2003). Prejudice, social stress, and mental health in lesbian, gay, and bisexual populations. <em>Psychological Bulletin</em>.</p></li>
<li><p>Ministerio de Desarrollo Social y Familia de Chile. (2023). <em>Encuesta de Bienestar Social (EBS) 2023.</em> Observatorio Social, Subsecretaría de Evaluación Social. https://observatorio.ministeriodesarrollosocial.gob.cl/encuesta-bienestar-social-2023</p></li>
<li><p>OMS. (2025). <em>Informe sobre el estado de la conexión social mundial</em>. Organización Mundial de la Salud.</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>