<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Seguridad barrial, edad y sexo y su impacto en la satisfacción con la democracia en Chile: Análisis en base al Estudio Longitudinal Social de Chile.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Trabajofinalcorrelacional_files/libs/clipboard/clipboard.min.js"></script>
<script src="Trabajofinalcorrelacional_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Trabajofinalcorrelacional_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Trabajofinalcorrelacional_files/libs/quarto-html/popper.min.js"></script>
<script src="Trabajofinalcorrelacional_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Trabajofinalcorrelacional_files/libs/quarto-html/anchor.min.js"></script>
<link href="Trabajofinalcorrelacional_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Trabajofinalcorrelacional_files/libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Trabajofinalcorrelacional_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Trabajofinalcorrelacional_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Trabajofinalcorrelacional_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="Trabajofinalcorrelacional_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="Trabajofinalcorrelacional_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Seguridad barrial, edad y sexo y su impacto en la satisfacción con la democracia en Chile: Análisis en base al Estudio Longitudinal Social de Chile.</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>integrantes: Camilo Núñez, Sebastian Llanos, Armando Álvarez, Kintrüy Ancaten y Elisa Palma</strong></p>
<p><strong>Profesor de Cátedra: Juan Castillo</strong></p>
<p><strong>Profesor colaborador: Kevin Carrasco</strong></p>
<p><strong>Cuarto semestre Sociología</strong></p>
<p><strong>Fecha: 22/11/25</strong></p>
<p><strong>Resumen</strong></p>
<p>Latinoamérica a mediados del siglo pasado se cubrió bajo el velo de las dictaduras en países como Brasil, Panamá, Guatemala, Nicaragua, Paraguay, Argentina y Chile. En nuestro país en específico, el retorno a la democracia generó grandes expectativas sobre la (re)construcción de la nación, pero a día de hoy se pone en duda el “fallido” proyecto de democracia en Chile, expresándose en el descontento social generalizado en patologías sociales. En base al Estudio Longitudinal Social de Chile (ELSOC) realizado por el Centro de Estudios de Conflicto y Cohesión Social (COES) este estudio tiene de objetivo general estudiar los niveles de satisfacción con el régimen democratico chileno ad portas de unas elecciones caracterizadas por candidatos “extremos”, esto a través de revisar tres hipótesis, se espera que a mayor satisfacción son la seguridad en el barrio mayor sea la satisfacción con la democracia (H1), en segundo lugar se espera que a menor edad del encuestado menor satisfacción con la democracia (H2) y por último se espera que a mayor edad mayor sea la satisfacción con la democracia (H3).&nbsp;</p>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción"><strong>1 Introducción</strong></h2>
<p>En 1990 Chile retornó a la democracia después de 17 años de la dictadura encabezada por Augusto Pinochet Ugarte. 35 años después, el proyecto democrativo tambalea por culpa de las propias expectativas que generó y más específicamente por la naturaleza latinoamericana de su “dinámica sociopolítica convulsionada” (Natalucci et al.&nbsp;2025, p.&nbsp;2). En la actualidad, se vive una contingencia respecto a una democracia debilitada, producto de un proceso marcado por proyectos de izquierda en búsqueda de consolidarse como gobiernos progresistas y una respuesta (como si de un péndulo se tratase) de proyectos con tendencias de extrema derecha e ideologías económicas de reducción del Estado que han consolidado en general una democracia puesta en duda desde distintos sectores del espectro político, enfrentamientos constantes entre extremos izquierdos y derechos, procesos de protestas que surgen como respuesta al agotamiento social y un “deterioro significativo de las condiciones de vida y calidad de la democracia” (Natalucci et al.&nbsp;2025, p.&nbsp;2). Es entonces la temática central de este estudio la satisfacción de la ciudadanía con respecto a la democracia.</p>
<p>El debilitamiento de la democracia producto de la oscilación entre proyectos de izquierda y derecha suele asociarse a “patologías” en la sociedad como la desigualdad económica y social persistente, crisis de la representación política, instituciones frágiles, demandas históricas sin respuesta, represión excesiva por parte del Estado, el lento avance en materia de igualdad de género/sexo y el descontento generalizado de cohortes etarias (Avendaño, 2019). Son las últimas dos variables (sexo y edad) las que conducen este estudio para evaluar la satisfacción de la ciudadanía con respecto a la democracia en Chile, sumando la satisfacción con la seguridad barrial en el contexto de un país azotado por un nivel de sensación de inseguridad alto (Lissardy, 2025).&nbsp;</p>
<p>El objetivo principal de este estudio es entender el debilitamiento de la satisfacción respecto a la democracia a través de tres variables.&nbsp;</p>
<p>Con respecto al sexo, hay que considerar la problemática histórica de la desigualdad entre hombres y mujeres, que ha llevado a las mujeres a estar en una casi perpetua desigualdad social, económica y política a comparación de los hombres. Según Hansen y Goenaga (2021), existe una relación negativa entre ser mujer y estar satisfecha respecto a la democracia, esto en un marco donde las mujeres están menos satisfechas con la protección social referente (por ejemplo) a la reducción ineficiente de la brecha de ingresos entre hombres y mujeres. Es en este contexto que el presente estudio incluye al sexo como una variable para evaular la satisfacción con la democracia en el sentido de que una democracia firme debería de generar igualdad entre sexos/géneros.&nbsp;</p>
<p>Por otro lado, la edad/cohortes etarios como variable para evaluar la satisfacción con la democracia corresponde al hecho de que existen grupos etarios menos satisfechos con el proyecto democratico chileno. En la investigación de Bargsted, Somma y Muñoz (2019) se establece que en desde la vuelta a la democracia ha existido un declive notable y sostenido en las participación de elecciones en el país (Bargsted et al.&nbsp;2019, p.2). La investigación sostiene que el grupo etario con menor participación política en la actualidad son los adultos jóvenes (18 a 35 años) estos hallazgos sugieren que los adultos jóvenes se encuentran con desafección política lo que refleja una desconexión con el sistema político institucional, mientras que los grupos más mayores tienen niveles de participación mayor y más conformidad con la democracia. Por otro lado, la investigación de Morales (2020) se conecta a la realidad expuesta por la investigación anterior con respecto a la baja participación política de los adultos jóvenes y ahonda en la satisfacción de este grupo etario con respecto al funcionamiento de la democracia, exponiendo que son un grupo que si bien ha vivido prácticamente toda su vida en democracia, han presenciado el desgaste de la misma y plantea 4 crisis que explican esta “desilución” con el proyecto democratico chileno post dictadura: 1) crisis de la participación (ya mencionada) 2) crisis de representación 3) crisis de la confianza institucional y 4) crisis de probidad. Se entiende también a partir de esta investigación que a medida que la edad aumenta los niveles de disconformidad con el proyecto democratico baja como una expresión del asentamiento.</p>
<p>La última variable a estudiar es la referente a los niveles de satisfacción con la seguridad del barrio. En el estudio de Alvarado (2024) se entiende seguridad barrial como la ausencia de actividades delictivas visibles, como por ejemplo, la venta de droga. La relación es simple, si existe inseguridad y por ende victimización la confianza y la satisfacción con las instituciones policiales, el Estado y el régimen democratico se erosiona, y al revés, si existe una percepción positiva con respecto a la seguridad del barrio se traduce en mayor aprobación a la democracia: “la satisfacción con el régimen está asociada con una percepción de menor presencia del crimen, así como con una buena valoración del trabajo policial y la confianza en la autoridad del Estado” (Alvarado, 2024, p.&nbsp;20).&nbsp;</p>
<p>Las hipótesis que surgen a partir de la selección y el estudio de las variables aquí presentes son las siguientes: <strong>H1</strong>: se espera que a mayor satisfacción de la seguridad en el barrio mayor sea la satisfacción con la democracia <strong>H2</strong>: se espera que exista una correlación negativa entre ser mujer y la satisfacción con la democracia. <strong>H3</strong>: se espera que a mayor edad mayor sea la satisfacción con la democracia.</p>
<p>Estudios como el aquí presente cobran relevancia en la actualidad en el contexto en el que se encuentra el país. Chile se encuentra ad portas de una segunda vuelta en las elecciones presidenciales 2025, donde se enfrentarán la candidata del partido comunista Jeannette Jara y el candidato del partido republicano José Antonio Kast, ambos de polos relativamente extremos del espectro político. Con unas elecciones de esta naturaleza, es siempre interesante e importante entender que tan satisfecha está la población nacional con respecto al desempeño de la democracia, ya sea para entender los resultados de las elecciones, como es que llegan ciertos candidatos a las mismas y más importante aún, si es que Chile sigue creyendo en el proyecto democratico que se levantó posterior a la dictadura (Zanotti y Villalobos, 2025).&nbsp;&nbsp;&nbsp;</p>
</section>
<section id="metodología" class="level2">
<h2 class="anchored" data-anchor-id="metodología"><strong>2 Metodología</strong></h2>
<section id="datos" class="level3">
<h3 class="anchored" data-anchor-id="datos"><strong>2.1 Datos</strong></h3>
<p>La encuesta ELSOC está caracterizada por ser una encuesta de naturaleza longitudinal/panel, siguiendo a las mismas personas por periodos extendidos de tiempo (años) en el formato de “olas” de recolección de datos, para este estudio se utilizó la encuesta ELSOC que abarca desde el año 2016 hasta el 2023. La encuesta se centra en analizar la estabilidad y el cambio de las creencias, actitudes y percepciones de la población urbana. Su foco central es la cohesión y el conflicto social, incluyendo variables relacionadas con la confianza interpersonal, la identificación política, el apoyo a la democracia, las actitudes hacia movimientos sociales y la desigualdad, y la sociabilidad barrial. La encuesta ELSOC tiene una muestra objetivo de aproximadamente 3.000 individuos.&nbsp;</p>
</section>
<section id="variables" class="level3">
<h3 class="anchored" data-anchor-id="variables"><strong>2.2 Variables</strong></h3>
<p>La variable “c01”, renombrada “satisfaccion_democracia_categorica” al momento de procesar los datos, mide la satisfacción del encuestado con la democracia en Chile. La variable es ordinal tipo Likert de 1 al 5. Los valores mayores indican una mejor evaluación, siendo 1 “Muy insatisfecho” y 5&nbsp; “Muy satisfecho”</p>
<p>La variable “m0_sexo”,&nbsp; renombrada “sexo_categorica” al momento de procesar los datos,&nbsp; identifica el sexo declarado por la persona encuestada. La variable es nominal categórica donde originalmente 1 corresponde a “Hombre” y 2 corresponde a “Mujer”. Para el análisis, fue recodificada en una variable dummy donde 0 corresponde a “Hombre” y 1 corresponde a “Mujer”.</p>
<p>La variable “t06_01”,&nbsp; renombrada “satisfaccion_seguridad_barrio_categorica” al momento de procesar los datos, mide el grado de satisfacción del encuestado con la seguridad en su barrio. La variable es ordinal tipo Likert de 1 al 5, los valores mayores indican una mejor evaluación, siendo 1 “Muy insatisfecho” y 5 “Muy satisfecho”.</p>
<p>La variable “m0_edad”, renombrada “edad_entrevistado_continua” al momento de procesar los datos, corresponde a la edad del entrevistado medida en años. La variable es numérica continua.</p>
<div class="cell">
<div id="fig-figura1" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-figura1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
vars
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:right;">
trimmed
</th>
<th style="text-align:right;">
mad
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
range
</th>
<th style="text-align:right;">
skew
</th>
<th style="text-align:right;">
kurtosis
</th>
<th style="text-align:right;">
se
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
satisfaccion_democracia_categorica
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
14527
</td>
<td style="text-align:right;">
2.0629173
</td>
<td style="text-align:right;">
1.0636657
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1.9263529
</td>
<td style="text-align:right;">
1.4826
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0.7144681
</td>
<td style="text-align:right;">
-0.3135813
</td>
<td style="text-align:right;">
0.0088250
</td>
</tr>
<tr>
<td style="text-align:left;">
sexo_categorica
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
14527
</td>
<td style="text-align:right;">
0.6129965
</td>
<td style="text-align:right;">
0.4870812
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.6412286
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
-0.4639420
</td>
<td style="text-align:right;">
-1.7848807
</td>
<td style="text-align:right;">
0.0040412
</td>
</tr>
<tr>
<td style="text-align:left;">
satisfaccion_seguridad_barrio_categorica
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
14527
</td>
<td style="text-align:right;">
3.3104564
</td>
<td style="text-align:right;">
1.1011066
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
3.3491353
</td>
<td style="text-align:right;">
1.4826
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
-0.4958177
</td>
<td style="text-align:right;">
-0.7626794
</td>
<td style="text-align:right;">
0.0091357
</td>
</tr>
<tr>
<td style="text-align:left;">
edad_entrevistado_continua
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
14527
</td>
<td style="text-align:right;">
47.9770083
</td>
<td style="text-align:right;">
15.4413083
</td>
<td style="text-align:right;">
48
</td>
<td style="text-align:right;">
47.8126990
</td>
<td style="text-align:right;">
17.7912
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
92
</td>
<td style="text-align:right;">
74
</td>
<td style="text-align:right;">
0.0525004
</td>
<td style="text-align:right;">
-0.9572560
</td>
<td style="text-align:right;">
0.1281139
</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-figura1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Tabla: descriptivos de todas las variables
</figcaption>
</figure>
</div>
</div>
</section>
<section id="métodos" class="level3">
<h3 class="anchored" data-anchor-id="métodos"><strong>2.3 Métodos</strong></h3>
<p>Para la evaluación de la Hipótesis 1, se calculó el coeficiente de correlación de Spearman entre las variables “satisfaccion_democracia_categorica” y “satisfaccion_seguridad_barrio_categorica”, para corroborar si existe una correlación estadísticamente significativa entre la satisfacción con la democracia en Chile y la satisfacción con la seguridad en los barrios.&nbsp;</p>
<p>Siguiendo con la hipótesis 2, se utilizó la prueba de Chi-Cuadrado (X2) entre las variables&nbsp; “satisfaccion_democracia_categorica” y “sexo_categorica”, para evaluar si existe una asociación estadisticamente significativa entre la satisfacción con la democracia en Chile y el sexo del encuestado.</p>
<p>Por último, para la evaluación de la hipótesis 3, se calculó el coeficiente de correlación de Spearman entre las variables “satisfaccion_democracia_categorica” y “edad_entrevistado_continua”, para evaluar si existe una correlación estadísticamente significativa entre la satisfacción con la democracia en Chile y la edad del encuestado.</p>
<p>Tanto los análisis estadísticos como las pruebas para contraste de hipótesis se llevaron a cabo utilizando el software Rstudio</p>
</section>
</section>
<section id="análisis" class="level2">
<h2 class="anchored" data-anchor-id="análisis"><strong>3 Análisis</strong></h2>
<section id="análisis-descriptivos" class="level3">
<h3 class="anchored" data-anchor-id="análisis-descriptivos"><strong>3.1 Análisis descriptivos</strong></h3>
<section id="descriptivos-variable-satisfacción-con-la-democracia" class="level4">
<h4 class="anchored" data-anchor-id="descriptivos-variable-satisfacción-con-la-democracia"><strong>3.1.1 Descriptivos variable satisfacción con la democracia</strong></h4>
<div class="cell">
<div id="fig-figura2" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-figura2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
vars
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:right;">
trimmed
</th>
<th style="text-align:right;">
mad
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
range
</th>
<th style="text-align:right;">
skew
</th>
<th style="text-align:right;">
kurtosis
</th>
<th style="text-align:right;">
se
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
X1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
14527
</td>
<td style="text-align:right;">
2.062917
</td>
<td style="text-align:right;">
1.063666
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1.926353
</td>
<td style="text-align:right;">
1.4826
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0.7144681
</td>
<td style="text-align:right;">
-0.3135813
</td>
<td style="text-align:right;">
0.008825
</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-figura2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Tabla de descriptivos: Satisfaccion con la democracia
</figcaption>
</figure>
</div>
</div>
<p>Como se puede observar en la <a href="#fig-figura2" class="quarto-xref">Figura&nbsp;2</a>, la variable “satisfaccion_democracia_categorica” presenta un promedio de 2.06. Como la escala va de 1 a 5, 1 siendo “Muy insatisfecho” y 5 “Muy satisfecho”, la media sugiere que, en promedio, las personas tienden a mostrar una baja satisfacción con la democracia en Chile. Además, la mediana es 2, lo que indica que al menos el 50% de los encuestados se sitúan en niveles de insatisfacción.&nbsp;</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-figura3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-figura3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Trabajofinalcorrelacional_files/figure-html/fig-figura3-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-figura3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Grafico de barras: Satisfaccion con la democracia
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="descriptivos-variable-edad" class="level4">
<h4 class="anchored" data-anchor-id="descriptivos-variable-edad"><strong>3.1.2 Descriptivos variable edad</strong></h4>
<div class="cell">
<div id="fig-figura4" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-figura4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
vars
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:right;">
trimmed
</th>
<th style="text-align:right;">
mad
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
range
</th>
<th style="text-align:right;">
skew
</th>
<th style="text-align:right;">
kurtosis
</th>
<th style="text-align:right;">
se
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
X1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
14527
</td>
<td style="text-align:right;">
47.97701
</td>
<td style="text-align:right;">
15.44131
</td>
<td style="text-align:right;">
48
</td>
<td style="text-align:right;">
47.8127
</td>
<td style="text-align:right;">
17.7912
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
92
</td>
<td style="text-align:right;">
74
</td>
<td style="text-align:right;">
0.0525004
</td>
<td style="text-align:right;">
-0.957256
</td>
<td style="text-align:right;">
0.1281139
</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-figura4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Tabla de descriptivos: Edad
</figcaption>
</figure>
</div>
</div>
<p>Como se puede observar en la <a href="#fig-figura4" class="quarto-xref">Figura&nbsp;4</a> la variable “edad_entrevistado_continua” presenta una mediana de 48 años, lo que nos permite afirmar que el 50% de los entrevistados tienen 48 años o menos. La media por otro lado es de 47,97 años, lo que es prácticamente igual a la mediana. Además, la variable presenta un rango que va desde los 18 años hasta los 72 años, lo que indica un amplio rango etario en la muestra</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-figura5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-figura5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Trabajofinalcorrelacional_files/figure-html/fig-figura5-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-figura5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Histograma: Edad
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="descriptivos-variable-satisfacción-seguridad-del-barrio" class="level4">
<h4 class="anchored" data-anchor-id="descriptivos-variable-satisfacción-seguridad-del-barrio">3.1.3 descriptivos variable satisfacción seguridad del barrio</h4>
<div class="cell">
<div id="fig-figura6" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-figura6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
vars
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:right;">
trimmed
</th>
<th style="text-align:right;">
mad
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
range
</th>
<th style="text-align:right;">
skew
</th>
<th style="text-align:right;">
kurtosis
</th>
<th style="text-align:right;">
se
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
X1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
14527
</td>
<td style="text-align:right;">
3.310456
</td>
<td style="text-align:right;">
1.101107
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
3.349135
</td>
<td style="text-align:right;">
1.4826
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
-0.4958177
</td>
<td style="text-align:right;">
-0.7626794
</td>
<td style="text-align:right;">
0.0091357
</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-figura6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6: Tabla de descriptivos: Satisfaccion seguridad del barrio
</figcaption>
</figure>
</div>
</div>
<p>La variable de satisfacción con la seguridad del barrio “satisfaccion_seguridad_barrio_categorica”, como se observa en la <a href="#fig-figura6" class="quarto-xref">Figura&nbsp;6</a>, tiene una mediana de 4. En la escala donde el mínimo 1 corresponde a “Muy insatisfecho” y el máximo 5 corresponde a “Muy satisfecho”, podemos afirmar que el 50% de los encuestados evalúan su satisfacción con la seguridad del barrio con un puntaje de 4 o menos.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-figura7" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-figura7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Trabajofinalcorrelacional_files/figure-html/fig-figura7-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-figura7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7: Grafico de barras: Satisfaccion seguridad barrio
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="análisis-estadísticos-bivariados" class="level3">
<h3 class="anchored" data-anchor-id="análisis-estadísticos-bivariados"><strong>3.2 Análisis estadísticos bivariados</strong></h3>
<section id="correlación-entre-satisfacción-democracia-y-satisfacción-seguridad-barrio" class="level4">
<h4 class="anchored" data-anchor-id="correlación-entre-satisfacción-democracia-y-satisfacción-seguridad-barrio"><strong>3.2.1 Correlación entre satisfacción democracia y satisfacción seguridad barrio</strong></h4>
<p><strong>HA</strong>: Existe una asociación entre satisfacción de la seguridad en el barrio (“satisfaccion_seguridad_barrio_categorica”) y la satisfacción con la democracia (“satisfaccion_democracia_categorica”).&nbsp;</p>
<p><br>
<strong>H0</strong>: No existe relación entre la satisfacción con la seguridad en el barrio (“satisfaccion_seguridad_barrio_categorica”) y la satisfacción con la democracia (“satisfaccion_democracia_categorica”).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  proc_datos1$satisfaccion_democracia_categorica and proc_datos1$satisfaccion_seguridad_barrio_categorica
S = 461188334455, p-value &lt; 0.00000000000000022
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
0.09738664 </code></pre>
</div>
</div>
<p>El valor del coeficiente de Spearman obtenido es igual a&nbsp; 0,097 lo que se entiende como una relación positiva, es decir, a medida que aumenta la satisfacción con la seguridad del barrio aumenta la satisfacción con la democracia, no obstante, dentro del umbral de Cohen se considera como una correlación débil por lo tanto se explica de manera marginal la correlación. El valor p es muy bajo (0.00000000000000022), lo que permite rechazar la hipótesis nula.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-figura9" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-figura9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Trabajofinalcorrelacional_files/figure-html/fig-figura9-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-figura9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8: Asociacion entre satisfaccion con la democracia y satisfaccion con la seguridad del barrio
</figcaption>
</figure>
</div>
</div>
</div>
<p>Los hallazgos de la <a href="#fig-figura9" class="quarto-xref">Figura&nbsp;8</a> confirman lo ya se expuso la correlación de Spearman, la nube de puntos muestra una relación positiva entre las variables, con una ligera tendencia positiva a la agrupación de datos a la derecha, pero se mantiene débil (a raíz de la dispersión de los puntos en las columnas). Se sugiere que las variables operan de manera independiente.&nbsp;</p>
</section>
<section id="asociación-entre-satisfacción-democracia-y-sexo" class="level4">
<h4 class="anchored" data-anchor-id="asociación-entre-satisfacción-democracia-y-sexo"><strong>3.2.2 Asociación entre satisfacción democracia y sexo</strong></h4>
<p><strong>HA</strong>: Existe asociación entre la satisfacción&nbsp; con la democracia en Chile (“satisfaccion_democracia_categorica”) y el sexo de los encuestados (“sexo_categorica”).</p>
<p><strong>H0</strong>: no existe asosiacion entre la satisfaccion con la democracia en Chile (“satisfaccion_democracia_categorica”) y el sexo de los encuestados (“sexo_categorica”).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(proc_datos1$satisfaccion_democracia_categorica, proc_datos1$sexo_categorica)
X-squared = 16.759, df = 4, p-value = 0.002153</code></pre>
</div>
</div>
<p>Como podemos observar, se realizó la prueba de Chi cuadrado (X2) para evaluar la asociación entre las variables “satisfaccion_democracia_categorica” y “sexo_categorica”. Los resultados fueron, un valor X2 = 16.759, para 4 grados de libertad y un valor p&lt;0.01, por lo que podemos rechazar la hipótesis nula de no asociación entre las variables con un 99% de confianza. También se calculó el V de cramer para medir el tamaño del efecto, el cuál nos arrojó V = 0.0339. Este resultado nos indica que, si bien tenemos una asociación estadísticamente significativa, es una asociación muy débil entre variables.</p>
<div class="cell">
<div id="fig-figura11" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-figura11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
satisfaccion_democracia_categorica
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">
sexo_categorica
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid;  background-color:#f8f8f8;" rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
0
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
1
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
1
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2239</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3421</span>
</td>
<td style="padding:0.2cm; text-align:center;   background-color:#f8f8f8;">
<span style="color:black;">5660</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
2
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1553</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2551</span>
</td>
<td style="padding:0.2cm; text-align:center;   background-color:#f8f8f8;">
<span style="color:black;">4104</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
3
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1199</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2071</span>
</td>
<td style="padding:0.2cm; text-align:center;   background-color:#f8f8f8;">
<span style="color:black;">3270</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
4
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">498</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">677</span>
</td>
<td style="padding:0.2cm; text-align:center;   background-color:#f8f8f8;">
<span style="color:black;">1175</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
5
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">133</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">185</span>
</td>
<td style="padding:0.2cm; text-align:center;   background-color:#f8f8f8;">
<span style="color:black;">318</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; background-color:#f8f8f8; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double; background-color:#f8f8f8;">
<span style="color:black;">5622</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double; background-color:#f8f8f8;">
<span style="color:black;">8905</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double; background-color:#f8f8f8;">
<span style="color:black;">14527</span>
</td>
</tr>
</tbody></table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-figura11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;9: Tabla de contingencia entre satisfaccion con la democracia y sexo
</figcaption>
</figure>
</div>
</div>
<p>En la <a href="#fig-figura11" class="quarto-xref">Figura&nbsp;9</a> se observa que tanto hombres como mujeres se concentran principalmente en niveles bajos de satisfacción con la democracia (entre niveles 1 y 2), y no presentan mayor diferencias en sus distribuciones</p>
</section>
<section id="correlación-entre-satisfacción-democracia-y-edad" class="level4">
<h4 class="anchored" data-anchor-id="correlación-entre-satisfacción-democracia-y-edad"><strong>3.2.2 Correlación entre satisfacción democracia y edad</strong></h4>
<p><strong>HA</strong>: Existe una asociación entre la satisfacción con la democracia (“satisfaccion_democracia_categorica”) y la edad de los individuos (“edad_entrevistado_continua”).&nbsp;</p>
<p><strong>H0</strong>: No existe una asociación entre la satisfacción con la democracia (“satisfaccion_democracia_categorica”) y la edad de los individuos (“edad_entrevistado_continua”).&nbsp;</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  proc_datos1$satisfaccion_democracia_categorica and proc_datos1$edad_entrevistado_continua
S = 492049233707, p-value = 0.000008229
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
0.03698733 </code></pre>
</div>
</div>
<p>AL testear el coeficiente de Spearman, obteniendo que la correlación entre las variables obtiene un valor rho de 0,036 lo que se entiende como un valor positivo (si aumenta la edad la satisfacción con la democracia tiende a aumentar ligeramente), sin embargo es una correlacion debil segun el umbral de cohen (1988). La hipotesis nula se rechaza con 99,9% de confianza (p&lt;0,001).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-figura13" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-figura13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Trabajofinalcorrelacional_files/figure-html/fig-figura13-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-figura13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;10: Boxplot de la edad segun satisfaccion con la democracia
</figcaption>
</figure>
</div>
</div>
</div>
<p>la <a href="#fig-figura13" class="quarto-xref">Figura&nbsp;10</a> confirma lo expuesto anteriormente, los “grupos” 1, 2 y 3 poseen una mediana que se encuentra cercana a los 50 años, mientras que los “grupos” 4 y 5 tienen unas medianas notablemente mayores a los grupos anteriores&nbsp; y las cajas se encuentran más altas en lo que respecta a la satisfacción con la democracia, confirmando la relación positiva entre más edad más satisfacción con la democracia.</p>
</section>
</section>
</section>
<section id="conclusiones" class="level2">
<h2 class="anchored" data-anchor-id="conclusiones"><strong>4 Conclusiones</strong></h2>
<p>En este estudio basado en la correlación entre la sensación subjetiva de satisfacción con la democracia en base a las variables independientes de edad, sexo y satisfacción con la seguridad barrial de la base de datos de ELSOC 2016-2023. La idea central del estudio era analizar y comprender si existe una correlación estadísticamente significativa entre la edad de los chilenos, su sexo y la satisfacción con la seguridad percibida en sus barrios con la satisfacción con el proyecto democratico del país y sus 35 años de tortuoso camino.&nbsp;</p>
<p>se obtuvieron los siguientes resultados:&nbsp;</p>
<ul>
<li><p>Las correlaciones entre los cruces de las variables edad/sexo/satisfacción con la seguridad barrial con la variable satisfacción con la democracia arrojan todos resultados positivos.</p></li>
<li><p>Si bien los resultados de los cruces entre las variables independientes con la variable dependiente son positivos, resultan todos sumamente débiles, no permitiendo generar análisis de dependencia real entre una variable y otra (explicaciones marginales).&nbsp;</p></li>
</ul>
<p>&nbsp;Las limitaciones del estudio se entienden a través de la cantidad de variables cruzadas (4) y el factor de la extensión temporal de la base de datos ELSOC, en el sentido de que si bien un estudio longitudinal como este sirve para comprender la evolución de las opiniones, quizás sería más funcional o con resultados estadísticamente más significativos un mapeo transversal.&nbsp;</p>
<p>Se recomienda para futuras investigaciones con esta base de datos crear dimensiones que se compongan de variables relacionadas y de esa forma generar cruces con mayor peso y envergadura de datos.&nbsp;</p>
</section>
<section id="bibliografía" class="level2">
<h2 class="anchored" data-anchor-id="bibliografía"><strong>5 Bibliografía</strong></h2>
<p>Alvarado-Mendoza, A. (2024). Impacto de la inseguridad y la participación ciudadana sobre la satisfacción con la democracia. Revista Científica General José María Córdova, 22(46), 313–337. <a href="https://doi.org/10.21830/19006586.1302" class="uri">https://doi.org/10.21830/19006586.1302</a></p>
<p>Avendaño, O. (2019). ESTALLIDO SOCIAL EN CHILE: LOS DILEMAS POLÍTICOS DESDE OCTUBRE DEL 2019. Política. Revista De Ciencia Política, 57(2), 105–119. <a href="https://doi.org/10.5354/0719-5338.2019.61558" class="uri">https://doi.org/10.5354/0719-5338.2019.61558</a>&nbsp;&nbsp;</p>
<p>Bargsted, Matías, Somma, Nicolás M., &amp; Muñoz-Rojas, Benjamín. (2019). Participación electoral en Chile. Una aproximación de edad, período y cohorte. Revista de ciencia política (Santiago), 39(1), 75-98. <a href="https://dx.doi.org/10.4067/S0718-090X2019000100075" class="uri">https://dx.doi.org/10.4067/S0718-090X2019000100075</a>&nbsp;</p>
<p>BBC. (2025). Chile está extremadamente atemorizado. Pero está lejos de ser el país con el mayor problema por crimen y violencia. <a href="https://www.bbc.com/mundo/articles/cql9766ykw5o" class="uri">https://www.bbc.com/mundo/articles/cql9766ykw5o</a>&nbsp;</p>
<p>Hansen MA, Goenaga A. Gender and Democratic Attitudes: Do Women and Men Prioritize Different Democratic Institutions? Politics &amp; Gender. 2021;17(1):23-52. doi:10.1017/S1743923X19000473&nbsp;&nbsp;</p>
<p>MEPOP. (2025). El auge de la ultraderecha y la encrucijada de la derecha convencional en Chile ad portas de las elecciones de 2025. <a href="https://mepop.cl/el-auge-de-la-ultraderecha-y-la-encrucijada-de-la-derecha-convencional-en-chile-ad-portas-de-las-elecciones-de-2025" class="uri">https://mepop.cl/el-auge-de-la-ultraderecha-y-la-encrucijada-de-la-derecha-convencional-en-chile-ad-portas-de-las-elecciones-de-2025</a>&nbsp;</p>
<p>Morales Quiroga, Mauricio. (2020). ESTALLIDO SOCIAL EN CHILE 2019: PARTICIPACIÓN, REPRESENTACIÓN, CONFIANZA INSTITUCIONAL Y ESCÁNDALOS PÚBLICOS. Análisis Político, 33(98), 3-25. <a href="https://doi.org/10.15446/anpol.v33n98.89407" class="uri">https://doi.org/10.15446/anpol.v33n98.89407</a>&nbsp;</p>
<p>Natalucci, A., Fernández Mouján, L., &amp; Kelmeszes, A. (2025). La democracia acechada. Protesta y política en Argentina, Brasil y Chile (2011-2019). Revista De La Red Intercátedras De Historia De América Latina Contemporánea, 22, 26-53. <a href="https://revistas.unc.edu.ar/index.php/RIHALC/article/view/48965" class="uri">https://revistas.unc.edu.ar/index.php/RIHALC/article/view/48965</a>&nbsp;</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>