<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tamara Roa">
<meta name="author" content="Gabriela Acevedo">
<meta name="author" content="Fernanda Catalina Becerra">
<meta name="author" content="Sofia Altamirano">
<meta name="author" content="Javiera Morales">
<meta name="author" content="José Tomás Torres">

<title>Etnia, ingresos familiares y género en la incidencia de orientación política en el territorio chileno.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Reporte_files/libs/clipboard/clipboard.min.js"></script>
<script src="Reporte_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Reporte_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Reporte_files/libs/quarto-html/popper.min.js"></script>
<script src="Reporte_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Reporte_files/libs/quarto-html/anchor.min.js"></script>
<link href="Reporte_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Reporte_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Reporte_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Reporte_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Reporte_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="Reporte_files/libs/table1-1.0/table1_defaults.css" rel="stylesheet">

<script src="Reporte_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="Reporte_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

<link href="Reporte_files/libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">

<script src="Reporte_files/libs/pagedtable-1.1/js/pagedtable.js"></script>

<style>
  body {
    text-align: justify;
  }
</style>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Etnia, ingresos familiares y género en la incidencia de orientación política en el territorio chileno.</h1>
<p class="subtitle lead">Estadística Correlacional 2025, Carrera de Sociología, Universidad de Chile</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Tamara Roa </p>
             <p>Gabriela Acevedo </p>
             <p>Fernanda Catalina Becerra </p>
             <p>Sofia Altamirano </p>
             <p>Javiera Morales </p>
             <p>José Tomás Torres </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">23 de noviembre de 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introducción" class="level1">
<h1>Introducción</h1>
<p>La orientación política es objeto de frecuente estudio y análisis en las ciencias sociales, debido a que la opinión de los ciudadanos respecto de la democracia y su posicionamiento ideológico tiene un valor central para comprender el comportamiento electoral, el apoyo a políticas públicas y las dinámicas de representación. En este sentido, entendemos la orientación política como la autoubicación ideológica en una escala de izquierda-derecha, lo que permite identificar patrones de apoyo o rechazo a determinadas agendas políticas (CEPAL, 2016). En este trabajo analizamos esta variable utilizando como fuente la encuesta Latin American Public Opinion Project (LAPOP) del año 2019 y su relación con tres características sociodemográficas: género, ingresos familiares y etnicidad.</p>
<p>Estudios recientes muestran que las desigualdades económicas, de género y etnicidad no solo afectan las oportunidades materiales de los individuos, sino también su percepción de justicia distributiva, su participación política y su identificación ideológica (World Bank, 2021; Inter-American Development Bank, 2018). En el caso de género, investigaciones sobre participación política evidencian que las brechas no se explican únicamente por roles culturales, sino también por la interacción entre género y desigualdad socioeconómica, generando experiencias diferenciales frente al sistema político (Pérez Verdugo, 2021). Asimismo, la literatura sobre desigualdad económica señala que esta puede generar polarización y moldear las preferencias ideológicas de los ciudadanos (Stewart, Plotkin &amp; McCarty, 2021).</p>
<p>Consideramos también relevante incorporar la dimensión étnica. Diversos estudios muestran que las poblaciones indígenas y afrodescendientes en América Latina experimentan condiciones históricas de desventaja social y económica, lo que influye en su relación con el Estado y en sus actitudes políticas (CEPAL, 2016; Telles, Wade &amp; Flores, 2022). Estas desigualdades, además, se entrecruzan con las brechas de género e ingresos, lo que puede repercutir en orientaciones políticas diferenciadas.</p>
<p>El presente trabajo tiene como objetivo examinar si las características sociodemográficas, género, ingresos familiares y etnicidad se relacionan significativamente con la orientación política declarada por los encuestados en la encuesta LAPOP 2019. A partir de la literatura revisada, proponemos las siguientes hipótesis: H₁: Existe una diferencia significativa en la orientación política (l1) según el género (sex). H2: Existe una diferencia significativa entre orientación política y etnicidad. H3: Existe una diferencia significativa en el género e ingresos familiares.. Estas hipótesis serán contrastadas mediante análisis estadísticos descriptivos y bivariados.</p>
</section>
<section id="metodología" class="level1">
<h1>Metodología</h1>
<section id="datos" class="level2">
<h2 class="anchored" data-anchor-id="datos">Datos</h2>
<p>El presente estudio se enmarca dentro de una investigación cuantitativa, adoptando un diseño no experimental y de corte transversal. Este enfoque metodológico es idóneo para analizar la relación, la distribución y la caracterización de las variables sociodemográficas (Género, Etnicidad, Ingresos Familiares) en función de la autoubicación ideológica (Orientación Política) en un momento específico, sin manipular las variables ni establecer relaciones causales directas a lo largo del tiempo.</p>
<p>El objetivo principal de esta sección es detallar el proceso de recopilación, el procesamiento y la técnicas de análisis de los datos que permiten abortar los objetivos de la investigación y fundamentar los resultados presentados en el reporte.</p>
<p>Los datos utilizados para este análisis son de naturaleza secundaria, provenientes de una fuente de información de carácter masivo (Encuesta). Para el presente estudio, se trabajó con un subconjunto de datos que incluyó un total de 1.137 casos válidos (N=1.137). Este tamaño muestral corresponde a aquellas observaciones que contaron con datos completos para la totalidad de las variables consideradas, asegurando la consistencia y validez en los análisis estadísticos correlacionales y descriptivos.</p>
</section>
<section id="variables" class="level2">
<h2 class="anchored" data-anchor-id="variables">Variables</h2>
<p>Se consideraron cuatro variables clave para la investigación, una de las cuales actúa como variables dependiente; la Orientación Política, y tres como variables independientes de carácter sociodemográfico: Género, Ingresos Familiares y Eticidad. La operacionalización y la distribución de frecuencias de cada una se detalla a continuación.</p>
<p><strong>Orientación política (Variable dependiente):<br>
</strong>Esta variable fue medida en una escala ordinal que se extiende desde 1 (Extrema Izquierda) hasta 10 (Extrema Derecha). La distribución de frecuencias de esta variable muestra la tendencia ideológica de la muestra, siendo fundamental para los análisis posteriores.</p>
<p><em>Tabla de frecuencia orientación política</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_df</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(sjmisc<span class="sc">::</span><span class="fu">frq</span>(proc_LAPOP<span class="sc">$</span>Orientación_política))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">variable</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">val</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">label</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">frq</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">raw.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">cum.prc</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">106</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">9.32</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">9.32</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">54</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4.75</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">14.07</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">116</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">10.20</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">24.27</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">126</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">11.08</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">35.36</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">360</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">31.66</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">67.02</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">129</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">11.35</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">78.36</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">87</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.65</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">86.02</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">8</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">64</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5.63</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">91.64</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">9</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">20</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.76</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">93.40</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">10</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">75</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6.60</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">100.00</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La distribución de la orientación política revela una clara concentración de la muestra en la posición central o moderada del espectro ideológico. La categoría 5 agrupa a la mayor cantidad de encuestados, con 360 casos, lo que representa el 31,66% del total. Si se agrupan las categorías de 1 a 4 (Izquierda) se obtiene un 35,36% de la muestra, mientras que las categorías de 6 a 10 (Derecha) suman un 32,99% ( 11.35 + 7,65 + 5,63 + 1,76 + 6,6). Este patrón sugiere una distribución tripartita relativamente equilibrada, pero con un peso significativo en el centro.</p>
<p><strong>Género:<br>
</strong>El género, en el marco de este trabajo y basandonos en la base de datos utilizada, se define como una variable nominal dicotómica.</p>
<p><em>Tabla de frecuencia de Género</em></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">variable</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">val</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">label</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">frq</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">raw.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">cum.prc</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">579</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">50.92</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">50.92</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">558</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">49.08</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">100.00</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La muestra se encuentra casi perfectamente balanceada en términos de Género. La categoría 1 (Femenino) representa el 50,92% (N=579) y la categoría 2 (Masculino) representa el 49.08% (N=558). Este equilibrio minimiza el riesgo de sesgo en los análisis que involucren esta variable.</p>
<p><strong>Ingresos Familiares:</strong><br>
Los Ingresos Familiares representan una variable ordinal con un amplio rango, desde 0 hasta 16, lo que permite capturar una diversidad de situaciones socioeconómicas.</p>
<p><em>Tabla de frecuencia de Ingresos familiares</em></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">variable</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">val</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">label</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">frq</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">raw.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">cum.prc</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">8</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.70</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.70</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">40</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3.52</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4.22</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">53</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4.66</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">8.88</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">71</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6.24</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">15.13</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">43</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3.78</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">18.91</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">100</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">8.80</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">27.70</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">81</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.12</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">34.83</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">8</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">59</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5.19</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">40.02</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">9</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">93</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">8.18</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">48.20</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">10</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">68</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5.98</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">54.18</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">11</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">76</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6.68</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">60.86</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">12</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">71</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6.24</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">67.11</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">13</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">79</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6.95</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">74.05</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">14</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">91</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">8.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">82.06</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">15</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">84</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.39</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">89.45</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">16</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">52</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4.57</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">94.02</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">17</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">68</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5.98</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">100.00</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La distribución de los Ingresos Familiares es amplia y dispersa, sin una clara moda en los extremos. Las categorías con mayor frecuencia son 5(N=100, 8,8%), 8 (N=93, 8,18%), y 13 (N=91, 8%), indicando que la variabilidad es favorable para detectar posibles diferencias en la Orientación política asociadas al nivel socioeconómico.</p>
<p><strong>Etnicidad:<br>
</strong>La variable original de Etnicidad, medida en una escala nominal en múltiples categorías, fue recodificada para simplificar el análisis y permitir su uso en modelos estadísticos con mayor poder interpretativo. La distribución de la variable original se presenta a continuación.</p>
<p><em>Tabla de frecuencia de Etnicidad</em></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">variable</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">val</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">label</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">frq</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">raw.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">cum.prc</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">536</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">47.14</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">47.14</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">447</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">39.31</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">86.46</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">85</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.48</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">93.93</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">15</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.32</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">95.25</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">30</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.64</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">97.89</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">24</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.11</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">100.00</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Para crear un variable dicotómica nominal, se procedió a agrupar las categorías originales de la siguiente manera:</p>
<ul>
<li><p>Categoría “No minoría”: Se mantuvo la categoría original con la mayor frecuencia (categoría 1), asumiéndola como el grupo de referencia o mayoritario.</p></li>
<li><p>Categoría “Minoría”: Se agruparon el resto de las categorías (2, 3, 4, 5 y 7) en una única nueva categoría que representa a los grupos étnicos minoritarios.</p></li>
</ul>
<p><em>Tabla de frecuencia Etnicidad transformada</em></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">variable</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">val</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">label</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">frq</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">raw.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">cum.prc</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Minoría</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">130</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">11.43</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">11.68</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">No minoría</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><none></none></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">983</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">86.46</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">100.00</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">x</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">24</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">2.11</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La creación de una variable dicotómica busca simplificar la complejidad de la variable original y poner foco en la dicotomía entre el grupo mayoritario y el conjunto de minorías. Esto es especialmente útil en los modelos de regresión, donde el efecto de pertenecer a una minoría étnica, en comparación con el grupo de referencia, puede ser evaluado de forma directa y robusta. La nueva distribución indica que la muestra se compone de un 47.14% de individuos en la categoría No Minoría y un 52,86% en la categoría Minoría, logrando una distribución que permite una comparación estadísticamente significativa entre ambos grupos.</p>
</section>
<section id="métodos" class="level2">
<h2 class="anchored" data-anchor-id="métodos">Métodos</h2>
<p>Para cumplir con los objetivos del estudio, el análisis de datos se realizó en dos etapas principales:</p>
<p><strong>Estadística Descriptiva:</strong> En esta primera etapa, se emplearon medidas de frecuencia absoluta (N) y frecuencia relativa (porcentajes válidos, valid.prc) para describir y caracterizar la muestra en cada una de las variables. Esto incluyó la presentación de las tablas de frecuencia detalladas previamente, que permitieron identificar la distribución, la moda y el nivel de dispersión en las variables, siendo esencial para comprender la composición de la muestra en términos de orientación política, género, ingresos familiares y etnicidad.</p>
<p><strong>Estadística correlacional e inferencial:</strong> La segunda etapa se centró en la exploración y la medición de la asociación entre las variables sociodemográficas (independientes) y la orientación política (dependiente). Dado que la variable dependiente es ordinal y las variables independientes son una mezcla de nominales (dicotómicas) y ordinales, las técnicas de análisis se basaron en los siguientes métodos:</p>
<p><strong>Tablas de contingencia y Prueba chi (Chi-cuadrado):</strong> Se utilizaron para examinar la asociación entre las variables nominales/dicotómicas (Género, Etnicidad transformada) y la Orientación Política (o una versión recodificada de esta). El chi^2 permite determinar si existe una dependencia estadística significativa entre las distribuciones de las variables.</p>
<p><strong>Análisis de Correlación:</strong> Se empleó la Correlación de Spearman (rho) para medir el grado y la dirección de la asociación monótona entre las variables ordinales Orientación Política e Ingresos Familiares), dado que es la medida apropiada para variables que no cumplen el supuesto de normalidad y son de escala ordinal.</p>
<p><strong>Modelos de Regresión (Regresión Logística u Ordinal):</strong> Para estimar el peso predictivo y la influencia independiente de las variables sociodemográficas en la Orientación Política, se pudo emplear un Modelo de Regresión Logística Ordinal. Esta técnica es ideal para variables dependientes ordinales, permitiendo interpretar la probabilidad de ubicarse en niveles superiores de la escala de orientación política (por ejemplo, hacia la derecha) en función de las categorías de Género, Etnicidad e Ingresos Familiares, controlando el efecto de todas las variables simultáneamente.</p>
<p>El umbral de significancia estadística se estableció en 0,05 para todas las pruebas inferenciales, de acuerdo con las prácticas estándar en las ciencias sociales.</p>
</section>
</section>
<section id="análisis" class="level1">
<h1>Análisis</h1>
<section id="análisis-descriptivo" class="level2">
<h2 class="anchored" data-anchor-id="análisis-descriptivo">Análisis descriptivo</h2>
<p><strong>Estadísticos Descriptivos</strong></p>
<div class="cell">
<div class="cell-output-display">
<div class="Rtable1">
<table class="Rtable1 caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabla descriptiva de las variables del estudio</caption>
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th class="rowlabel firstrow lastrow" data-quarto-table-cell-role="th"></th>
<th class="firstrow lastrow" data-quarto-table-cell-role="th"><span class="stratlabel">Overall<br>
<span class="stratn">(N=1137)</span></span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowlabel firstrow"><span class="varlabel">Género</span></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Hombre</td>
<td>579 (50.9%)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Mujer</td>
<td class="lastrow">558 (49.1%)</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow"><span class="varlabel">Orientación_política</span></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Mean (SD)</td>
<td>5.01 (2.30)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">5.00 [1.00, 10.0]</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow"><span class="varlabel">Etnicidad_dicot</span></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Minoría</td>
<td>154 (13.5%)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">No Minoría</td>
<td class="lastrow">983 (86.5%)</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow"><span class="varlabel">Ingresos_familiares</span></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Mean (SD)</td>
<td>9.80 (4.39)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">10.0 [1.00, 17.0]</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">vars</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">trimmed</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mad</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">range</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">skew</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">kurtosis</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Orientación_política</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1137</td>
<td style="text-align: right;">5.005277</td>
<td style="text-align: right;">2.3020139</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4.936334</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.2751715</td>
<td style="text-align: right;">-0.1151941</td>
<td style="text-align: right;">0.0682697</td>
</tr>
<tr class="even">
<td style="text-align: left;">Género*</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1137</td>
<td style="text-align: right;">1.490765</td>
<td style="text-align: right;">0.5001347</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.488474</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0368969</td>
<td style="text-align: right;">-2.0003957</td>
<td style="text-align: right;">0.0148322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Etnicidad</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1137</td>
<td style="text-align: right;">1.793316</td>
<td style="text-align: right;">1.0641523</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.580681</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2.0601167</td>
<td style="text-align: right;">4.8438609</td>
<td style="text-align: right;">0.0315590</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ingresos familiares</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1137</td>
<td style="text-align: right;">9.796834</td>
<td style="text-align: right;">4.3884921</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">9.844127</td>
<td style="text-align: right;">5.9304</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">-0.0765151</td>
<td style="text-align: right;">-1.1069291</td>
<td style="text-align: right;">0.1301473</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En estas tablas se observan los principales estadísticos descriptivos de las 3 variables categóricas (Ingresos familiares, Género y Etnicidad) y la variable cuantitativa (Orientación política) en los 1137 casos revisados. En Orientación política se observa un promedio de 5,005 y la mediana 5, lo que indica que la muestra está casi perfectamente centrada, con una desviación estándar de 2,30, el Error Estándar, es de 0,06, lo cual es muy bajo e indica que esta estimación central es precisa y representativa de la población. En Género, la cual es una variable dicotómica, es decir, solo tiene dos posibles valores, (1= hombre, 2= mujer), la media está en 1,49 lo que indica que la muestra está casi perfectamente equilibrada. Etnicidad es una variable categórica con 6 grupos distintos, la media es de 1,79 y la mediana 2, lo que sugiere que los valores más bajos (1 y 2) están más representados, así lo indica la Asimetría= 2,06 , lo cual señala que las categorías 1 y 2 concentran la gran mayoría de la muestra, el Error Estándar= 0,03 es pequeño en relación a la Desviación estándar= 4,39, lo que valida la precisión de la media de ingresos reportada. Por último en relación a los Ingresos Familiares, está en una escala del 0 al 16, es decir, 16 posibles valores, donde el promedio es de 8,80 y una mediana de 8,84, es decir, casi idénticas. El bajo Error estándar= 0.13 indica una alta precisión de la estimación del promedio.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El histograma anterior representa la frecuencia empírica de cada evento, este revela una distribución con una marcada tendencia central, la categoría con la frecuencia más alta se encuentra en el centro, específicamente en el valor 5, es decir, actúa como Moda de la distribución. La distribución es aproximadamente simétrica y muestra una participación significativa en los extremos de la escala, es decir, en la Extrema Izquierda (1.0) y la Extrema Derecha (10.0). Este patrón sugiere que, aunque la mayoría de los encuestados se sitúa en el centro del espectro, existe también un bloque de votantes ideológicamente polarizados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En este histograma de frecuencias de Ingresos Familiares, representado por gráficos de barras. El gráfico confirma la Asimetría señalada en la primera tabla de -0,08, pues las frecuencias en la mitad izquierda (0-8) son generalmente similares a las de la mitad derecha (9-16). Respecto a las medidas de tendencia central la distribución es multimodal (tiene varios picos), con una frecuencia máxima alrededor del valor 5 (casi 100 casos). Sin embargo, hay otros picos significativos alrededor de 3 8 13 y 14 La simetría general confirma que la Media (8.80) y la Mediana (8.84) son buenos indicadores del centro de la riqueza en la muestra. La distribución se extiende de manera uniforme en torno a este valor, lo que indica una amplia heterogeneidad en los niveles de riqueza de los hogares encuestados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Este gráfico de barras ilustra la distribución de la muestra entre las dos categorías de la variable Género, codificadas como: 1=hombre y 2=mujer. Respecto a la distribución el gráfico muestra que la frecuencia de las categorías es casi idéntica, esto confirma la información que obtuvimos en la tabla descriptiva respecto a la media=1,49.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Respecto a la etnicidad es importante mencionar que esta variable fue recodificada, ya que la variable original incluía 6 categorías y fue convertida en una variable dicotómica. A modo de análisis la categoría “No minoría” es la dominante con 970 casos aproximadamente o un 85% de la muestra. Este fuerte sesgo en la distribución de la etnicidad es un factor clave que debe ser considerado al interpretar los resultados de la relación entre Etnicidad y Orientación Política.</p>
</section>
<section id="análisis-estadístico-bivariado" class="level2">
<h2 class="anchored" data-anchor-id="análisis-estadístico-bivariado">Análisis estadístico bivariado</h2>
<p><strong>Tabla 1: Estadísticos según género</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tabla 1: Estadísticos según género</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Género</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Media</th>
<th style="text-align: right;">Mediana</th>
<th style="text-align: right;">Desv. Estándar</th>
<th style="text-align: right;">Mínimo</th>
<th style="text-align: right;">Máximo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hombre</td>
<td style="text-align: right;">579</td>
<td style="text-align: right;">4.95</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2.31</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mujer</td>
<td style="text-align: right;">558</td>
<td style="text-align: right;">5.06</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2.29</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Tabla 2: Prueba T de Student y tamaño de efecto (H1)</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tabla: Prueba T y tamaño de efecto según Género</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Estadístico</th>
<th style="text-align: left;">Resultado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">t (Student)</td>
<td style="text-align: left;">-0.77</td>
</tr>
<tr class="even">
<td style="text-align: left;">gl</td>
<td style="text-align: left;">1134</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p-valor</td>
<td style="text-align: left;">0.4388</td>
</tr>
<tr class="even">
<td style="text-align: left;">Media (H vs M)</td>
<td style="text-align: left;">4.95 vs 5.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diferencia significativa</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cohen’s d</td>
<td style="text-align: left;">-0.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Magnitud del efecto</td>
<td style="text-align: left;">Muy pequeño</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Tabla 3: Estadísticos según Etnicidad Dicotómica</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tabla 3: Estadísticos según Etnicidad Dicotómica</caption>
<thead>
<tr class="header">
<th style="text-align: right;">n</th>
<th style="text-align: left;">Estadística</th>
<th style="text-align: right;">Minoría (n=154)</th>
<th style="text-align: right;">No minoría (n=983)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">154</td>
<td style="text-align: left;">Media</td>
<td style="text-align: right;">4.94</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">154</td>
<td style="text-align: left;">Mediana</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: right;">154</td>
<td style="text-align: left;">Desv. Estándar</td>
<td style="text-align: right;">2.32</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">154</td>
<td style="text-align: left;">Mínimo</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: right;">154</td>
<td style="text-align: left;">Máximo</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">983</td>
<td style="text-align: left;">Media</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.02</td>
</tr>
<tr class="odd">
<td style="text-align: right;">983</td>
<td style="text-align: left;">Mediana</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">983</td>
<td style="text-align: left;">Desv. Estándar</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.30</td>
</tr>
<tr class="odd">
<td style="text-align: right;">983</td>
<td style="text-align: left;">Mínimo</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">983</td>
<td style="text-align: left;">Máximo</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">10.00</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Tabla 4: Prueba T de Student y tamaño de efecto (H2)</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tabla: Prueba T y tamaño de efecto según Etnicidad Dicotómica</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Estadístico</th>
<th style="text-align: left;">Resultado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">t (Student)</td>
<td style="text-align: left;">-0.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">gl</td>
<td style="text-align: left;">203</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p-valor</td>
<td style="text-align: left;">0.7144</td>
</tr>
<tr class="even">
<td style="text-align: left;">Media (Minoría vs No Minoría)</td>
<td style="text-align: left;">4.94 vs 5.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diferencia significativa</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cohen’s d</td>
<td style="text-align: left;">-0.03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Magnitud del efecto</td>
<td style="text-align: left;">Muy pequeño</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La tabla 3 presenta los estadísticos descriptivos de la orientación política según etnicidad dicotómica, mostrando que las medias entre personas pertenecientes a grupo Minoría 4.94 y no minoria 5.032 son muy similares, lo que anticipa la ausencia de diferencias relevantes entre ambos grupos, ya que ambos se centran en el centro de la escala ideológica. Esta impresión descriptiva confirma que que los resultados de la tabla 4, donde la prueba t de student arroja valor p de 0.712, muy por encima del nivel de significancia de 0.05, indicando que no existen diferencias estadísticamente significativas en la autoubicación ideológica según etnicidad. Por lo que, el tamaño del efecto es nulo, con un Cohen de 0.03, lo que refuerza que cualquier diferencia observada en los promedios carece de relevancia sustantiva. Finalmente, se muestra que la etnicidad no influye en la orientación política dentro de esta muestra, entonces se rechaza la H2.</p>
<p><strong>Tabla 5: Contingencia Género e Ingresos</strong></p>
<div class="cell">
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">Tabla 5: Contingencia Género e Ingresos</caption>
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Género</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="17">Ingresos_familiares</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">1</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">2</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">3</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">4</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">5</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">6</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">7</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">8</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">9</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">10</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">11</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">12</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">13</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">14</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">15</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">16</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">17</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Hombre</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">4</span><br><span style="color:#333399;">0.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">13</span><br><span style="color:#333399;">2.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">22</span><br><span style="color:#333399;">3.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">28</span><br><span style="color:#333399;">4.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">28</span><br><span style="color:#333399;">4.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">45</span><br><span style="color:#333399;">7.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">35</span><br><span style="color:#333399;">6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">22</span><br><span style="color:#333399;">3.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">47</span><br><span style="color:#333399;">8.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">41</span><br><span style="color:#333399;">7.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">33</span><br><span style="color:#333399;">5.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">34</span><br><span style="color:#333399;">5.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">48</span><br><span style="color:#333399;">8.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">49</span><br><span style="color:#333399;">8.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">52</span><br><span style="color:#333399;">9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">32</span><br><span style="color:#333399;">5.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">46</span><br><span style="color:#333399;">7.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">579</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Mujer</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">4</span><br><span style="color:#333399;">0.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">27</span><br><span style="color:#333399;">4.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">31</span><br><span style="color:#333399;">5.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">43</span><br><span style="color:#333399;">7.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">15</span><br><span style="color:#333399;">2.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">55</span><br><span style="color:#333399;">9.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">46</span><br><span style="color:#333399;">8.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">37</span><br><span style="color:#333399;">6.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">46</span><br><span style="color:#333399;">8.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">27</span><br><span style="color:#333399;">4.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">43</span><br><span style="color:#333399;">7.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">37</span><br><span style="color:#333399;">6.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">31</span><br><span style="color:#333399;">5.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">42</span><br><span style="color:#333399;">7.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">32</span><br><span style="color:#333399;">5.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">20</span><br><span style="color:#333399;">3.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">22</span><br><span style="color:#333399;">3.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">558</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">8</span><br><span style="color:#333399;">0.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">40</span><br><span style="color:#333399;">3.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">53</span><br><span style="color:#333399;">4.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">71</span><br><span style="color:#333399;">6.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">43</span><br><span style="color:#333399;">3.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">100</span><br><span style="color:#333399;">8.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">81</span><br><span style="color:#333399;">7.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">59</span><br><span style="color:#333399;">5.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">93</span><br><span style="color:#333399;">8.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">68</span><br><span style="color:#333399;">6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">76</span><br><span style="color:#333399;">6.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">71</span><br><span style="color:#333399;">6.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">79</span><br><span style="color:#333399;">6.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">91</span><br><span style="color:#333399;">8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">84</span><br><span style="color:#333399;">7.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">52</span><br><span style="color:#333399;">4.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">68</span><br><span style="color:#333399;">6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1137</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="19">χ<sup>2</sup>=43.996 · df=16 · Cramer's V=0.197 · Fisher's p=0.000</td> 
</tr>
 
</tbody></table>
</div>
</div>
<p>Esta tabla de contingencia o tabla cruzada permite contrastar la h3 de diferencia entre género e ingresos familiares. Esta tabla muestra las frecuencias por encima de los porcentajes para cada nivel de ingresos de hombres (n=579) y mujeres (n=558). La tabla revela que los patrones de porcentajes no son tan distintos, ambos grupos tienen una alta concentración en el rango medio (alrededor de 5 a 9) y en el rango alto (12 a 16). Esto sugiere que no existe una diferencia marcada en la distribución de la riqueza relativa por género, aunque sí se observan diferencias marcadas en los extremos: Las Mujeres muestran una concentración significativamente mayor que los Hombres en los niveles más bajos de riqueza relativa (especialmente en los niveles 1, 2 y 3), mientras que los Hombres muestran una concentración de casos mayor en los niveles más altos del índice (especialmente en los niveles 14 y 16). Estos resultados sugieren que existe una brecha de riqueza relativa entre géneros, donde las mujeres están sobrerrepresentadas en la parte inferior de la distribución y los hombres en la parte superior.</p>
<p><strong>Tabla 6: Chi cuadrado y medidas de asociación (H3)</strong></p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(tabla): Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tabla 6: Chi-cuadrado y medidas de asociación (H₃)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Estadístico</th>
<th style="text-align: left;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chi-cuadrado (Pearson)</td>
<td style="text-align: left;">43.996</td>
</tr>
<tr class="even">
<td style="text-align: left;">gl</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p-valor</td>
<td style="text-align: left;">0.0002</td>
</tr>
<tr class="even">
<td style="text-align: left;">Contingency Coefficient</td>
<td style="text-align: left;">0.193</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cramer’s V</td>
<td style="text-align: left;">0.197</td>
</tr>
<tr class="even">
<td style="text-align: left;">Interpretación</td>
<td style="text-align: left;">Asociación débil , pero significativa</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La tabla 6 muestra que la prueba de Chi cuadrado para controlar la hipótesis 3. Existe una diferencia significativa entre género e ingresos familiares, el resultado principal es que la asociación estadísticamente significativamente, ya que el valor p es 0.00019, siendo considerablemente menor que el umbral de alpha=0.05, lo que nos lleva a ampliar la hipótesis de que existe una dependencia estadística entre la distribución de género y los ingresos familiares. Sin embargo, la magnitud de esta asociación es débil, como lo indican las medidas de tamaño del efecto. En resumen, el género está relacionado de manera no aleatoria con la distribución de los ingresos familiares en la muestra, pero el género por sí mismo sólo explica una pequeña parte de la variabilidad total observada en los ingresos.</p>
</section>
</section>
<section id="conclusiones" class="level1">
<h1>Conclusiones</h1>
<p>El análisis bivariado reveló que la Orientación política promedio es independiente del Género y la Etnicidad. Las pruebas T de Student indicaron que las diferencias mínimas observadas en las medias políticas entre hombres y mujeres (p=0.43) y entre minorías y no minorías (p=0.712) no son estadísticamente significativas. En ambos casos, el tamaño del efecto (Cohen’s d) fue trivial, sugiriendo que estos factores sociodemográficos no son predictores relevantes de la posición ideológica central en la población estudiada. En contraste, la hipótesis sobre la Riqueza Relativa (Índice WEALTH) fue la única confirmada. La prueba Chi-cuadrado arrojó una asociación estadísticamente significativa entre Género e Ingresos Familiares (p=0.00019). Aunque el tamaño del efecto (Cramer’s V=0.197) es débil, este hallazgo confirma la existencia de una brecha de riqueza, donde los hombres se concentran desproporcionadamente en los niveles más altos y las mujeres en los niveles más bajos de la distribución de riqueza relativa. Una limitación clave del estudio fue la baja variabilidad de la Orientación Política en las medias grupales, lo que dificulta la detección de diferencias. Además, la recodificación dicotómica de Etnicidad y el fuerte desequilibrio entre el grupo Minoría y No Minoría pudo haber afectado el poder estadístico.</p>
</section>
<section id="bibliografía" class="level1">
<h1>Bibliografía</h1>
<p>CEPAL. (2016). La matriz de la desigualdad social en América Latina. Comisión Económica para América Latina y el Caribe. https://repositorio.cepal.org/server/api/core/bitstreams/c52907b3-a3dc-4866-8f4c-c19491c2b83a/content</p>
<p>Inter-American Development Bank. (2018). New Century, Old Disparities: Gender and Ethnic Earnings Gaps in Latin America and the Caribbean. BID. https://publications.iadb.org/publications/english/document/New-century-Old-Disparities-Gender-and-Ethnic-Earnings-Gaps-in-Latin-America-and-The-Caribbean.pdf</p>
<p>Pérez Verdugo, C. (2021). Género y participación política en Chile [Memoria de título, Universidad de Chile]. Repositorio UChile. https://repositorio.uchile.cl/bitstream/handle/2250/182157/Constanza%20P%C3%A9rez%20Verdugo.pdf?sequence=1&amp;isAllowed=y</p>
<p>Stewart, A. J., Plotkin, J. B., &amp; McCarty, N. (2021). Inequality, identity, and partisanship: How redistribution can stem the tide of mass polarization. Proceedings of the National Academy of Sciences. https://arxiv.org/pdf/2103.14619.pdf</p>
<p>Telles, E., Wade, P., &amp; Flores, R. (2022). Racial and ethnic inequality in Latin America. LSE Latin America and Caribbean Centre. https://eprints.lse.ac.uk/120677/1/LACIR_WP_113.pdf</p>
<p>World Bank. (2021). Are fairness perceptions shaped by income inequality? Evidence from Latin America. World Bank Group. https://thedocs.worldbank.org/en/doc/050334bac09c2058754559a9915d7a16-0050022021/original/Are-Fairness-Perceptions-Shaped-by-Income-Inequality.pdf</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>