<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Fernanda Barrios">
<meta name="author" content="Matilda Fuenzalida">
<meta name="author" content="Ambar Urbina">
<meta name="author" content="Ignacio Muñoz">
<meta name="author" content="Josefa Ubilla">

<title>Trabajo final correlacional Satisfacción con la democracia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Reporte_final_files/libs/clipboard/clipboard.min.js"></script>
<script src="Reporte_final_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Reporte_final_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Reporte_final_files/libs/quarto-html/popper.min.js"></script>
<script src="Reporte_final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Reporte_final_files/libs/quarto-html/anchor.min.js"></script>
<link href="Reporte_final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Reporte_final_files/libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Reporte_final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Reporte_final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Reporte_final_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="Reporte_final_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="Reporte_final_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

<style>
  body {
    margin: 2.54cm;  /* Márgenes estilo Google Docs */
    text-align: justify; /* Justificación del texto */
  }
</style>


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología"><span class="header-section-number">2</span> Metodología</a>
  <ul class="collapse">
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables"><span class="header-section-number">2.1</span> Variables</a></li>
  <li><a href="#metodos" id="toc-metodos" class="nav-link" data-scroll-target="#metodos"><span class="header-section-number">2.2</span> Metodos</a></li>
  </ul></li>
  <li><a href="#análisis" id="toc-análisis" class="nav-link" data-scroll-target="#análisis"><span class="header-section-number">3</span> Análisis</a>
  <ul class="collapse">
  <li><a href="#análisis-descriptivos" id="toc-análisis-descriptivos" class="nav-link" data-scroll-target="#análisis-descriptivos"><span class="header-section-number">3.1</span> Análisis Descriptivos</a></li>
  <li><a href="#análisis-bivariados" id="toc-análisis-bivariados" class="nav-link" data-scroll-target="#análisis-bivariados"><span class="header-section-number">3.2</span> Análisis Bivariados</a>
  <ul class="collapse">
  <li><a href="#análisis-entre-la-correlación-de-las-variables-satifacción-a-la-democracia-saf_demo-y-edad" id="toc-análisis-entre-la-correlación-de-las-variables-satifacción-a-la-democracia-saf_demo-y-edad" class="nav-link" data-scroll-target="#análisis-entre-la-correlación-de-las-variables-satifacción-a-la-democracia-saf_demo-y-edad"><span class="header-section-number">3.2.1</span> Análisis entre la correlación de las variables Satifacción a la democracia (saf_demo) y Edad</a></li>
  <li><a href="#análisis-entre-la-correlación-de-las-variables-satifacción-a-la-democracia-saf_demo-y-confianza-a-los-poderes-del-estado-conf_gob-conf_jub-conf_cong" id="toc-análisis-entre-la-correlación-de-las-variables-satifacción-a-la-democracia-saf_demo-y-confianza-a-los-poderes-del-estado-conf_gob-conf_jub-conf_cong" class="nav-link" data-scroll-target="#análisis-entre-la-correlación-de-las-variables-satifacción-a-la-democracia-saf_demo-y-confianza-a-los-poderes-del-estado-conf_gob-conf_jub-conf_cong"><span class="header-section-number">3.2.2</span> Análisis entre la correlación de las variables Satifacción a la democracia (saf_demo) y Confianza a los poderes del estado (conf_gob, conf_jub, conf_cong)</a></li>
  <li><a href="#análisis-entre-la-correlación-de-las-variables-confianza-a-los-poderes-del-estado-conf_gob-conf_jub-conf_cong-y-edad" id="toc-análisis-entre-la-correlación-de-las-variables-confianza-a-los-poderes-del-estado-conf_gob-conf_jub-conf_cong-y-edad" class="nav-link" data-scroll-target="#análisis-entre-la-correlación-de-las-variables-confianza-a-los-poderes-del-estado-conf_gob-conf_jub-conf_cong-y-edad"><span class="header-section-number">3.2.3</span> Análisis entre la correlación de las variables Confianza a los poderes del estado (conf_gob, conf_jub, conf_cong) y Edad</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conlusión" id="toc-conlusión" class="nav-link" data-scroll-target="#conlusión"><span class="header-section-number">4</span> Conlusión</a></li>
  <li><a href="#bibliografia" id="toc-bibliografia" class="nav-link" data-scroll-target="#bibliografia"><span class="header-section-number">5</span> Bibliografia</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo final correlacional Satisfacción con la democracia</h1>
<p class="subtitle lead">Estadística Correlacional 2025, Carrera de Sociología - Universidad de Chile</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Fernanda Barrios </p>
             <p>Matilda Fuenzalida </p>
             <p>Ambar Urbina </p>
             <p>Ignacio Muñoz </p>
             <p>Josefa Ubilla </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">23 de noviembre de 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'pacman' was built under R version 4.3.3</code></pre>
</div>
</div>
<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>Para esta investigación utilizaremos el Estudio Longitudinal Social de Chile (ELSOC) estudio único en Chile y América Latina, el cual encuesta anualmente a una muestra representativa de la población urbana en Chile a lo largo de una década, con el fin de evaluar cómo piensan, sienten y se comportan los chilenos en torno a un conjunto de temas referidos al conflicto y la cohesión social en el país. A través de los datos se buscará medir la percepción de la calidad de la democracia, que será entendida como la valoración subjetiva de las personas respecto al proceso de participación e influencia política en la ciudadanía.</p>
<p>Durante los últimos años, Chile ha mostrado una notable desconexión con sus fuerzas políticas, esta desconexión llegó a su cúspide con el estallido social en octubre del 2019, pero ya venía revelándose desde hace tiempo a través de una baja participación electoral. Disi y Mardones (2019) apuntan a que la desafección tiene un efecto negativo tanto en la participación política convencional y no convencional, pero sobre todo en la primera, por lo que a mayor desconexión con la política del país, menor es la participación electoral. Es por esto que nos parece relevante analizar la legitimidad que los ciudadanos dan al sistema político Chileno, ya que su funcionamiento no se sostiene solo con que haya sido escogido por una mayoría sino también por la satisfacción de la ciudadanía, Sepulveda y Garrido (2022) plantean que la satisfacción con la democracia depende también de la confianza que la ciudadanía tenga en sus instituciones y que tan representados y escuchados se sientan por estas, esto es importante ya que como Riffo (2019) señala, quienes sienten insatisfacción con la democracia desconfían más en las instituciones ligadas a esta. Según Molina y Levine (2007) la calidad de la democracia debe ser medida a partir de cinco dimensiones conceptuales, decisión electoral, participación, respeto a la voluntad popular, responsabilidades y soberanía. ELSOC considera la medición operacional de la percepción de la calidad de la democracia en Chile, esto está incluido en el módulo C de la encuesta “Ciudadanía y democracia” que utiliza varios ítems, en su mayoría de tipo ordinal, buscando medir el nivel de acuerdo con cada pregunta, para luego abordar el nivel de confianza en distintas instituciones. La escala buscará medir cómo perciben los chilenos la calidad de la democracia, a partir de preguntas que apuntan a la confianza en los tres poderes del estado. Medir la calidad de la democracia y a su vez entender cómo los ciudadanos perciben la misma, resulta relevante ya que es determinante para el desarrollo de un país (Sanchez, Ganatios, 2011), tanto por la participación política como por la representatividad.</p>
<p>El objetivo principal de este trabajo es analizar la relación que existe entre variables sociodemográficas (edad) y actitudinales (confianza en las poderes del Estado) con la percepción que existe de la calidad democrática en Chile, esperando que los hallazgos nos ayuden a comprender los efectos de la desconfianza en esta y como estos desafían la legitimidad del sistema político en Chile. Para cumplir con este objetivo, nuestras hipótesis son;</p>
<ul>
<li>H1 : A mayor edad, mayor será la satisfacción con el funcionamiento de la democracia.</li>
<li>H2: Existe una relación entre la confianza en los tres poderes del estado y la satisfacción a la democracia.</li>
<li>H3: A una menor edad, mayor será la confianza a los tres poderes del Estado.</li>
</ul>
</section>
<section id="metodología" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Metodología</h1>
<p>La presente sección muestra el diseño metodológico utilizado para analizar la satisfacción con el funcionamiento de la democracia en Chile y su relación con la edad y la confianza en tres instituciones clave del Estado: Gobierno, Poder Judicial y Congreso Nacional. El estudio emplea datos del Estado Longitudinal Social de Chile (ELSOC), ola 7 (2023), correspondiente al módulo “Ciudadanía y Democracia”. Esta encuesta de panel es representativa de la población urbana entre 18 y 75 años, lo que permite observar cambios y continuidades en percepciones ciudadanas. Para este análisis se trabajó con los casos que presentan información completa en las variables seleccionadas, garantizando consistencia en los resultados.</p>
<p>El estudio se centra en una variable dependiente (satisfacción con la democracia) y tres variables independientes relacionadas con la confianza institucional, además de la edad como variable continua complementaria. Todas las medidas pertenecen al módulo C del cuestionario, que evalúa percepciones subjetivas sobre el funcionamiento democratico. Los procedimientos estadísticos aplicados fueron seleccionados según el nivel de medición de cada variable, combinando métodos descriptivos, correlaciones y pruebas de asociación, con el fin de asegurar rigor analítico y coherencia en el contraste de las hipótesis planteadas.</p>
<section id="variables" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="variables"><span class="header-section-number">2.1</span> Variables</h2>
<p>La única variable dependiente es “satisfacción con la democracia” que pertenece al código c01 y fue renombrada como “saf_demo”. Corresponde a la pregunta “¿Cuán satisfecho o insatisfecho está usted con el funcionamiento de la democracia en Chile?, medida originalmente en una escala ordinal de 1= nada satisfecho a 5= muy satisfecho. Debido a la presencia de categorías con baja frecuencia en los valores superiores de la escala, se procedió a recodificar en tres niveles conceptualmente coherentes: Baja (1 - 2), Media (3), Alta (4 - 5). Esta recodificación permite obtener distribuciones más equilibradas y asegurar el cumplimiento de los supuestos métodos estadísticos empleados.</p>
<p>Por otro lado, las tres variables independientes pertenecen al ítem C05, y son “confianza en el Estado” que corresponde al código c05_01 y fue renombrada como “conf_gob”, la segunda es “confianza en el poder judicial” que corresponde al código c05_05 y fue renombrada como “conf_jud”, y por último la variable “confianza en el congreso nacional” perteneciente al código c05_07 fue renombrada como “conf_cong”. En un principio estas utilizaban una escala donde 1 significa “Nada” y 5 significa “Mucho”, sin embargo al igual que con la variable dependiente la escala fue recodificada a tres niveles conceptuales, baja, media y alta confianza, con el fin de evitar celdas vacías y obtener distribuciones más estables para el análisis.</p>
<p>Estas tres variables provienen del ítem C05: “Utilizando una escala donde 1 representa “Nada” y 5 “Mucho”, ¿Podría decirme cuánto confía usted en cada una de las siguientes instituciones?” Las escalas originales fueron recodificadas a los tres niveles conceptuales.</p>
<p>La variable continua que registra la edad (edad_enc) declarada por los participantes en años cumplidos, presenta una distribución no normal y se relaciona con variables ordinales, su análisis se efectuó mediante estadísticos no paramétricos.</p>
<p>Con el fin de asegurar la limpieza y una cohesión analitica de la base de datos, se aplicó un proceso previo al tratamiento donde los valores que son atípicos o de codificación especial (-888, -999, -777, -666) pasaron por la recodificación como valores perdidos (NA), posterior a esto se aplicó el método listwise, ya que el volumen original de 2726 observaciones, posibilita el asumir que el porcentaje de casos perdidos es considerablemente bajo, garantizando así que el proceso de eliminación de los casos incompletos no afectará de una manera significativa a la representatividad de la muestra. La principal ventaja de utilizar este método es tener la posibilidad de obtener y utilizar una base de datos que cuente con casos completos, lo que garantiza que cada correlación estadísticas se utiliza el mismo conjunto de datos, lo que permite mantener una buena coherencia y un profundo nivel de comparación entre los análisis que se realicen.</p>
</section>
<section id="metodos" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="metodos"><span class="header-section-number">2.2</span> Metodos</h2>
<p>La elección de los métodos estadísticos se basa en el nivel de medición de las variables, la distribución observada y los objetivos de contraste de hipótesis. El análisis se divide en métodos descriptivos, pruebas de hipótesis y estimación de tamaños de efecto.</p>
<p>En el caso de la primera hipótesis: A mayor edad, mayor será la satisfacción con el funcionamiento de la democracia. Se optó por emplear el coeficiente de correlación Spearman, dado que ambas variables se comportan como ordinales y no presentan distribución normal. Este método no paramétrico permite evaluar asociaciones monotónicas y manejar empates en las categorías, por lo que resulta la opción más pertinente para este tipo de datos.</p>
<p>Para la segunda hipótesis, que analiza la correlación entre la confianza de los tres poderes del Estado y la satisfacción con la democracia, fue necesario recodificar las variables de confianza en categorías (baja, media y alta), lo que permitió construir tablas de contingencia y aplicar la prueba de Chi - cuadrado de independencia, complementada con el coeficiente V de Cramer para estimar la magnitud del efecto y determinar la fuerza real de la asociación.</p>
<p>Finalmente para la tercera hipótesis, que evalúa la relación entre la edad y la confianza de las instituciones, nuevamente se utilizó Spearman ya que tanto la edad como los niveles de confianza corresponden a escalas ordinales. Este método permite identificar si existe una tendencia monotónica entre ambas variables sin exigir normalidad ni linealidad. De este modo cada prueba estadística fue seleccionada en coherencia con las características de las variables y con los requerimientos analíticos del estudio, asegurando consistencia metodológica en el contraste de las hipótesis planteadas.</p>
<p>En todas las hipótesis se reportó tamaño del efecto, siguiendo los criterios de Cohen: &lt;0.1: muy pequeño, 0.1 - 0.3: pequeño, 0.3 - 0.5: moderado, &gt;0.5: grande. Estos criterios permiten interpretar la relevancia substantiva de los hallazgos, más allá de su significancia estadística.</p>
</section>
</section>
<section id="análisis" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Análisis</h1>
<section id="análisis-descriptivos" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="análisis-descriptivos"><span class="header-section-number">3.1</span> Análisis Descriptivos</h2>
<p>Para dar inicio al análisis del fenómeno que se pretende estudiar, se comenzará con un análisis univariado de las variables con respecto a estadíticos descriptivos y frecuencias.</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tabla de estadísticos descriptivos por variable</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: #078 !important;">variable</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: #078 !important;">n</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: #078 !important;">minimo</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: #078 !important;">maximo</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: #078 !important;">media</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: #078 !important;">mediana</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: #078 !important;">sd</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: #078 !important;">cv</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Confianza Congreso</td>
<td style="text-align: right;">2528</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">51.43</td>
</tr>
<tr class="even">
<td style="text-align: left;">Confianza Gobierno</td>
<td style="text-align: right;">2528</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2.11</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: right;">54.03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Confianza Judicial</td>
<td style="text-align: right;">2528</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2.05</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">49.76</td>
</tr>
<tr class="even">
<td style="text-align: left;">Edad</td>
<td style="text-align: right;">2528</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">48.05</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">12.02</td>
<td style="text-align: right;">25.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Satisfacción Democracia</td>
<td style="text-align: right;">2528</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2.25</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">51.11</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A partir de los datos se puede analizar que el nivel de confianza al congreso, su mediana posee un valor de 1, ubicándose así en el valor más bajo, el CV que tiene un valor de 51.43 indicando alta dispersión relativa. La confianza en el gobierno y en el poder judicial muestran valores de medias de 2.11 y un 2.05, ambos con un CV que cercano al 50%, lo que muestra que hay una fuerte variabilidad entre las respuestas. La variable de edad posee un valor de 25.02 en su CV, lo que confirma una distribución de datos que es más homogénea. La satisfacción con la democracia, es baja con una media de 2.25 y un CV de 51.11, mostrando una dispersión importante respecto de las percepciones ciudadanas.</p>
<p><strong>Gráfico 1.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_final_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En el gráfico 1 de histograma muestra por un lado que hay una alta concentración de personas encuestadas que se encuentran en un rango entre los 40 y 60 años, lo que explica los valores de 48 de media y 49 de mediana que se reportaron en la tabla 1, y por otro lado la presencia de casos en edades más bajas respecto de la media y la mediana demuestra una dispersión de los datos que es importante, lo que explica también coherentemente el valor de 12 años en la desviación estándar. A modo de síntesis el gráfico no hace más que confirmar que si bien existe una distribución amplia de la edad pero que esta amplia distribución es también medianamente relativa, con una alta concentración en la tercera edad y sin notorias asimetrías.</p>
<p><strong>Grafico 2.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_final_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Este gráfico muestra que la mayor frecuencia de respuestas se asocian al primer nivel de satisfacción con un total de 847 respuestas, seguido de los niveles 2 (267 respuestas) y 3 (647 respuestas). Esto muestra que la mayoría de los encuestados muestran una baja o moderada valoración de la democracia. Sin embargo los niveles 4 (263) y 5 (104), mostrando frecuencias menores a los niveles anteriores. Esta distribución está en coherencia con las medias (2.25) y la mediana (2) las cuales muestran un nivel generalizado de baja satisfacción. Este gráfico muestra una inclinación general hacia la insatisfacción, a pesar de que hay una cierta variabilidad que busca revelar las diferencias entre las respuestas.</p>
<p><strong>Grafico 3.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_final_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El nivel 1 “nada de confianza” tiene una frecuencia con 1036, concentrando un 41% de la muestra. Seguido por el nivel 3; confianza moderada y el nivel 2; poca confianza, evidenciando que los valores de mayor frecuencia señalan una nula-moderada confianza al gobierno. Los niveles 3, 4 y 5 en conjunto suman 909 casos. Esto explica la fuerte concentración de datos que también coincide con la media y la mediana. Su desviación estándar de 1,14 demuestra una dispersión moderada, ya que a pesar de que los valores bajos tengan mayor frecuencia, el nivel 3 hace contrapeso al concentrar una alta cantidad de datos, alterando la media. Este gráfico nos indica que hay una baja confianza de parte de la ciudadanía en el gobierno.</p>
<p><strong>Grafico 4.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_final_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El nivel 1 “nada de confianza” con un 39% de los datos, seguido por el nivel 2 y 3 los valores que más se repiten son aquellos que indican una confianza en el poder judicial baja o nula, concentrando entre los 3 niveles más bajos un 91,5% de los datos. La frecuencia de alta confianza es significativamente menor, lo cual coincide con la media (2,05) y la mediana (2), esto indica que la tendencia central es a la desconfianza. La desviación estándar de 1,02 indica una dispersión moderada, a pesar de que la mayoría de datos se agrupen en valores bajos, hay una variación en las respuestas, sobre todo con el nivel 3. Este gráfico refleja una baja confianza de parte de la ciudadanía en el poder judicial.</p>
<p><strong>Grafico 5.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_final_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Nuevamente el nivel 1 muestra un alto porcentaje (52%) de los datos de la muestra, seguido por el nivel 2 los valores indican una baja confianza son los de mayor frecuencia. Los valores 3, 4 y 5 que señalan una confianza moderada-total tienen frecuencias bajas, las tres en conjunto suman 579 casos, lo que representa un 23% de la muestra. Esto explica la alta concentración de datos en el lado negativo de la tabla, ya que los dos niveles más bajos hay más del doble de los datos que acumulan el resto de niveles, por lo que, como señala la media (1,75) y la mediana (1) existe una evidente desconfianza en el Congreso Nacional. La desviación estándar de este análisis es la más baja de las tres instituciones analizadas, de los tres poderes del estado, el Congreso Nacional es la institución en la que menos confían las personas.</p>
</section>
<section id="análisis-bivariados" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="análisis-bivariados"><span class="header-section-number">3.2</span> Análisis Bivariados</h2>
<p>En esta sección se presentan los análisis bivariados realizados para contrastar las tres hipótesis de investigación. Se consideran, por una parte la tabla resumen de correlaciones y asociaciones y por otra, los gráficos bivariados construidos para facilitar la interpretación sustantiva de los resultados. En todos los casos se reportan el nivel de significancia y el tamaño del efecto, de acuerdo con los criterios de Cohen.</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Resumen de correlaciones y asociaciones de las hipótesis</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: #078 !important;">Hipotesis</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: #078 !important;">Variables</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: #078 !important;">Test</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: #078 !important;">Coeficiente</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: #078 !important;">p_valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">Edad vs Satisfacción con la democracia</td>
<td style="text-align: left;">Spearman ρ</td>
<td style="text-align: left;">-0.04</td>
<td style="text-align: left;">0.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">Satisfacción vs Confianza Gobierno</td>
<td style="text-align: left;">Chi-cuadrado / V de Cramer</td>
<td style="text-align: left;">X²=570.82, V=0.336</td>
<td style="text-align: left;">0.00000000022</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">Satisfacción vs Confianza Poder Judicial</td>
<td style="text-align: left;">Chi-cuadrado / V de Cramer</td>
<td style="text-align: left;">X²=155.35, V=0.200</td>
<td style="text-align: left;">0.00000000022</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">Satisfacción vs Confianza Congreso Nacional</td>
<td style="text-align: left;">Chi-cuadrado / V de Cramer</td>
<td style="text-align: left;">X²=165.54, V=0.210</td>
<td style="text-align: left;">0.00000000022</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">Edad vs Gobierno</td>
<td style="text-align: left;">Spearman ρ</td>
<td style="text-align: left;">-0.034</td>
<td style="text-align: left;">0.0812</td>
</tr>
<tr class="even">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">Edad vs Poder Judicial</td>
<td style="text-align: left;">Spearman ρ</td>
<td style="text-align: left;">0.025</td>
<td style="text-align: left;">0.2152</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">Edad vs Congreso Nacional</td>
<td style="text-align: left;">Spearman ρ</td>
<td style="text-align: left;">0.072</td>
<td style="text-align: left;">0.0003</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<section id="análisis-entre-la-correlación-de-las-variables-satifacción-a-la-democracia-saf_demo-y-edad" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="análisis-entre-la-correlación-de-las-variables-satifacción-a-la-democracia-saf_demo-y-edad"><span class="header-section-number">3.2.1</span> Análisis entre la correlación de las variables Satifacción a la democracia (saf_demo) y Edad</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Tabla de correlación: Edad y Satisfacción de la Democracia
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: #078 !important;">Estadístico</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: #078 !important;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rho - coeficiente</td>
<td style="text-align: right;">-0.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">p-valor</td>
<td style="text-align: right;">0.04</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La tabla muestra una correlación de Spearman muestra un coeficiente ρ = -0.04 con p = 0.04, lo que indica una asociación estadísticamente significativa pero extremadamente débil. Aunque el valor p indica significancia estadística, el coeficiente es tan cercano a cero que la relación carece de relevancia práctica. Esto implica que la edad no explica de manera sustantiva las diferencias en satisfacción democrática. En términos generales las variaciones entre personas jóvenes y mayores son mínimas y no conforman un patrón consistente, lo que se confirma posteriormente en los gráficos por grupos etarios.</p>
<p><strong>Gráfico H1.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_final_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico 1 evidencia que la satisfacción baja predomina en todos los grupos etarios, desde jóvenes hasta adultos mayores. Aunque existe una ligera tendencia a mayor insatisfacción en los grupos de mayor edad, las diferencias entre tramos son mínimas y no configuran un patrón claro. La satisfacción media y alta se mantienen relativamente estables entre grupos, lo que coincide con el coeficiente de correlación casi nulo. Por último, el gráfico confirma que la edad no desempeña un rol relevante en la evaluación del funcionamiento democrático.</p>
</section>
<section id="análisis-entre-la-correlación-de-las-variables-satifacción-a-la-democracia-saf_demo-y-confianza-a-los-poderes-del-estado-conf_gob-conf_jub-conf_cong" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="análisis-entre-la-correlación-de-las-variables-satifacción-a-la-democracia-saf_demo-y-confianza-a-los-poderes-del-estado-conf_gob-conf_jub-conf_cong"><span class="header-section-number">3.2.2</span> Análisis entre la correlación de las variables Satifacción a la democracia (saf_demo) y Confianza a los poderes del estado (conf_gob, conf_jub, conf_cong)</h3>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tabla de Chi-cuadrado y V de Cramer: Asociación entre satisfacción con la democracia y confianza en los tres poderes del Estado</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: #078 !important;">Variable</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: #078 !important;">X2</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: #078 !important;">df</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: #078 !important;">p.valor</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: #078 !important;">V.de.Cramer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Confianza Gobierno</td>
<td style="text-align: right;">570.82</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">0.00000000000000022</td>
<td style="text-align: right;">0.336</td>
</tr>
<tr class="even">
<td style="text-align: left;">Confianza Poder Judicial</td>
<td style="text-align: right;">155.35</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">0.00000000000000022</td>
<td style="text-align: right;">0.200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Confianza Congreso Nacional</td>
<td style="text-align: right;">165.54</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">0.00000000000000022</td>
<td style="text-align: right;">0.210</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Los resultados muestran una asociación significativa entre la confianza en los tres poderes del Estado y la satisfacción con la democracia. Las pruebas de Chi - Cuadrado indican que está relación existe en los tres casos y los valores de V de Cramer revelan que el efecto es moderado para el Gobierno (V= 0.336) y débil pero consistente para el Poder Judicial (V= 0.200) y el congreso Nacional (V= 0.210). Esto indica que la confianza institucional influye en la satisfacción democrática, siendo el Gobierno la institución más vinculada a esta evaluación. Los resultados respaldan la existencia de un vínculo claro entre ambas dimensiones.</p>
<p><strong>Gráfico H2.1: Correlacción entre Confianza al Gobierno y Satifacción a la democracia.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_final_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico muestra un patrón de que quienes presentan baja confianza en el Gobierno concentran los niveles más altos de baja satisfacción con la democracia (47.7%) y a medida que la confianza aumenta hacia niveles medios y altos, las proporciones de satisfacción media y alta se incrementan levemente, aunque siguen siendo minoritarias. La celda “baja confianza - baja satisfacción” domina la distribución, lo que evidencia una relación positiva y significativa entre ambas variables. En conclusión el gráfico refuerza la asociación identificada en el análisis estadístico.</p>
<p><strong>Grafico H2.2: Correlación entre la Confianza al Poder judicial y la Satifacción a la Democracia.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_final_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico muestra que las personas con baja confianza en el Poder Judicial concentran los niveles más altos de baja satisfacción con la democracia (44.4%). A medida que la confianza aumenta hacia niveles medios y altos, las proporciones de satisfacción también disminuyen considerablemente, lo cual evidencia un patrón claro de asociación positiva entre ambas variables. Aunque los porcentajes de satisfacción alta son bajos en todos los niveles, el gradiente del gráfico confirma que una menor confianza judicial se relaciona sistemáticamente con una menor satisfacción democrática.</p>
<p><strong>Grafico H2.3: Correlación entre la Confianza al Congreso Nacional y la Satifacción a la Democracia.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_final_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico muestra un claro patrón que es que las personas con baja confianza en el Congreso concentran los niveles más altos de baja satisfacción con la democracia. A medida que aumenta la confianza hacia niveles medios y altos, las proporciones de satisfacción media y alta se incrementan, aunque en menor medida. La celda “baja confianza - baja satisfacción” presenta la mayor frecuencia, lo que evidencia la relación significativa encontrada en los análisis. El gráfico permite visualizar de forma simple el gradiente positivo entre ambas variables.</p>
<p>En conclusión, los resultados evidencian un gradiente claro, es decir a mayor confianza institucional, mayor satisfacción con la democracia y con ellos la segunda hipótesis queda firmemente respaldada.</p>
</section>
<section id="análisis-entre-la-correlación-de-las-variables-confianza-a-los-poderes-del-estado-conf_gob-conf_jub-conf_cong-y-edad" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="análisis-entre-la-correlación-de-las-variables-confianza-a-los-poderes-del-estado-conf_gob-conf_jub-conf_cong-y-edad"><span class="header-section-number">3.2.3</span> Análisis entre la correlación de las variables Confianza a los poderes del estado (conf_gob, conf_jub, conf_cong) y Edad</h3>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tabla de correlaciones de Spearman: Relación entre edad y confianza en los tres poderes del Estado</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: #078 !important;">Variable</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: white !important; background-color: #078 !important;">Rho</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: #078 !important;">p_valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Edad-Gobierno</td>
<td style="text-align: right;">-0.035</td>
<td style="text-align: left;">0.0812</td>
</tr>
<tr class="even">
<td style="text-align: left;">Edad-Poder Judicial</td>
<td style="text-align: right;">-0.025</td>
<td style="text-align: left;">0.2152</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Edad-Congreso Nacional</td>
<td style="text-align: right;">-0.072</td>
<td style="text-align: left;">0.0003</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>La tercera hipótesis plantea que a menor edad, mayor será la confianza en los tres poderes del Estado. Para contrastar se estimaron correlaciones de Spearman entre la edad y los niveles originales de confianza en cada institución. Las correlaciones obtenidas son -0.035 para la confianza en el Gobierno, 0.025 para la confianza en el Poder Judicial y 0.072 para la confianza en el Congreso Nacional. Solo esta última alcanza significancia estadística, sin embargo en los tres casos los valores se mantienen por debajo del umbral de 0.10, lo que indica que la relación es extremadamente débil.</p>
<p><strong>Gráfico H3.1: Confianza en el Gobierno por Grupo Etario.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_final_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico muestra que la baja confianza en el Gobierno predomina en todos los grupos etarios, con porcentajes que van desde 60% hasta cerca de 68% y la confianza media y alta se distribuyen de manera similar entre tramos etarios, sin diferencias claras. Aunque los adultos mayores presentan ligeramente más baja confianza, las variaciones son pequeñas. La estructura general del gráfico es homogénea, lo que coincide con la correlación muy débil observada en la tabla.</p>
<p><strong>Gráfico H3.2: Confianza en el Poder Judicial por Grupo Etario.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_final_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En todos los grupos etarios predomina la baja confianza en el Poder Judicial, con niveles de confianza alta que no superan el 9%. Las diferencias entre cohortes son mínimas, ya que los porcentajes se mantienen relativamente estables entre jóvenes, adultos y adultos mayores. Lo cual refuerza la conclusión de que la edad no determina los niveles de confianza judicial y coincide con la correlación cercana a cero observada en los resultados estadísticos.</p>
<p><strong>Gráfico H3.3: Confianza en el Congreso Nacional por Grupo Etario.</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Reporte_final_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico evidencia un nivel de baja confianza muy alto en todos los grupos etarios, superando el 70% y llegando a más del 80% en adultos mayores. La confianza media y alta con minoritarias en todos los tramos. Aunque los niveles de desconfianza aumentan ligeramente con la edad, las diferencias no son suficientes para establecer un patrón claro. Estos resultados coinciden con la correlación muy débil encontrada, mostrando que la desconfianza es transversal a todas las edades. Por lo tanto la hipótesis tres se rechaza en términos prácticos, ya que la edad no parece explicar los niveles de confianza institucional.</p>
</section>
</section>
</section>
<section id="conlusión" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Conlusión</h1>
<p>A partir del presente estudio que tuvo como objetivo analizar la relación entre la percepción de la calidad de la democracia en Chile y las variables como la edad y confianza a los poderes del Estado, se puede concluir que en Chile a modo general existe una baja satisfacción y alta desconfianza en la democracia. A partir del análisis bivariado se puede concluir que, para la primera hipotesis según la correlación de Spearman la edad no define totalmente las diferencias en satisfacción democrática, demostrando que en todos los grupos etarios existe una baja satisfacción. Por otro lado, el resultado de Chi-Cuadrado de la segunda hipótesis muestra una asociación significativa entre la confianza en los tres poderes del Estado y la satisfacción con la democracia, principalmente en el caso del Gobierno. Finalmente, en la hipótesis que afirma que a menor edad mayor confianza en los tres poderes del estado, a través de la correlación de Spearman se puede afirmar que no existe una relación significativa.</p>
<p>Las principales limitaciones que presenta esta investigación corresponden, por un lado, a la recodificación de las variables a tres niveles, que inevitablemente significa la pérdida de información. Así mismo el uso del tratamiento “Listwise”, a pesar de que permite mantener un orden y coherencia para el análisis, se reduce el tamaño de la muestra y por lo tanto se pierde información. Mientras que por otro lado, a pesar de que el uso de la correlación de Spearman logra evidenciar si existe relación entre variables, no nos permite establecer causalidad. Para futuras investigaciones sería ideal poder analizar los datos de varias olas de la encuesta ELSOC, que permitirá identificar cambios o patrones en el tiempo, y así mismo se podría determinar de mejor manera la causalidad. Por otro lado, esto resultaría interesante para poder relacionar los datos con la coyuntura del país y en qué medida afectan, por ejemplo en el caso de estallido social o de la pandemia.</p>
</section>
<section id="bibliografia" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Bibliografia</h1>
<p>Disi Pavlic, R., &amp; Mardones Arévalo, R. (2019). Chile 2010: la desafección política y su impacto en la participación política convencional y no convencional. <em>Revista Del CLAD Reforma Y Democracia, 73</em>. https://doi.org/10.69733/clad.ryd.n73.a177</p>
<p>Sepúlveda-Rodríguez, I., &amp; Garrido-Vergara, L. (2022). Satisfacción con la democracia y legitimidad en Chile. <em>Revista De Sociología, 37</em>(2), 1–15. https://doi.org/10.5354/0719-529X.2022.69099</p>
<p>Riffo Galán, F. (2019). <em>¿Qué influye en la confianza en las instituciones? Evidencia empírica para el caso Chileno</em> [Seminario de Grado]. Universidad del Bío-Bío. http://repobib.ubiobio.cl/jspui/bitstream/123456789/3073/1/Riffo%20Gal%C3%A1n%2C%20Fabian.pdf</p>
<p>Levine, D. H., &amp; Molina, J. E. (2007). La calidad de la democracia en América Latina: una visión comparada. <em>América Latina Hoy, (46)</em>, 17–46. http://www.redalyc.org/articulo.oa?id=308004502</p>
<p>Patrón Sánchez, F., &amp; León Ganaba, L. E. (2011). Calidad de la democracia y percepción ciudadana en América Latina. Revista Mañongo Nº 35, VOL. XVIII, , https://www.servicio.bc.uc.edu.ve/postgrado/manongo35/art10.pdf</p>
<p>Equipo ELSOC. (2023). <em>Manual metodológico ELSOC 2016-2022</em>. Centro de Estudios de Conflicto y Cohesión Social (COES). https://manual-metodologico-elsoc.netlify.app/manual-metodologico-elsoc.pdf</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>