<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Trabajo final Estadística Correlacional</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="trabajo final1_files/libs/clipboard/clipboard.min.js"></script>
<script src="trabajo final1_files/libs/quarto-html/quarto.js"></script>
<script src="trabajo final1_files/libs/quarto-html/popper.min.js"></script>
<script src="trabajo final1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="trabajo final1_files/libs/quarto-html/anchor.min.js"></script>
<link href="trabajo final1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="trabajo final1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="trabajo final1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="trabajo final1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="trabajo final1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo final Estadística Correlacional</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Paz Isla Rocío Suárez Catalina Santos Monserrat Aravena Pía Solá </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="confianza-en-el-gobierno-de-chile-un-análisis-de-factores-sociodemográficos-elsoc-2019" class="level2">
<h2 class="anchored" data-anchor-id="confianza-en-el-gobierno-de-chile-un-análisis-de-factores-sociodemográficos-elsoc-2019"><strong>Confianza en el Gobierno de Chile: Un análisis de factores sociodemográficos (ELSOC 2019)</strong></h2>
<p><strong>Resumen:</strong> La presente investigación buscó medir el nivel de confianza en el gobierno en el caso chileno mediante un análisis del año 2019 de Encuesta Longitudinal Social de Chile, medición sobre la cual se plantean cinco hipótesis que buscan estimar la relación que tiene conocer su correlación con las variables nivel educativo, sexo, salario, edad y satisfacción con la democracia. Mediante un exámen de esta medición se emplearon técnicas de análisis cuantitativo orientadas a evaluar la existencia de asociaciones significativas entre las variables de estudio, además se aplicaron distintos procedimientos de contraste de hipótesis nula, lo que permitió examinar de manera diferenciada los patrones de relación con la confianza institucional. Como resultado, se encontró evidencia a favor de asociaciones entre la confianza en el gobierno y nivel educacional; confianza en el gobierno y edad; confianza en el gobierno y sexo; y confianza en el gobierno; confianza en el gobierno y salario y satisfacción con la democracia, sin embargo, estas asociaciones fueron de baja magnitud.</p>
</section>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>El presente documento busca analizar el nivel de confianza en el gobierno en Chile y su relación con&nbsp; las variables de nivel educacional, salario, edad, sexo y satisfacción con la democracia respectivamente, a partir de la base de datos ELSOC 2016-2023. Debido a que se realiza un cuestionario por año, se tomó la decisión de analizar nuestra variable dependiente mediante el sondeo correspondiente al año 2019 por su relación con la creciente inestabilidad en torno a la confianza en el gobierno.</p>
<p>Se considera que el estudio sobre el nivel de confianza en el gobierno –variable dependiente seleccionada– es de suma relevancia bajo el marco de desafección y desconfianza política que manifiesta la ciudadanía. Dentro de PNUD (2019). Diez años de auditoría a la democracia: Antes del estallido. Santiago de Chile, Programa de las Naciones Unidas para el Desarrollo se afirma que “la vitalidad de la democracia se ve comprometida por una acentuada disminución en la confianza ciudadana hacia las instituciones, al mismo tiempo en la región de América Latina, diversas naciones atraviesan coyunturas de inestabilidad social, política y económica que representan serias amenazas para la solidez democrática” (p.&nbsp;40)</p>
<p>Debido a que el objetivo es medir el nivel de confianza en las instituciones, encarnado principalmente en la confianza en el gobierno, se puede establecer que la relación se enmarca en un análisis referente a la cohesión social, pues “la confianza entre las personas mantiene una cercana relación con respecto a la cohesión social, ya que en la medida en que los agentes creen en la palabra del otro, pueden establecer metas comunes y trabajar en conjunto para lograrlas, pero cuando la confianza es baja la cohesión social tiende a desestabilizarse” (Keefer &amp; Scartascini, 2022, p.&nbsp;6).&nbsp;</p>
<p>Considerando lo anterior, analizaremos el nivel de confianza en el gobierno, entendiendo por ello “la forma en que las personas perciben y evalúan su desempeño en función de una serie de objetivos y de principios normativos según los cuales se espera que operen” (Pena, 2023, p.&nbsp;60). En ese contexto, es relevante precisar que, con el objetivo de que los ciudadanos confíen en el gobierno, deben reconocer el marco normativo correspondiente para eventualmente ponderar su funcionamiento.&nbsp;</p>
<p>Además, comprenderemos la relevancia que tiene conocer la relación entre el nivel de confianza en el gobierno y la edad, pues según Morales (2020) un predictor sistemático del nivel de confianza en las instituciones refiere a la edad, donde los más jóvenes muestran menores niveles de confianza en las instituciones. Inclusive, Morales (2008) evidencia que la edad surge como un determinante en la confianza institucional, pues las personas mayores confían más que los jóvenes, y en ese sentido, si no hay mejoras en la percepción de confianza en el gobierno, es altamente probable que esta desconfianza tienda al alza de mantenerse esta tendencia.</p>
<p>Con respecto al sexo, OECD (2025) evidencia que en los países de América Latina y El Caribe es posible identificar una diferencia entre hombres y mujeres con respecto a la confianza en el gobierno, en donde el porcentaje de los hombres corresponde a un 37% mientras que el de las mujeres corresponde a un 34%. A pesar de que esta diferencia es pequeña, varía en los distintos países, puesto que en los casos de Colombia y México esta brecha es más amplia. (p.&nbsp;57).</p>
<p>Con respecto a la relación entre el nivel educativo y el nivel de confianza en el gobierno, “en países de la OCDE la población con menores niveles educativos, estatus social e ingresos y las personas que perciben inseguridad financiera o altos niveles de preocupación económica reportan tener niveles más bajos de confianza en el gobierno” (Irarrázaval y Cruz, 2023, p.&nbsp;10)</p>
<p>Finalmente, bajo este enfoque se plantean cuatro hipótesis principales:</p>
<ul>
<li><p>En primer lugar, se espera identificar que a mayor nivel educacional habrá un mayor nivel de confianza en el gobierno.</p></li>
<li><p>En segundo lugar, se espera evidenciar que a mayor edad habrá un mayor nivel de confianza en el gobierno.</p></li>
<li><p>En tercer lugar, se espera encontrar una diferencia por sexo con respecto al nivel de confianza en el gobierno.</p></li>
<li><p>En cuarto lugar, se espera encontrar evidencia que indique que a mayor salario habrá una mayor confianza en el gobierno.</p></li>
<li><p>En quinto lugar, se espera encontrar evidencia que a mayor satisfacción con la democracia habrá mayor nivel de confianza en el gobierno.&nbsp;</p></li>
</ul>
<p><strong>Metodología</strong></p>
<p>Se recurrió al uso del software R Studio, seleccionando la base longitudinal 2016-2023, específicamente la “ola 4” correspondiente a la medición del año 2019, debido a su pertinencia en un contexto de percepción de legitimidad inestable reforzado por la literatura revisada. El Estudio Longitudinal Social de Chile tiene como objetivo final aportar datos empíricos sobre la evolución del conflicto y cohesión social en el país, mediante la incorporación de opiniones, creencias y actitudes de la población sobre aquellos datos empíricos (Centro de Estudios de Conflicto y Cohesión Social [COES], 2018, párr. 1).</p>
<p>En ese sentido, el análisis llevado a cabo es de carácter cuantitativo, en donde se seleccionó como variable dependiente el nivel de confianza en el gobierno, y como variables independientes: nivel educativo, edad, sexo. salario y satisfacción con la democracia. Las variables seleccionadas fueron; “C05_01” renombrada por “confianza_gobierno”, “M01” renombrada por “nivel_educacional”, “M13” renombrada por “salario”, “M0_edad” renombrada por “edad”,&nbsp; “M0_sexo” renombrada por “sexo”, “M13” renombrada por “salario” y “C01” renombrada por “satisfaccion_demo”.&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Cargar librerias</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, <span class="co"># Manipulacion datos</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               sjPlot, <span class="co"># Graficos y tablas</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>               sjmisc, <span class="co"># Descriptivos</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>               kableExtra, <span class="co"># Tablas</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>               psych, <span class="co"># Estadísticos</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>               broom,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>               rempsyc) <span class="co"># Varios</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) <span class="co"># para desactivar notacion cientifica</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co"># para limpiar el entorno de trabajo</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Cargar base de datos</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"C:/Users/Acer/Downloads/trabajo estadistica/input/ELSOC_Long_2016_2023.RData"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>datos_ola_w04 <span class="ot">&lt;-</span> elsoc_long_2016_2023 <span class="sc">%&gt;%</span> </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ola <span class="sc">==</span> <span class="dv">4</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>elsoc_w04 <span class="ot">&lt;-</span> elsoc_long_2016_2023 <span class="sc">%&gt;%</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ola <span class="sc">==</span> <span class="dv">4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    c05_01,           <span class="co"># confianza gobierno</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    m01,              <span class="co"># nivel educacional</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    m13,              <span class="co"># salario</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    m0_sexo,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    m0_edad,</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    c01               <span class="co">#satisfaccion en la democracia</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">confianza_gobierno   =</span> c05_01,</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">nivel_educacional =</span> m01,</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">salario           =</span> m13,</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">sexo              =</span> m0_sexo,</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">edad              =</span> m0_edad,</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">satisfaccion_demo =</span> c01</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code></code></pre>
<p>Con respecto al tratamiento de valores perdidos, se reemplazaron valores fuera de rango (-666, -777, -888, -999) por NA, al igual que los valores máximos fueron recodificados a NA. Si bien las variables “sexo”, “edad” y “satisfacción_demo” presentan niveles muy bajo de NA, y las variables “confianza_gobierno” y “nivel_educacional” representan solo un aproximado entre el 0% y 0.35% de valores perdidos, la variable “salario” presenta un alto porcentaje de NA (40% aproximadamente). Es por ello que se tomó la decisión metodológica de aplicar el tratamiento de pairwise en el caso de los análisis bivariados, debido a que con ello, es posible recuperar la máxima cantidad posible de casos disponibles en cada correlación.</p>
<p>Las variables “confianza_gobierno” y “nivel_educacional” fueron recodificadas. La primera fue recodificada en dos categorías (“confianza_gobierno_recode”) para realizar una correlación tetracórica con la variable dicotómica “sexo”, y la segunda fue recodificada en cinco categorías con el objetivo de agrupar los niveles educativos y lograr una mejor interpretación de los análisis bivariados. Con respecto a la demás variables, no hubo necesidad de recodificar, pues el nivel de medición de las variables seleccionadas cumplían el sentido del atributo (medición en donde el puntaje más bajo representa menor presencia –o ausencia– del atributo, y el más alto representa mayor presencia del mismo).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Reemplazar valores no válidos (-999, -888, -777, -666) con NA</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>elsoc_w04 <span class="ot">&lt;-</span> elsoc_w04 <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">everything</span>(),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>      <span class="sc">~</span> <span class="fu">case_when</span>(</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>        .x <span class="sc">%in%</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">666</span>, <span class="sc">-</span><span class="dv">777</span>, <span class="sc">-</span><span class="dv">888</span>, <span class="sc">-</span><span class="dv">999</span>) <span class="sc">~</span> <span class="cn">NA</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> .x</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar el valor máximo real (excluyendo NAs)</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>max_salario <span class="ot">&lt;-</span> <span class="fu">max</span>(elsoc_w04<span class="sc">$</span>salario, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Reemplazar el valor máximo por NA</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>elsoc_w04 <span class="ot">&lt;-</span> elsoc_w04 <span class="sc">%&gt;%</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">salario =</span> <span class="fu">ifelse</span>(salario <span class="sc">==</span> max_salario, <span class="cn">NA</span>, salario))</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>elsoc_w04 <span class="ot">&lt;-</span> elsoc_w04 <span class="sc">%&gt;%</span> </span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">salario =</span> <span class="fu">if_else</span>(</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>      salario <span class="sc">==</span> <span class="fu">max</span>(salario, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>      <span class="cn">NA_real_</span>,</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>      salario</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>maximo <span class="ot">&lt;-</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">max</span>(elsoc_w04<span class="sc">$</span>salario, <span class="at">na.rm =</span> T)</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>elsoc_w04 <span class="ot">&lt;-</span> elsoc_w04 <span class="sc">%&gt;%</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(<span class="sc">!</span>salario <span class="sc">%in%</span> </span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>                  maximo)</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_scatter</span>(<span class="at">data =</span> elsoc_w04,</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>                     <span class="at">x =</span> salario,</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> salario)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.
ℹ The deprecated feature was likely used in the sjPlot package.
  Please report the issue at &lt;https://github.com/strengejacke/sjPlot/issues&gt;.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trabajo-final1_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(elsoc_w04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> confianza_gobierno nivel_educacional    salario             sexo      
 Min.   :1.000      Min.   : 1.00     Min.   :      0   Min.   :1.000  
 1st Qu.:1.000      1st Qu.: 4.00     1st Qu.: 300000   1st Qu.:1.000  
 Median :1.000      Median : 5.00     Median : 400000   Median :2.000  
 Mean   :1.608      Mean   : 5.25     Mean   : 523644   Mean   :1.625  
 3rd Qu.:2.000      3rd Qu.: 7.00     3rd Qu.: 600000   3rd Qu.:2.000  
 Max.   :5.000      Max.   :10.00     Max.   :6000000   Max.   :2.000  
 NA's   :12         NA's   :4         NA's   :1397                     
      edad       satisfaccion_demo
 Min.   :19.00   Min.   :1.000    
 1st Qu.:36.00   1st Qu.:1.000    
 Median :49.00   Median :1.000    
 Mean   :48.77   Mean   :1.707    
 3rd Qu.:61.00   3rd Qu.:2.000    
 Max.   :92.00   Max.   :5.000    
                 NA's   :98       </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#RECODIFICACION DE GOBIERNO</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>elsoc_w04 <span class="ot">&lt;-</span> elsoc_w04 <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">confianza_gobierno_recode =</span> <span class="fu">case_when</span>(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>      confianza_gobierno <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">1</span>,  <span class="co"># ausencia</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>      confianza_gobierno <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">1</span>,  <span class="co"># presencia</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>      confianza_gobierno <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>      confianza_gobierno <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>      confianza_gobierno <span class="sc">==</span> <span class="dv">5</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span>  <span class="co"># Asignar NA en caso de valores faltantes</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Recodificacion de nivel educacional</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>elsoc_w04 <span class="ot">&lt;-</span> elsoc_w04 <span class="sc">%&gt;%</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">nivel_educ_recode =</span> <span class="fu">case_when</span>(</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>      nivel_educacional <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>      nivel_educacional <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>      nivel_educacional <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>      nivel_educacional <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>      nivel_educacional <span class="sc">==</span> <span class="dv">5</span> <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>      nivel_educacional <span class="sc">==</span> <span class="dv">6</span> <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>      nivel_educacional <span class="sc">==</span> <span class="dv">7</span> <span class="sc">~</span> <span class="dv">4</span>,</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>      nivel_educacional <span class="sc">==</span> <span class="dv">8</span> <span class="sc">~</span> <span class="dv">4</span>,</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>      nivel_educacional <span class="sc">==</span> <span class="dv">9</span> <span class="sc">~</span> <span class="dv">5</span>,</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>      nivel_educacional <span class="sc">==</span> <span class="dv">10</span> <span class="sc">~</span> <span class="dv">5</span>,</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span>   <span class="co"># datos perdidos u otros valores</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code></code></pre>
<p>La variable dependiente seleccionada “confianza_gobierno” corresponde a un nivel de medición de tipo ordinal con un rango de 1 a 5 en donde 1 corresponde a “Nada de confianza”, y 5 corresponde a “Mucha confianza”. El objetivo de esta variable es medir el nivel declarado de confianza en el gobierno por parte de la muestra.&nbsp;</p>
<p>Con respecto a nuestras variables independientes; “nivel_educacional” corresponde a un nivel de medición de tipo ordinal con un rango de 1 a 10 en donde 1 corresponde a “Sin estudios” y 10 corresponde a “Estudios de posgrado (magíster o doctorado)”; “salario” corresponde a un nivel de medición de tipo continua, pues en el cuestionario se solicita que el encuestado constate su ingreso mensual en pesos; “edad” corresponde a un nivel de medición de tipo continua al igual que la anterior, debido a que se solicita que el encuestado constate su edad en años; “sexo” corresponde a un nivel de medición de tipo dicotómica en donde 1 = hombre, 2 = mujer; y finalmente, la variable “satisfaccion_demo” corresponde a un nivel de medición ordinal con un rango de 1 a 5, en donde 1 corresponde a “Nada satisfecho” y 5 corresponde a&nbsp; “Muy satisfecho”. El objetivo principal de esta variable es medir el nivel de satisfacción con la percepción del funcionamiento de la&nbsp; democracia en el país.</p>
<p>Para contrastar las hipótesis planteadas, se utilizó la técnica de contraste de hipótesis nula con el fin de determinar si las asociaciones observadas pueden extrapolarse a la población. En primer lugar, se utilizó correlación de Spearman (entre variables ordinales) para dos correlaciones: “confianza_gobierno” con “nivel_educacional” y “confianza_gobierno” con “satisfaccion_demo”. En segundo lugar, se utilizó correlación de Pearson (entre variables continuas)para dos correlaciones: “confianza_gobierno” con “edad” y “confianza_gobierno” y “salario”. Finalmente, y en tercer lugar, se utilizó correlación tetracórica, Chi cuadrado y Coeficiente Phi (entre variables categóricas): “confianza_gobierno_recode” con “sexo”. Con respecto a la interpretación del tamaño del efecto, se realizó siguiendo los criterios de Cohen, que distinguen efectos pequeños (≈0,10), medianos (≈0,30) y grandes (≈0,50).</p>
<p>A continuación se presenta una tabla de descriptivos básicos que incluye medidas de tendencia central, dispersión&nbsp; y distribución:</p>
<p><strong>Tabla</strong> <strong>1. Tabla de estadísticos descriptivos</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggpubr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggpubr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'ggplot2'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:psych':

    %+%, alpha</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:sjPlot':

    set_theme</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear tabla descriptiva</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>tabla_descriptivos <span class="ot">&lt;-</span> elsoc_w04 <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(confianza_gobierno, nivel_educacional, salario, sexo, edad, satisfaccion_demo) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  sjmisc<span class="sc">::</span><span class="fu">descr</span>(<span class="at">show =</span> <span class="fu">c</span>(<span class="st">"label"</span>, <span class="st">"range"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"NA.prc"</span>, <span class="st">"n"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear tabla con ggtexttable</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>tabla_plot <span class="ot">&lt;-</span> <span class="fu">ggtexttable</span>(</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  tabla_descriptivos,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">rows =</span> <span class="cn">NULL</span>, <span class="co"># Sin nombres de filas</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">theme =</span> <span class="fu">ttheme</span>(<span class="st">"light"</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar tabla como un gráfico</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tabla_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trabajo-final1_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<pre><code></code></pre>
<p>Mediante un análisis descriptivo de las variables se realizó la estimación de medidas de tendencia central (media y mediana), de dispersión (desviación estándar y rango), así como también la presentación de frecuencias en el caso de las variables categóricas (“salario”) y ordinales (“confianza_gobierno”, “nivel_educacional” y “satisfaccion_demo”).&nbsp;</p>
<p>En primer lugar, se observa que la variable “confianza_gobierno” presenta una media de 1.60 y una desviación estándar de 0.86, pudiendo establecerse un bajo nivel de confianza en las instituciones, pues el grueso de los valores se concentran entre 1 (“nada”) y 2 (“poca”).</p>
<p>En segundo lugar, se observa que la variable “nivel_educacional” presenta una media de 5.25 y una desviación estándar de 2.23, lo que sugiere que la mayoría de nuestro N se posiciona principalmente en niveles educacionales medios y medios altos (mayoritariamente desde educación media completa a educación superior técnica-universitaria).</p>
<p>En tercer lugar, se observa que la variable “salario” presenta una media de $1.028.307 y una desviación estándar de $2.224.337, lo que nos indica que quienes tienen altas remuneraciones alteran la estructura real de los salarios.&nbsp;</p>
<p>En cuarto lugar, se observa que la variable “sexo” presenta una media de 1.62 y una desviación estándar de 0.48, lo que nos sugiera que la muestra se distribuye equitativamente entre hombres (1) y mujeres (2), sin valores perdidos.</p>
<p>En quinto lugar, se observa que la variable&nbsp; “edad”, presenta una media de 48.7 años y una desviación estándar de 15.41, lo que indica una muestra heterogénea en cuanto a las edades (desde jóvenes hasta la personas mayores).</p>
<p>En sexto lugar, se observa que la variable “satisfacción_demo” presenta una media de 1.70 y una desviación estándar de 0.91, lo que se describe como un nivel de satisfacción promedio bajo, pero con una dispersión o variabilidad moderada en las respuestas de la muestra.</p>
<p><strong>Análisis</strong></p>
<p>A continuación se presentarán las pruebas bivariadas realizadas para evaluar las asociaciones entre la variable confianza en el gobierno y los distintos predictores seleccionados que se describieron anteriormente. Para cada relación se formula la hipótesis nula (H₀) y alternativa (H₁), junto con el coeficiente correspondiente, su significancia y la magnitud del efecto según los criterios de Cohen.</p>
<p><strong>1.Relación entre confianza en el gobierno y nivel educacional</strong></p>
<p>Hipótesis:</p>
<p>H₀: (confianza_gobierno, nivel_educacional) = 0</p>
<p>H₁: (confianza_gobierno, nivel_educacional) ≠ 0</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Correlacion Spearman,confianza en el gobierno y nivel educacional</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(elsoc_w04<span class="sc">$</span>confianza_gobierno, elsoc_w04<span class="sc">$</span>nivel_educ_recode, <span class="at">method =</span> <span class="st">"spearman"</span>, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(elsoc_w04$confianza_gobierno,
elsoc_w04$nivel_educ_recode, : Cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  elsoc_w04$confianza_gobierno and elsoc_w04$nivel_educ_recode
S = 6139044680, p-value = 0.0002461
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
0.06283657 </code></pre>
</div>
</div>
<pre><code></code></pre>
<p>Para realizar el análisis bivariado correspondiente a la primera hipótesis se utilizó el coeficiente de correlación de Spearman, dado que ambas variables, “confianza_gobierno” y “nivel_educacional”, son de naturaleza ordinal. El valor obtenido fue de 0,06, lo que indica una correlación pequeña, pero positiva entre las variables. El valor de p fue de 0,0004, siendo menor al valor teórico (p &lt; 0,05). Por tanto, la correlación observada es estadísticamente significativa según Cohen. De esta manera, con un 95% de confianza, es posible rechazar la hipótesis nula, la cual sugiere que no existe asociación entre nivel educacional y confianza institucional y, por lo tanto, se puede afirmar que existe una asociación estadísticamente significativa, aunque de magnitud baja, entre ambas variables.</p>
<p><strong>Tabla 3. Tabla de contingencia entre confianza en el gobierno y nivel educacional recodificado</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabla de contingencia,confianza en el gobierno y nivel educacional</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_xtab</span>(elsoc_w04<span class="sc">$</span>confianza_gobierno, elsoc_w04<span class="sc">$</span>nivel_educ_recode, <span class="at">show.row.prc =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Grado de confianza:<br>El Gobierno</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="5">nivel_educ_recode</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">1</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">2</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">3</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">4</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">5</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Nada</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">295</span><br><span style="color:#333399;">14.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">465</span><br><span style="color:#333399;">22.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">705</span><br><span style="color:#333399;">34.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">344</span><br><span style="color:#333399;">16.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">227</span><br><span style="color:#333399;">11.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">2036</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Poca</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">107</span><br><span style="color:#333399;">13.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">168</span><br><span style="color:#333399;">20.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">253</span><br><span style="color:#333399;">31.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">173</span><br><span style="color:#333399;">21.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">105</span><br><span style="color:#333399;">13&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">806</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Algo</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">55</span><br><span style="color:#333399;">12.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">89</span><br><span style="color:#333399;">20.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">132</span><br><span style="color:#333399;">30.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">91</span><br><span style="color:#333399;">20.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">71</span><br><span style="color:#333399;">16.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">438</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Bastante</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">14</span><br><span style="color:#333399;">14.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">24</span><br><span style="color:#333399;">25.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">18</span><br><span style="color:#333399;">18.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">19</span><br><span style="color:#333399;">20&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">20</span><br><span style="color:#333399;">21.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">95</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Mucha</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">5</span><br><span style="color:#333399;">20&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">5</span><br><span style="color:#333399;">20&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">8</span><br><span style="color:#333399;">32&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">4</span><br><span style="color:#333399;">16&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">3</span><br><span style="color:#333399;">12&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">25</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">476</span><br><span style="color:#333399;">14&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">751</span><br><span style="color:#333399;">22.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1116</span><br><span style="color:#333399;">32.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">631</span><br><span style="color:#333399;">18.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">426</span><br><span style="color:#333399;">12.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">3400</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="7">χ<sup>2</sup>=34.790 · df=16 · Cramer's V=0.051 · Fisher's p=0.003</td> 
</tr>
 
</tbody></table>
</div>
</div>
<pre><code></code></pre>
<p>En la tabla se observa una diferencia entre los distintos niveles educacionalesrespecto a la confianzaen el gobierno. Algunos grupos educativos muestran una mayor proporción de personas con confianza baja, mientras que los otros presentan mayores porcentajes en niveles medios o altos de confianza. Esto indica, que la distribución de la confianza no es completamente homogénea entre los distintos niveles educativos</p>
<p>Los resultados muestran que existen diferencias entre los grupos educacionales en su nivel de confianza, pero estas diferencias son de <strong>baja magnitud</strong>, lo que sugiere que el nivel educacional tiene un efecto limitado sobre la variación en la confianza hacia el gobierno</p>
<p><strong>Figura 1.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico de nivel educacional</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar data sin NA</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>elsoc_w04_clean <span class="ot">&lt;-</span> elsoc_w04 <span class="sc">%&gt;%</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(confianza_gobierno),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(nivel_educ_recode))</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico de puntos, confianza en el gobierno y nivel educacional</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_scatter</span>(</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> elsoc_w04, </span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> confianza_gobierno,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> nivel_educ_recode, </span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.line =</span> <span class="st">"lm"</span>,      <span class="co"># Mostrar línea de regresión</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">show.ci =</span> <span class="cn">TRUE</span>,       <span class="co"># Mostrar intervalo de confianza</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">dot.size =</span> <span class="dv">3</span>,</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">dot.labels =</span> elsoc_w04<span class="sc">$</span>idencuesta   <span class="co"># Usa aquí la variable que quieras como etiqueta</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Asociación entre confianza en el gobierno y nivel educacional"</span>, </span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Nivel educacional"</span>, </span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Confianza en el gobierno"</span>,</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Fuente: Elaboración propia en base a ELSOC 2019."</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trabajo-final1_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico visualiza un diagrama de dispersión a partir del cual es posible evidenciar una correlación positiva, pero débil entre las variables “confianza_gobierno” y “nivel_educacional” (rho = 0.063, p &lt; 0.001) indicando que a medida que aumenta la confianza en el gobierno, aumenta a su vez el nivel educacional, pero manera leve. La dispersión de los puntos indica que los niveles educacionales se distribuyen de manera similar en los niveles de confianza.</p>
<p><strong>2.Relación entre confianza en el gobierno y edad</strong></p>
<p>H₀: (confianza_gobierno, edad) = 0</p>
<p>H₁: (confianza_gobierno, edad) ≠ 0</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Correlacion de Pearson, confianza en el gobierno y edad</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(elsoc_w04<span class="sc">$</span>confianza_gobierno, elsoc_w04<span class="sc">$</span>edad, <span class="at">method =</span> <span class="st">"pearson"</span>, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  elsoc_w04$confianza_gobierno and elsoc_w04$edad
t = 8.4854, df = 3402, p-value &lt; 0.00000000000000022
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.1109065 0.1767064
sample estimates:
      cor 
0.1439656 </code></pre>
</div>
</div>
<p>En cuanto al análisis bivariado correspondiente a la segunda hipótesis, se utilizó coeficiente de correlación de Pearson, dado que la variable “confianza_gobierno” es ordinal y “edad”. El valor obtenido fue de 0,14, lo que indica una correlación pequeña y positiva entre las variables “edad” y “confianza_gobierno”. El valor de p fue menor a 0,001, siendo inferior al valor teórico (p &lt; 0,05), por lo que la correlación observada es estadísticamente significativa según Cohen. De esta manera, con un 95% de confianza, es posible rechazar la hipótesis nula que plantea que no existe asociación entre la edad y la confianza en el gobierno y, por lo tanto, se puede afirmar que existe una asociación estadísticamente significativa, aunque de baja magnitud, entre ambas variables.</p>
<p><strong>3.Correlación tetracórica entre confianza en el gobierno y sexo</strong></p>
<p>Hipótesis:</p>
<p>H₀: (confianza_gobierno, sexo) = 0</p>
<p>H₁: (confianza_gobierno, sexo) ≠ 0</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Correlacion tetracorica, confianza en el gobierno y sexo</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>tetratorica_confianza_gobierno_sexo <span class="ot">&lt;-</span> elsoc_w04 <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(confianza_gobierno_recode, sexo)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">tetrachoric</span>(tetratorica_confianza_gobierno_sexo, <span class="at">na.rm =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: psych::tetrachoric(x = tetratorica_confianza_gobierno_sexo, na.rm = T)
tetrachoric correlation 
                          cnf__ sexo 
confianza_gobierno_recode  1.00      
sexo                      -0.07  1.00

 with tau of 
confianza_gobierno_recode                      sexo 
                     0.98                     -0.32 </code></pre>
</div>
</div>
<p>La correlación tetracórica entre las variables confianza en el gobierno y sexo arrojó un coeficiente de –0,07. Este valor indica una asociación negativa muy débil entre ambas variables.</p>
<p><strong>Prueba Chi-Cuadrado</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Chi2</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>chi_results1 <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(elsoc_w04<span class="sc">$</span>confianza_gobierno_recode, elsoc_w04<span class="sc">$</span>sexo)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>chi_results1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  elsoc_w04$confianza_gobierno_recode and elsoc_w04$sexo
X-squared = 3.9055, df = 1, p-value = 0.04813</code></pre>
</div>
</div>
<p>La prueba Chi-cuadrado muestra una asociación estadísticamente significativa (p = 0.048 &lt; 0.05), lo que indica que la confianza en el gobierno y el sexo están relacionados de manera no aleatoria. Esto significa que la distribución de los niveles de confianza en el gobierno varía ligeramente según el sexo.</p>
<p>Aunque la asociación es débil, el resultado sigue siendo significativo y sugiere que podrían existir diferencias entre hombres y mujeres en cómo evalúan o expresan su confianza en el gobierno. Este hallazgo, si bien de baja magnitud, refuerza la importancia de seguir investigando cómo el género podría influir en las actitudes políticas o la percepción institucional.</p>
<p><strong>Cálculo de Phi</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Phi</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>chi_results1 <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(elsoc_w04<span class="sc">$</span>confianza_gobierno_recode, elsoc_w04<span class="sc">$</span>sexo)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(elsoc_w04 <span class="sc">%&gt;%</span> <span class="fu">select</span>(confianza_gobierno_recode, elsoc_w04<span class="sc">$</span>sexo)) <span class="sc">%&gt;%</span> <span class="fu">nrow</span>()</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>phi <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(chi_results1<span class="sc">$</span>statistic <span class="sc">/</span> n)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>phi</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> X-squared 
0.03389223 </code></pre>
</div>
</div>
<p>El valor de Phi obtenido (0.0339) indica que la fuerza de la asociación entre confianza en el gobienro y sexo es extremadamente débil. Aunque el análisis Chi-cuadrado pudiera mostrar significancia estadística dependiendo del valor p, el tamaño del efecto medido por Phi revela que la relación entre ambas variables es prácticamente inexistente en términos sustantivos.</p>
<p><strong>Tabla 4. Tabla cruzada entre confianza en el gobierno recodificado y sexo</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabla cruzadas, confianza en el gobierno_recode y sexo</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_xtab</span>(elsoc_w04<span class="sc">$</span>confianza_gobierno_recode, elsoc_w04<span class="sc">$</span>sexo, <span class="at">show.row.prc =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">confianza_gobierno_recode</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">Sexo del<br>entrevistado</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Hombre</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Mujer</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">1</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1049</span><br><span style="color:#333399;">36.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1797</span><br><span style="color:#333399;">63.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">2846</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">2</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">231</span><br><span style="color:#333399;">41.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">327</span><br><span style="color:#333399;">58.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">558</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1280</span><br><span style="color:#333399;">37.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">2124</span><br><span style="color:#333399;">62.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">3404</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">χ<sup>2</sup>=3.906 · df=1 · &amp;phi=0.035 · p=0.048</td> 
</tr>
 
</tbody></table>
</div>
</div>
<p>En la Tabla 4, se observan diferencias en la confianza en el gobierno entre hombres y mujeres. Entre quienes presentan baja confianza (categoría 1), el 36.9% son hombres y el 63.1% son mujeres, lo que muestra que dentro de esta categoría las mujeres están más representadas. Por otro lado, entre quienes presentan alta confianza (categoría 2), el 41.4% son hombres y el 58.6% son mujeres, lo que indica nuevamente una mayor presencia femenina, pero con una diferencia ligeramente menor que en la categoría anterior.</p>
<p>En conjunto, los resultados muestran que, en esta muestra, las mujeres tienden a concentrarse tanto en los niveles bajos como altos de confianza, aunque con mayor proporción en la categoría de baja confianza. Los hombres, en contraste, tienen una presencia algo menor en ambos niveles, pero relativamente mayor en la categoría de alta confianza en comparación con la proporción femenina en la misma categoría.</p>
<p>Si bien la relación entre el sexo y la confianza en el gobierno resulta estadísticamente significativa (χ² = 3.906, p = 0.048), la fuerza de asociación es muy débil (φ = 0.035). Esto significa que, aunque existe una diferencia entre hombres y mujeres en la distribución de los niveles de confianza, esta diferencia es pequeña y la relación entre ambas variables es limitada.</p>
<p><strong>Figura 2.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico de barras, confianza en el gobierno y sexo</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">subset</span>(elsoc_w04, <span class="sc">!</span><span class="fu">is.na</span>(confianza_gobierno) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(sexo)), <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(confianza_gobierno), <span class="at">fill =</span> <span class="fu">factor</span>(sexo))) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"1"</span> <span class="ot">=</span> <span class="st">"#A8E6CF"</span>, <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"#FFD1BA"</span>), <span class="co"># Colores morado y rosado</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Masculino"</span>, <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"Femenino"</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribucion de confianza en el gobierno según sexo"</span>,</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Confianza en el gobierno"</span>,</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Número de personas"</span>,</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Sexo"</span>,</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Fuente: Elaboración propia en base a ELSOC 2019"</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Nada"</span>,</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"Poca"</span>,</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"Algo"</span>,</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"4"</span> <span class="ot">=</span> <span class="st">"Bastante"</span>,</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"5"</span> <span class="ot">=</span> <span class="st">"Mucha"</span></span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"#000"</span>),</span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">"#000"</span>),</span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">"#000"</span>),</span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">color =</span> <span class="st">"#000"</span>),</span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">color =</span> <span class="st">"#000"</span>),</span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#000"</span>),</span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">8</span>, <span class="at">color =</span> <span class="st">"#000"</span>)</span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trabajo-final1_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico sugiere que las mujeres tienden a reportar niveles ligeramente menores de confianza en el gobierno, pero las diferencias visuales son pequeñas, lo que coincide con la magnitud débil de la asociación encontrada en la prueba estadística. Esto indica que, aunque el sexo y la confianza en el gobierno están asociados, la fuerza de la relación es baja, por lo que las diferencias entre ambos grupos no son pronunciadas.</p>
<p><strong>4.Relación entre confianza en el gobierno y salario</strong></p>
<p>Hipótesis:</p>
<p>H₀: (confianza_gobierno, salario) = 0</p>
<p>H₁: (confianza_gobierno, salario) ≠ 0</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Correlacion Pearson, confianza en el gobierno y salario</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(elsoc_w04<span class="sc">$</span>confianza_gobierno, elsoc_w04<span class="sc">$</span>salario, <span class="at">method =</span> <span class="st">"pearson"</span>, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  elsoc_w04$confianza_gobierno and elsoc_w04$salario
t = 4.7189, df = 2013, p-value = 0.000002534
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.06121202 0.14759318
sample estimates:
      cor 
0.1045999 </code></pre>
</div>
</div>
<p>Para analizar la relación entre la confianza en el gobierno y el salario, se aplicó un análisis bivariado mediante Pearson. El coeficiente obtenido fue de 0,109, lo que indica una correlación pequeña y positiva entre ambas variables. El valor de p fue 0,870, siendo inferior al valor teórico (p &lt; 0,05), por lo que la correlación observada es estadísticamente significativa según los criterios de Cohen. De esta manera, con un 95% de confianza, es posible rechazar la hipótesis nula que plantea que no existe asociación entre el salario y la confianza en el gobierno. Por lo tanto, se puede afirmar que existe una asociación estadísticamente significativa, aunque de baja magnitud, entre ambas variables.</p>
<p><strong>5.Relación entre confianza en el gobierno y satisfacción con la democracia</strong></p>
<p>Hipótesis:</p>
<p>H₀: (confianza_gobierno, satisfaccion_demo) = 0</p>
<p>H₁: (confianza_gobierno, satisfaccion_demo) ≠ 0</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Correlacion Spearman, confianza en el gobierno y satisfaccion en la democracia</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(elsoc_w04<span class="sc">$</span>confianza_gobierno, elsoc_w04<span class="sc">$</span>satisfaccion_demo, <span class="at">method =</span> <span class="st">"spearman"</span>, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(elsoc_w04$confianza_gobierno,
elsoc_w04$satisfaccion_demo, : Cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  elsoc_w04$confianza_gobierno and elsoc_w04$satisfaccion_demo
S = 3357754154, p-value &lt; 0.00000000000000022
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.4464681 </code></pre>
</div>
</div>
<p>Para realizar el análisis entre la confianza en el gobierno y la satisfacción con la democracia se optó por el coeficiente de correlación de Spearman dada la naturaleza ordinal de las variables, midiendo así la fuerza y dirección de la asociación. El coeficiente obtenido fue de 0,4468607, lo que indica una correlación positiva de fuerza moderada. El valor p fue menor a 0,001, siendo menor al valor teórico (p &lt; 0,05), por lo que este resultado permite rechazar la hipótesis nula de no asociación entre confianza en el gobierno y satisfacción con la democracia con un 99,9% de confianza, confirmando que la relación observada es estadísticamente significativa. Es decir, los resultados permiten afirmar que las personas que tienden a reportar niveles más altos de confianza en el gobierno, también tienden a reportar niveles más altos de satisfacción con la democracia.</p>
<p><strong>Figura 3</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico de barras, Confianza en el gobierno y satisfaccion con la democracia</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">subset</span>(elsoc_w04, <span class="sc">!</span><span class="fu">is.na</span>(confianza_gobierno) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(satisfaccion_demo)), <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(confianza_gobierno), <span class="at">fill =</span> <span class="fu">factor</span>(satisfaccion_demo))) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"1"</span> <span class="ot">=</span> <span class="st">"#FEA790"</span>, <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"#FD844C"</span>, <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"#794D43"</span>, <span class="st">"4"</span> <span class="ot">=</span> <span class="st">"#358E96"</span>, <span class="st">"5"</span> <span class="ot">=</span> <span class="st">"#1A4F56"</span>), <span class="co"># Colores morado y rosado</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Nada"</span>, <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"Poco"</span>, <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"Algo"</span>, <span class="st">"4"</span> <span class="ot">=</span> <span class="st">"Bastante"</span>, <span class="st">"5"</span> <span class="ot">=</span> <span class="st">"Muy"</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribucion de confianza en el gobierno según la satisfaccion con la democracia"</span>,</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Confianza en el gobierno"</span>,</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Número de personas"</span>,</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Satisfaccion con la democracia"</span>,</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Fuente: Elaboración propia en base a ELSOC 2019"</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Nada"</span>,</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"Poco"</span>,</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"Algo"</span>,</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"4"</span> <span class="ot">=</span> <span class="st">"Bastante"</span>,</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"5"</span> <span class="ot">=</span> <span class="st">"Muy"</span></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"#000"</span>),</span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">"#000"</span>),</span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">"#000"</span>),</span>
<span id="cb41-27"><a href="#cb41-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">color =</span> <span class="st">"#000"</span>),</span>
<span id="cb41-28"><a href="#cb41-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">color =</span> <span class="st">"#000"</span>),</span>
<span id="cb41-29"><a href="#cb41-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#000"</span>)</span>
<span id="cb41-30"><a href="#cb41-30" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trabajo-final1_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico sugiere que la insatisfacción con la democracia se asocia a menores niveles de confianza en el gobierno, mientras que una mayor satisfacción con la democracia tiene una tendencia a aumentar con la confianza, aunque sigue siendo leve generalmente hablando dentro de la muestra.</p>
<p><strong>Discusión de resultados</strong></p>
<p>En relación con las hipótesis planteadas, los análisis muestran asociaciones significativas en algunos casos, aunque de magnitud pequeña, lo que sugiere que la confianza en las instituciones está influida por las variables seleccionadas, pero en un grado limitado.</p>
<p>En primer lugar, la asociación entre confianza en el gobierno y nivel educacional también resulta significativa, pero nuevamente con una magnitud muy baja. Esto plantea que la educación podría influir en la manera en que las personas evalúan a las instituciones, aunque su peso real es más bien acotado.</p>
<p>En segundo lugar, la relación entre confianza institucional y edad presenta una correlación positiva y significativa, aunque pequeña. Esto indica que, a medida que aumenta la edad, tiende a aumentar levemente la confianza en las instituciones. Si bien el efecto es débil, su significancia estadística sugiere que la edad opera como un factor que estructura, en parte, la percepción de la confianza en el gobierno.</p>
<p>En tercer lugar, la relación entre confianza en el gobierno (recodificada para correlación tetracórica) y sexo muestra una diferencia estadísticamente significativa, pero con un tamaño de efecto pequeño. Esto indica que existen variaciones de sexo en la confianza declarada, aunque estas diferencias no son lo suficientemente grandes como para sostener un patrón robusto.</p>
<p>En cuarto lugar, la relación entre confianza en el gobierno y salario arroja una correlación positiva y estadísticamente significativa. Esto sugiere que, en este caso, que a medida que los ingresos aumenten, tiende a aumentar ligeramente la confianza en el gobierno. Sin embargo, dado que la fuerza de la asociación es baja, el salario no constituye un determinante fuerte de la confianza institucional, sino más bien un factor que influye de manera limitada.</p>
<p>En quinto lugar, la relación entre confianza en el gobierno y satisfacción con la democracia evidencia una correlación estadísticamente significativa de un tamaño efecto mediana. Esto indicaría que el patrón observado en el gráfico sugiere una dependencia positiva, en otras palabras, la insatisfacción con la democracia tiende a ir de la mano con menores niveles de confianza y mientras que una mayor satisfacción con el sistema democrático tiende a aumentar a medida que crece la confianza</p>
<p>En conjunto, los resultados muestran que, aunque algunas asociaciones son significativas, los efectos tienden a ser pequeños. Esto implica que la confianza en las instituciones es un fenómeno complejo, posiblemente moldeado por múltiples dimensiones no incluidas en este análisis, y que las variables consideradas explican solo una fracción limitada de su variación.</p>
<p><strong>Conclusión</strong></p>
<p>El análisis de los factores que afectan la confianza en el gobierno de Chile, realizado con los datos de la Encuesta ELSOC correspondiente al año 2019, ha permitido identificar algunas asociaciones significativas –aunque de baja magnitud– entre la confianza en el gobierno y las variables seleccionadas. Se observó una relación positiva, aunque débil, con la edad y el nivel educacional, lo que sugiere que a mayor edad y mayor nivel educacional, mayor confianza en el gobierno. En contraste, el sexo mostró una correlación pequeña y negativa, y no se encontró una relación significativa con el salario, lo que sugiere que el ingreso no influye de manera determinante en la confianza hacia el gobierno. La relación más significativa se dio con la satisfacción con la democracia, lo que indica que la percepción de los ciudadanos con la democracia tiene un fuerte vínculo con su confianza en el gobierno.&nbsp;</p>
<p>No obstante, varias limitaciones afectan la interpretación de los resultados. En primer lugar, la baja magnitud de las correlaciones sugieren que las variables sociodemográficas sólo explicarían una parte pequeña del nivel de confianza en el gobierno y la variación de éste. Además, el alto porcentaje de valores perdidos en la variable salario limita su conclusión sobre la no asociación con la confianza en el gobierno.&nbsp;</p>
<p>Para futuras investigaciones, se hace necesario el análisis multivariado para evaluar el peso combinado de las variables sociodemográficas y asimismo explorar otros factores que podrían influir más fuertemente en la confianza en el gobierno. Finalmente, un análisis comparativo más detallado por sexo y edad arrojaría información más precisa sobre la desconfianza juvenil hacia el gobierno.&nbsp;</p>
<p><strong>Bibliografía</strong></p>
<p>Castro Riaño, L. C. (2020). La protesta social en América Latina: una aproximación a su fisonomía a propósito de los estallidos sociales de 2019. Revista Rumbos TS.</p>
<p>Centro de Estudios de Conflicto y Cohesión Social (COES). (2018). Manual de usuario de Estudio Longitudinal Social de Chile (ELSOC), primera ola (2016), versión 2.0. <a href="https://manual-metodologico-elsoc.netlify.app" class="uri">https://manual-metodologico-elsoc.netlify.app</a></p>
<p>Cerro Fernández, R. (2024). Del malestar al estallido social (2006-2019): estudio de la crisis de la representación política en Chile.</p>
<p>Durul, T. (2019, 23 de diciembre). El 2019, año de las protestas en el mundo. Agencia Anadolu. <a href="https://www.aa.com.tr/es/mundo/el-2019-a%C3%B1o-de-las-protestas-en-el-mundo/1682091" class="uri">https://www.aa.com.tr/es/mundo/el-2019-a%C3%B1o-de-las-protestas-en-el-mundo/1682091</a></p>
<p>Irarrazaval, I., &amp; Cruz, F. (2023). Confianza institucional en Chile: Un desafío para el desarrollo. Centro de Estudios Públicos. <a href="https://www.researchgate.net/profile/Florencia-Cruz/publication/381306498_Confianza_institucional_en_Chile_un_desafio_para_el_desarrollo/links/6667a69985a4ee7261b6f3a2/Confianza-institucional-en-Chile-un-desafio-para-el-desarrollo.pdf" class="uri">https://www.researchgate.net/profile/Florencia-Cruz/publication/381306498_Confianza_institucional_en_Chile_un_desafio_para_el_desarrollo/links/6667a69985a4ee7261b6f3a2/Confianza-institucional-en-Chile-un-desafio-para-el-desarrollo.pdf</a></p>
<p>Keefer, P., &amp; Scartascini, C. (2022). Confianza: la clave de la cohesión social y el crecimiento en América Latina y el Caribe (Resumen ejecutivo). <a href="https://doi.org/10.18235/0003911" class="uri">https://doi.org/10.18235/0003911</a></p>
<p>Morales Quiroga, Mauricio. (2008). Assessing Institutional Confidence in Chile: A Look from LAPOP’s Findings. Revista de ciencia política (Santiago), 28(2), 161-186. <a href="https://dx.doi.org/10.4067/S0718-090X2008000200007" class="uri">https://dx.doi.org/10.4067/S0718-090X2008000200007</a></p>
<p>Morales Quiroga, Mauricio. (2020). Estallido social en Chile 2019: participación, representación, confianza institucional y escándalos públicos. Análisis Político, 33(98), 3-25. <a href="https://doi.org/10.15446/anpol.v33n98.89407" class="uri">https://doi.org/10.15446/anpol.v33n98.89407</a></p>
<p>OECD. (2025). Encuesta de la OCDE sobre los determinantes de la confianza en las instituciones públicas de América Latina y el Caribe Resultados 2025. OECD Publishing. <a href="https://doi.org/10.1787/b4dea13c-es" class="uri">https://doi.org/10.1787/b4dea13c-es</a></p>
<p>Pena Ibarra, L. P. (2023). Evolución de la confianza en las instituciones en América Latina entre 1995 y 2021, un análisis transnacional, multinivel y longitudinal.</p>
<p>PNUD (2019). Diez años de auditoría a la democracia: Antes del estallido. Santiago de Chile, Programa de las Naciones Unidas para el Desarrollo</p>
<p>Segovia, C., Haye, A., González, R., Manzi, J., &amp; Carvacho, H. (2008). Confianza en instituciones políticas en Chile: un modelo de los componentes centrales de juicios de confianza. Revista de ciencia política (Santiago), 28(2), 39-60.</p>
<pre><code></code></pre>
<pre><code></code></pre>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>